import { APP_ROUTES } from "@/lib/routes";
import type { TargetLocale } from "@/lib/locale";
import { pickTargetCatalog } from "@/lib/pick-catalog";

export type WalletUiCopy = {
  pageTitle: string;
  recordHeaders: [string, string, string, string, string, string];
  balanceLabel: string;
  overdraftSuffix: (n: number) => string;
  couponLabel: string;
  couponSuffix: string;
  packageLabel: string;
  packageSuffix: string;
  online: string;
  auto: string;
  autoOff: string;
  corporate: string;
  warningOn: string;
  warningOffChip: string;
  warningModalTitle: string;
  warningRule1: string;
  warningRule1a: string;
  warningRule1b: string;
  warningRule2: string;
  warningRule3Before: string;
  warningRule3Bold: string;
  warningRule3After: string;
  warningThresholdLabel: string;
  warningAuto: string;
  warningCustom: string;
  warningOff: string;
  warningYuan: string;
  warningCancel: string;
  warningOk: string;
  payAmount: string;
  payMethod: string;
  otherAmount: string;
  alipay: string;
  otherPay: string;
  wechatPay: string;
  wechatShort: string;
  captcha: string;
  captchaSuccess: string;
  confirmPay: string;
  paying: string;
  payDisabled: string;
  payError: string;
  agreePrefix: string;
  agreeLink: string;
  agreeHref: string;
  recordsTitle: string;
  statusPending: string;
  statusSuccess: string;
  statusOther: string;
  empty: string;
  segmentAll: string;
  segmentAvailable: string;
  redeemCenter: string;
  redeemInputLabel: string;
  redeemPlaceholder: string;
  redeemSubmit: string;
  redeemSubmitting: string;
  redeemCancel: string;
  redeemSuccess: (n: number) => string;
  redeemFailed: string;
  quotaLabel: string;
  autoTitle: string;
  autoAlerts: [string, string, string];
  thresholdLabel: string;
  rechargeAmountLabel: string;
  otherAmountShort: string;
  thresholdHint: string;
  amountHint: string;
  autoPreview: (threshold: number, amount: number) => string;
  signNow: string;
};

const zhCN: WalletUiCopy = {
  pageTitle: "é’±åŒ…",
  recordHeaders: ["ç¼–å·", "æ—¶é—´", "å……å€¼æ¸ é“", "çŠ¶æ€", "é‡‘é¢", "æ“ä½œ"],
  balanceLabel: "ä½™é¢",
  overdraftSuffix: (n) => `ï¼ˆå‰©ä½™å¯é€æ”¯é¢åº¦ Â¥ ${n}ï¼‰`,
  couponLabel: "ä»£é‡‘åˆ¸",
  couponSuffix: "å¼ å¯ç”¨",
  packageLabel: "èµ„æºåŒ…",
  packageSuffix: "ä¸ªç”Ÿæ•ˆä¸­",
  online: "åœ¨çº¿å……å€¼",
  auto: "è‡ªåŠ¨å……å€¼",
  autoOff: "æœªå¼€å¯",
  corporate: "å¯¹å…¬è½¬è´¦æ±‡æ¬¾",
  warningOn: "ä½™é¢é¢„è­¦å·²å¼€å¯ (åŽ»è®¾ç½®)",
  warningOffChip: "ä½™é¢é¢„è­¦å·²å…³é—­ (åŽ»è®¾ç½®)",
  warningModalTitle: "ä½™é¢é¢„è­¦è®¾ç½®",
  warningRule1: "ä½™é¢é¢„è­¦åŒ…æ‹¬è‡ªåŠ¨ã€è‡ªå®šä¹‰ã€å…³é—­ä¸‰ç§æ¨¡å¼ï¼š",
  warningRule1a:
    "è‹¥è®¾ç½®ä¸ºè‡ªåŠ¨ï¼Œå½“è´¦æˆ·å‰©ä½™å¯ç”¨é¢åº¦ï¼ˆåŒ…æ‹¬å……å€¼ä½™é¢å’Œé€æ”¯é¢åº¦ï¼‰ä½ŽäºŽè¿‘ 7 æ—¥ API è°ƒç”¨äº§ç”Ÿçš„å……å€¼ä½™é¢å¹³å‡æ—¥æ¶ˆè´¹æ—¶è‡ªåŠ¨é¢„è­¦",
  warningRule1b:
    "è‹¥è®¾ç½®ä¸ºè‡ªå®šä¹‰ï¼Œå½“è´¦æˆ·å‰©ä½™å¯ç”¨é¢åº¦ï¼ˆåŒ…æ‹¬å……å€¼ä½™é¢å’Œé€æ”¯é¢åº¦ï¼‰ä½ŽäºŽè®¾ç½®é˜ˆå€¼æ—¶è‡ªåŠ¨é¢„è­¦",
  warningRule2: "ä½™é¢é¢„è­¦å°†åœ¨åŒ—äº¬æ—¶é—´æ¯å¤©ä¸Šåˆ 10 ç‚¹å‘é€é¢„è­¦çŸ­ä¿¡åŠé‚®ä»¶é€šçŸ¥",
  warningRule3Before: "é¦–æ¬¡å®Œæˆåœ¨çº¿å……å€¼æ—¶ï¼Œç³»ç»ŸæŒ‰",
  warningRule3Bold: "è‡ªåŠ¨æ¨¡å¼",
  warningRule3After: "å¼€å¯ä½™é¢é¢„è­¦",
  warningThresholdLabel: "é¢„è­¦é˜ˆå€¼ï¼š",
  warningAuto: "è‡ªåŠ¨",
  warningCustom: "è‡ªå®šä¹‰",
  warningOff: "å…³é—­é¢„è­¦",
  warningYuan: "å…ƒ",
  warningCancel: "å– æ¶ˆ",
  warningOk: "ç¡® å®š",
  payAmount: "æ”¯ä»˜é‡‘é¢",
  payMethod: "æ”¯ä»˜æ–¹å¼",
  otherAmount: "å…¶å®ƒé‡‘é¢",
  alipay: "æ”¯ä»˜å®",
  otherPay: "å…¶ä»–æ”¯ä»˜æ–¹å¼",
  wechatPay: "å¾®ä¿¡æ”¯ä»˜",
  wechatShort: "å¾®ä¿¡",
  captcha: "ç‚¹å‡»å®ŒæˆéªŒè¯",
  captchaSuccess: "éªŒè¯æˆåŠŸ",
  confirmPay: "ç¡®è®¤æ”¯ä»˜",
  paying: "è·³è½¬æ”¯ä»˜ä¸­â€¦",
  payDisabled:
    "åœ¨çº¿å……å€¼æš‚æœªå¼€é€šã€‚è¯·ç®¡ç†å‘˜åœ¨ Backend ç¡®è®¤æ”¯ä»˜åˆè§„å¹¶é…ç½®æ˜“æ”¯ä»˜ï¼ˆPayAddress / EpayId / EpayKey / PayMethodsï¼‰ã€‚",
  payError: "æ‹‰èµ·æ”¯ä»˜å¤±è´¥ï¼Œè¯·ç¨åŽé‡è¯•",
  agreePrefix: "æˆ‘å·²çŸ¥æ‚‰å……å€¼èµ„é‡‘ä¸æ”¯æŒç›´æŽ¥å¼€å…·å‘ç¥¨ï¼Œç¡®è®¤æ”¯ä»˜å³ä»£è¡¨åŒæ„æœ¬å¹³å°",
  agreeLink: "ã€Œç”¨æˆ·åè®®ã€",
  agreeHref: APP_ROUTES.userAgreement,
  recordsTitle: "å……å€¼é€€æ¬¾è®°å½•",
  statusPending: "å¾…æ”¯ä»˜",
  statusSuccess: "å·²å®Œæˆ",
  statusOther: "å·²å…³é—­",
  empty: "æš‚æ— æ•°æ®",
  segmentAll: "å…¨éƒ¨",
  segmentAvailable: "å¯ç”¨",
  redeemCenter: "å…‘æ¢ä¸­å¿ƒ",
  redeemInputLabel: "å…‘æ¢ç ",
  redeemPlaceholder: "è¯·è¾“å…¥ç®¡ç†å‘˜å‘æ”¾çš„å…‘æ¢ç ",
  redeemSubmit: "å…‘æ¢",
  redeemSubmitting: "å…‘æ¢ä¸­â€¦",
  redeemCancel: "å–æ¶ˆ",
  redeemSuccess: (n) => `å…‘æ¢æˆåŠŸï¼Œé¢åº¦ +${n}`,
  redeemFailed: "å…‘æ¢å¤±è´¥ï¼Œè¯·æ£€æŸ¥å…‘æ¢ç æ˜¯å¦æœ‰æ•ˆ",
  quotaLabel: "é¢åº¦",
  autoTitle: "å¼€é€šæ”¯ä»˜å®è‡ªåŠ¨å……å€¼",
  autoAlerts: [
    "è¯¥åŠŸèƒ½ç”±æ”¯ä»˜å®æä¾›ï¼Œç­¾çº¦åŽæŽˆæƒå¹³å°åœ¨ç”¨æˆ·ä½™é¢ä½ŽäºŽè®¾å®šé˜ˆå€¼æ—¶è‡ªåŠ¨å……å€¼ï¼Œå¯éšæ—¶å–æ¶ˆ",
    "ç­¾çº¦åŽå¹³å°æ¯ 10 åˆ†é’Ÿæ£€æµ‹ä¸€æ¬¡ä½™é¢ï¼Œé»˜è®¤ä¸åœ¨å¤œé—´ï¼ˆ22:00 ~ æ¬¡æ—¥ 08:00ï¼‰æ‰§è¡Œï¼ˆå¼€é€šåŽå¯è°ƒæ•´ï¼‰",
    "è‡ªåŠ¨å……å€¼æ‰§è¡Œå‰ 10 åˆ†é’Ÿï¼Œç³»ç»Ÿå°†å‘æ‚¨å‘é€çŸ­ä¿¡é€šçŸ¥",
  ],
  thresholdLabel: "è®¾å®šé˜ˆå€¼",
  rechargeAmountLabel: "å……å€¼é‡‘é¢",
  otherAmountShort: "å…¶ä»–é‡‘é¢",
  thresholdHint: "å½“ä½™é¢ä½ŽäºŽé˜ˆå€¼æ—¶è‡ªåŠ¨è§¦å‘å……å€¼ï¼ŒèŒƒå›´ Â¥ 5 ~ Â¥ 1000",
  amountHint: "å¿…é¡»å¤§äºŽè®¾å®šé˜ˆå€¼ï¼Œä¸Šé™ Â¥ 2000ï¼›æ¯æ—¥ç´¯è®¡ Â¥ 6,000ï¼Œæ¯æœˆç´¯è®¡ Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `ä½™é¢ < Â¥ ${threshold} æ—¶ï¼Œè‡ªåŠ¨å……å€¼ Â¥ ${amount}`,
  signNow: "ç«‹å³ç­¾çº¦",
};

const en: WalletUiCopy = {
  pageTitle: "Wallet",
  recordHeaders: ["ID", "Time", "Channel", "Status", "Amount", "Actions"],
  balanceLabel: "Balance",
  overdraftSuffix: (n) => `(Remaining overdraft quota Â¥ ${n})`,
  couponLabel: "Vouchers",
  couponSuffix: "available",
  packageLabel: "Resource packs",
  packageSuffix: "active",
  online: "Online recharge",
  auto: "Auto recharge",
  autoOff: "Not enabled",
  corporate: "Bank transfer",
  warningOn: "Balance alert enabled (Settings)",
  warningOffChip: "Balance alert disabled (Settings)",
  warningModalTitle: "Balance alert settings",
  warningRule1: "Balance alerts support Auto, Custom, and Off:",
  warningRule1a:
    "In Auto mode, an alert is sent when remaining available quota (balance plus overdraft) falls below your average daily balance consumption from API calls over the last 7 days",
  warningRule1b:
    "In Custom mode, an alert is sent when remaining available quota (balance plus overdraft) falls below your threshold",
  warningRule2:
    "Balance alerts are sent daily at 10:00 AM Beijing time via SMS and email",
  warningRule3Before: "After your first online recharge, balance alerts are enabled in ",
  warningRule3Bold: "Auto mode",
  warningRule3After: "",
  warningThresholdLabel: "Alert threshold:",
  warningAuto: "Auto",
  warningCustom: "Custom",
  warningOff: "Turn off alerts",
  warningYuan: "CNY",
  warningCancel: "Cancel",
  warningOk: "Confirm",
  payAmount: "Payment amount",
  payMethod: "Payment method",
  otherAmount: "Other amount",
  alipay: "Alipay",
  otherPay: "Other payment methods",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Click to verify",
  captchaSuccess: "Verified",
  confirmPay: "Confirm payment",
  paying: "Redirecting to paymentâ€¦",
  payDisabled:
    "Online recharge is not available yet. Ask an admin to confirm payment compliance in Backend and configure Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Failed to start payment. Please try again later.",
  agreePrefix:
    "I understand that recharged funds cannot be invoiced directly. By confirming payment, I agree to the platform's ",
  agreeLink: "User Agreement",
  agreeHref: APP_ROUTES.userAgreement,
  recordsTitle: "Recharge & refund records",
  statusPending: "Pending payment",
  statusSuccess: "Completed",
  statusOther: "Closed",
  empty: "No data",
  segmentAll: "All",
  segmentAvailable: "Available",
  redeemCenter: "Redemption center",
  redeemInputLabel: "Redemption code",
  redeemPlaceholder: "Enter the code issued by an administrator",
  redeemSubmit: "Redeem",
  redeemSubmitting: "Redeemingâ€¦",
  redeemCancel: "Cancel",
  redeemSuccess: (n) => `Redeemed successfully. Quota +${n}`,
  redeemFailed: "Redemption failed. Check whether the code is valid.",
  quotaLabel: "Quota",
  autoTitle: "Enable Alipay auto recharge",
  autoAlerts: [
    "Provided by Alipay. After signing, you authorize the platform to recharge automatically when your balance falls below the threshold. You can cancel anytime.",
    "After signing, the platform checks your balance every 10 minutes. By default, recharges do not run overnight (22:00â€“08:00). You can adjust this after enabling.",
    "Ten minutes before an auto recharge, the system sends you an SMS notification.",
  ],
  thresholdLabel: "Threshold",
  rechargeAmountLabel: "Recharge amount",
  otherAmountShort: "Other amount",
  thresholdHint:
    "Auto recharge triggers when balance falls below the threshold. Range Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Must exceed the threshold, up to Â¥ 2000; daily cap Â¥ 6,000, monthly cap Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `When balance < Â¥ ${threshold}, auto recharge Â¥ ${amount}`,
  signNow: "Sign now",
};

const zhTW: WalletUiCopy = {
  ...zhCN,
  pageTitle: "éŒ¢åŒ…",
  recordHeaders: ["ç·¨è™Ÿ", "æ™‚é–“", "å„²å€¼æ¸ é“", "ç‹€æ…‹", "é‡‘é¡", "æ“ä½œ"],
  balanceLabel: "é¤˜é¡",
  overdraftSuffix: (n) => `ï¼ˆå‰©é¤˜å¯é€æ”¯é¡åº¦ Â¥ ${n}ï¼‰`,
  couponLabel: "ä»£é‡‘åˆ¸",
  couponSuffix: "å¼µå¯ç”¨",
  packageLabel: "è³‡æºåŒ…",
  packageSuffix: "å€‹ç”Ÿæ•ˆä¸­",
  online: "ç·šä¸Šå„²å€¼",
  auto: "è‡ªå‹•å„²å€¼",
  autoOff: "æœªé–‹å•Ÿ",
  corporate: "å°å…¬è½‰å¸³åŒ¯æ¬¾",
  warningOn: "é¤˜é¡é è­¦å·²é–‹å•Ÿ (åŽ»è¨­å®š)",
  warningOffChip: "é¤˜é¡é è­¦å·²é—œé–‰ (åŽ»è¨­å®š)",
  warningModalTitle: "é¤˜é¡é è­¦è¨­å®š",
  warningRule1: "é¤˜é¡é è­¦åŒ…æ‹¬è‡ªå‹•ã€è‡ªè¨‚ã€é—œé–‰ä¸‰ç¨®æ¨¡å¼ï¼š",
  warningRule1a:
    "è‹¥è¨­å®šç‚ºè‡ªå‹•ï¼Œç•¶å¸³æˆ¶å‰©é¤˜å¯ç”¨é¡åº¦ï¼ˆåŒ…æ‹¬å„²å€¼é¤˜é¡å’Œé€æ”¯é¡åº¦ï¼‰ä½Žæ–¼è¿‘ 7 æ—¥ API å‘¼å«ç”¢ç”Ÿçš„å„²å€¼é¤˜é¡å¹³å‡æ—¥æ¶ˆè²»æ™‚è‡ªå‹•é è­¦",
  warningRule1b:
    "è‹¥è¨­å®šç‚ºè‡ªè¨‚ï¼Œç•¶å¸³æˆ¶å‰©é¤˜å¯ç”¨é¡åº¦ï¼ˆåŒ…æ‹¬å„²å€¼é¤˜é¡å’Œé€æ”¯é¡åº¦ï¼‰ä½Žæ–¼è¨­å®šé–¾å€¼æ™‚è‡ªå‹•é è­¦",
  warningRule2: "é¤˜é¡é è­¦å°‡åœ¨åŒ—äº¬æ™‚é–“æ¯å¤©ä¸Šåˆ 10 é»žç™¼é€é è­¦ç°¡è¨ŠåŠéƒµä»¶é€šçŸ¥",
  warningRule3Before: "é¦–æ¬¡å®Œæˆç·šä¸Šå„²å€¼æ™‚ï¼Œç³»çµ±æŒ‰",
  warningRule3Bold: "è‡ªå‹•æ¨¡å¼",
  warningRule3After: "é–‹å•Ÿé¤˜é¡é è­¦",
  warningThresholdLabel: "é è­¦é–¾å€¼ï¼š",
  warningAuto: "è‡ªå‹•",
  warningCustom: "è‡ªè¨‚",
  warningOff: "é—œé–‰é è­¦",
  warningYuan: "å…ƒ",
  warningCancel: "å– æ¶ˆ",
  warningOk: "ç¢º å®š",
  payAmount: "æ”¯ä»˜é‡‘é¡",
  payMethod: "æ”¯ä»˜æ–¹å¼",
  otherAmount: "å…¶å®ƒé‡‘é¡",
  alipay: "æ”¯ä»˜å¯¶",
  otherPay: "å…¶ä»–æ”¯ä»˜æ–¹å¼",
  wechatPay: "å¾®ä¿¡æ”¯ä»˜",
  wechatShort: "å¾®ä¿¡",
  captcha: "é»žæ“Šå®Œæˆé©—è­‰",
  captchaSuccess: "é©—è­‰æˆåŠŸ",
  confirmPay: "ç¢ºèªæ”¯ä»˜",
  paying: "è·³è½‰æ”¯ä»˜ä¸­â€¦",
  payDisabled:
    "ç·šä¸Šå„²å€¼æš«æœªé–‹é€šã€‚è«‹ç®¡ç†å“¡åœ¨ Backend ç¢ºèªæ”¯ä»˜åˆè¦ä¸¦é…ç½®æ˜“æ”¯ä»˜ï¼ˆPayAddress / EpayId / EpayKey / PayMethodsï¼‰ã€‚",
  payError: "æ‹‰èµ·æ”¯ä»˜å¤±æ•—ï¼Œè«‹ç¨å¾Œé‡è©¦",
  agreePrefix: "æˆ‘å·²çŸ¥æ‚‰å„²å€¼è³‡é‡‘ä¸æ”¯æŒç›´æŽ¥é–‹å…·ç™¼ç¥¨ï¼Œç¢ºèªæ”¯ä»˜å³ä»£è¡¨åŒæ„æœ¬å¹³å°",
  agreeLink: "ã€Œç”¨æˆ¶å”è­°ã€",
  recordsTitle: "å„²å€¼é€€æ¬¾è¨˜éŒ„",
  statusPending: "å¾…æ”¯ä»˜",
  statusSuccess: "å·²å®Œæˆ",
  statusOther: "å·²é—œé–‰",
  empty: "æš«ç„¡è³‡æ–™",
  segmentAll: "å…¨éƒ¨",
  segmentAvailable: "å¯ç”¨",
  redeemCenter: "å…Œæ›ä¸­å¿ƒ",
  redeemInputLabel: "å…Œæ›ç¢¼",
  redeemPlaceholder: "è«‹è¼¸å…¥ç®¡ç†å“¡ç™¼æ”¾çš„å…Œæ›ç¢¼",
  redeemSubmit: "å…Œæ›",
  redeemSubmitting: "å…Œæ›ä¸­â€¦",
  redeemCancel: "å–æ¶ˆ",
  redeemSuccess: (n) => `å…Œæ›æˆåŠŸï¼Œé¡åº¦ +${n}`,
  redeemFailed: "å…Œæ›å¤±æ•—ï¼Œè«‹æª¢æŸ¥å…Œæ›ç¢¼æ˜¯å¦æœ‰æ•ˆ",
  quotaLabel: "é¡åº¦",
  autoTitle: "é–‹é€šæ”¯ä»˜å¯¶è‡ªå‹•å„²å€¼",
  autoAlerts: [
    "è©²åŠŸèƒ½ç”±æ”¯ä»˜å¯¶æä¾›ï¼Œç°½ç´„å¾ŒæŽˆæ¬Šå¹³å°åœ¨ç”¨æˆ¶é¤˜é¡ä½Žæ–¼è¨­å®šé–¾å€¼æ™‚è‡ªå‹•å„²å€¼ï¼Œå¯éš¨æ™‚å–æ¶ˆ",
    "ç°½ç´„å¾Œå¹³å°æ¯ 10 åˆ†é˜æª¢æ¸¬ä¸€æ¬¡é¤˜é¡ï¼Œé è¨­ä¸åœ¨å¤œé–“ï¼ˆ22:00 ~ æ¬¡æ—¥ 08:00ï¼‰åŸ·è¡Œï¼ˆé–‹é€šå¾Œå¯èª¿æ•´ï¼‰",
    "è‡ªå‹•å„²å€¼åŸ·è¡Œå‰ 10 åˆ†é˜ï¼Œç³»çµ±å°‡å‘æ‚¨ç™¼é€ç°¡è¨Šé€šçŸ¥",
  ],
  thresholdLabel: "è¨­å®šé–¾å€¼",
  rechargeAmountLabel: "å„²å€¼é‡‘é¡",
  otherAmountShort: "å…¶ä»–é‡‘é¡",
  thresholdHint: "ç•¶é¤˜é¡ä½Žæ–¼é–¾å€¼æ™‚è‡ªå‹•è§¸ç™¼å„²å€¼ï¼Œç¯„åœ Â¥ 5 ~ Â¥ 1000",
  amountHint: "å¿…é ˆå¤§æ–¼è¨­å®šé–¾å€¼ï¼Œä¸Šé™ Â¥ 2000ï¼›æ¯æ—¥ç´¯è¨ˆ Â¥ 6,000ï¼Œæ¯æœˆç´¯è¨ˆ Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `é¤˜é¡ < Â¥ ${threshold} æ™‚ï¼Œè‡ªå‹•å„²å€¼ Â¥ ${amount}`,
  signNow: "ç«‹å³ç°½ç´„",
};

function fromEn(
  partial: Partial<
    Omit<WalletUiCopy, "overdraftSuffix" | "redeemSuccess" | "autoPreview">
  > & {
    overdraftSuffix?: WalletUiCopy["overdraftSuffix"];
    redeemSuccess?: WalletUiCopy["redeemSuccess"];
    autoPreview?: WalletUiCopy["autoPreview"];
  },
): WalletUiCopy {
  return {
    ...en,
    ...partial,
    recordHeaders: partial.recordHeaders ?? en.recordHeaders,
    autoAlerts: partial.autoAlerts ?? en.autoAlerts,
    overdraftSuffix: partial.overdraftSuffix ?? en.overdraftSuffix,
    redeemSuccess: partial.redeemSuccess ?? en.redeemSuccess,
    autoPreview: partial.autoPreview ?? en.autoPreview,
  };
}

const ja = fromEn({
  pageTitle: "ã‚¦ã‚©ãƒ¬ãƒƒãƒˆ",
  recordHeaders: ["ID", "æ—¥æ™‚", "ãƒãƒ£ãƒãƒ«", "çŠ¶æ…‹", "é‡‘é¡", "æ“ä½œ"],
  balanceLabel: "æ®‹é«˜",
  overdraftSuffix: (n) => `ï¼ˆæ®‹ã‚Šã®é€æ”¯æž  Â¥ ${n}ï¼‰`,
  couponLabel: "ã‚¯ãƒ¼ãƒãƒ³",
  couponSuffix: "æžšåˆ©ç”¨å¯èƒ½",
  packageLabel: "ãƒªã‚½ãƒ¼ã‚¹ãƒ‘ãƒƒã‚¯",
  packageSuffix: "ä»¶æœ‰åŠ¹",
  online: "ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ãƒãƒ£ãƒ¼ã‚¸",
  auto: "è‡ªå‹•ãƒãƒ£ãƒ¼ã‚¸",
  autoOff: "æœªè¨­å®š",
  corporate: "æ³•äººæŒ¯è¾¼",
  warningOn: "æ®‹é«˜ã‚¢ãƒ©ãƒ¼ãƒˆæœ‰åŠ¹ï¼ˆè¨­å®šã¸ï¼‰",
  warningOffChip: "æ®‹é«˜ã‚¢ãƒ©ãƒ¼ãƒˆç„¡åŠ¹ï¼ˆè¨­å®šã¸ï¼‰",
  warningModalTitle: "æ®‹é«˜ã‚¢ãƒ©ãƒ¼ãƒˆè¨­å®š",
  warningRule1: "æ®‹é«˜ã‚¢ãƒ©ãƒ¼ãƒˆã«ã¯è‡ªå‹•ãƒ»ã‚«ã‚¹ã‚¿ãƒ ãƒ»ã‚ªãƒ•ã®3ãƒ¢ãƒ¼ãƒ‰ãŒã‚ã‚Šã¾ã™ï¼š",
  warningRule1a:
    "è‡ªå‹•ã®å ´åˆã€æ®‹ã‚Šåˆ©ç”¨å¯èƒ½æž ï¼ˆãƒãƒ£ãƒ¼ã‚¸æ®‹é«˜ã¨é€æ”¯æž ã‚’å«ã‚€ï¼‰ãŒéŽåŽ»7æ—¥é–“ã®APIå‘¼ã³å‡ºã—ã«ã‚ˆã‚‹ãƒãƒ£ãƒ¼ã‚¸æ®‹é«˜ã®å¹³å‡æ—¥æ¬¡æ¶ˆè²»ã‚’ä¸‹å›žã‚‹ã¨è‡ªå‹•ã§ã‚¢ãƒ©ãƒ¼ãƒˆ",
  warningRule1b:
    "ã‚«ã‚¹ã‚¿ãƒ ã®å ´åˆã€æ®‹ã‚Šåˆ©ç”¨å¯èƒ½æž ï¼ˆãƒãƒ£ãƒ¼ã‚¸æ®‹é«˜ã¨é€æ”¯æž ã‚’å«ã‚€ï¼‰ãŒè¨­å®šã—ãŸé–¾å€¤ã‚’ä¸‹å›žã‚‹ã¨è‡ªå‹•ã§ã‚¢ãƒ©ãƒ¼ãƒˆ",
  warningRule2:
    "æ®‹é«˜ã‚¢ãƒ©ãƒ¼ãƒˆã¯åŒ—äº¬æ™‚é–“ã®æ¯Žæ—¥åˆå‰10æ™‚ã«SMSã¨ãƒ¡ãƒ¼ãƒ«ã§é€ä¿¡ã•ã‚Œã¾ã™",
  warningRule3Before: "åˆå›žã®ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ãƒãƒ£ãƒ¼ã‚¸å®Œäº†å¾Œã€ã‚·ã‚¹ãƒ†ãƒ ã¯",
  warningRule3Bold: "è‡ªå‹•ãƒ¢ãƒ¼ãƒ‰",
  warningRule3After: "ã§æ®‹é«˜ã‚¢ãƒ©ãƒ¼ãƒˆã‚’æœ‰åŠ¹ã«ã—ã¾ã™",
  warningThresholdLabel: "ã‚¢ãƒ©ãƒ¼ãƒˆé–¾å€¤ï¼š",
  warningAuto: "è‡ªå‹•",
  warningCustom: "ã‚«ã‚¹ã‚¿ãƒ ",
  warningOff: "ã‚¢ãƒ©ãƒ¼ãƒˆã‚’ã‚ªãƒ•",
  warningYuan: "å…ƒ",
  warningCancel: "ã‚­ãƒ£ãƒ³ã‚»ãƒ«",
  warningOk: "ç¢ºå®š",
  payAmount: "æ”¯æ‰•ã„é‡‘é¡",
  payMethod: "æ”¯æ‰•ã„æ–¹æ³•",
  otherAmount: "ãã®ä»–ã®é‡‘é¡",
  alipay: "Alipay",
  otherPay: "ãã®ä»–ã®æ”¯æ‰•ã„æ–¹æ³•",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "ã‚¯ãƒªãƒƒã‚¯ã—ã¦èªè¨¼",
  captchaSuccess: "èªè¨¼æˆåŠŸ",
  confirmPay: "æ”¯æ‰•ã„ã‚’ç¢ºèª",
  paying: "æ”¯æ‰•ã„ãƒšãƒ¼ã‚¸ã¸ç§»å‹•ä¸­â€¦",
  payDisabled:
    "ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ãƒãƒ£ãƒ¼ã‚¸ã¯ã¾ã åˆ©ç”¨ã§ãã¾ã›ã‚“ã€‚ç®¡ç†è€…ã«Backendã§æ±ºæ¸ˆã‚³ãƒ³ãƒ—ãƒ©ã‚¤ã‚¢ãƒ³ã‚¹ã®ç¢ºèªã¨æ˜“æ”¯ä»˜ï¼ˆPayAddress / EpayId / EpayKey / PayMethodsï¼‰ã®è¨­å®šã‚’ä¾é ¼ã—ã¦ãã ã•ã„ã€‚",
  payError: "æ”¯æ‰•ã„ã®é–‹å§‹ã«å¤±æ•—ã—ã¾ã—ãŸã€‚å¾Œã§ã‚‚ã†ä¸€åº¦ãŠè©¦ã—ãã ã•ã„ã€‚",
  agreePrefix:
    "ãƒãƒ£ãƒ¼ã‚¸è³‡é‡‘ã¯ç›´æŽ¥è«‹æ±‚æ›¸ã‚’ç™ºè¡Œã§ããªã„ã“ã¨ã‚’ç†è§£ã—ã¾ã—ãŸã€‚æ”¯æ‰•ã„ã‚’ç¢ºèªã™ã‚‹ã“ã¨ã§ã€æœ¬ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ ã®",
  agreeLink: "ã€Œåˆ©ç”¨è¦ç´„ã€",
  recordsTitle: "ãƒãƒ£ãƒ¼ã‚¸ãƒ»è¿”é‡‘è¨˜éŒ²",
  statusPending: "æ”¯æ‰•ã„å¾…ã¡",
  statusSuccess: "å®Œäº†",
  statusOther: "ã‚¯ãƒ­ãƒ¼ã‚º",
  empty: "ãƒ‡ãƒ¼ã‚¿ãªã—",
  segmentAll: "ã™ã¹ã¦",
  segmentAvailable: "åˆ©ç”¨å¯èƒ½",
  redeemCenter: "å¼•ãæ›ãˆã‚»ãƒ³ã‚¿ãƒ¼",
  redeemInputLabel: "å¼•ãæ›ãˆã‚³ãƒ¼ãƒ‰",
  redeemPlaceholder: "ç®¡ç†è€…ã‹ã‚‰ç™ºè¡Œã•ã‚ŒãŸã‚³ãƒ¼ãƒ‰ã‚’å…¥åŠ›",
  redeemSubmit: "å¼•ãæ›ãˆ",
  redeemSubmitting: "å¼•ãæ›ãˆä¸­â€¦",
  redeemCancel: "ã‚­ãƒ£ãƒ³ã‚»ãƒ«",
  redeemSuccess: (n) => `å¼•ãæ›ãˆæˆåŠŸã€‚åˆ©ç”¨æž  +${n}`,
  redeemFailed: "å¼•ãæ›ãˆã«å¤±æ•—ã—ã¾ã—ãŸã€‚ã‚³ãƒ¼ãƒ‰ãŒæœ‰åŠ¹ã‹ç¢ºèªã—ã¦ãã ã•ã„ã€‚",
  quotaLabel: "åˆ©ç”¨æž ",
  autoTitle: "Alipay è‡ªå‹•ãƒãƒ£ãƒ¼ã‚¸ã‚’æœ‰åŠ¹åŒ–",
  autoAlerts: [
    "ã“ã®æ©Ÿèƒ½ã¯AlipayãŒæä¾›ã—ã¾ã™ã€‚å¥‘ç´„å¾Œã€æ®‹é«˜ãŒè¨­å®šã—ãŸé–¾å€¤ã‚’ä¸‹å›žã‚‹ã¨è‡ªå‹•ãƒãƒ£ãƒ¼ã‚¸ã‚’è¨±å¯ã—ã¾ã™ã€‚ã„ã¤ã§ã‚‚è§£ç´„ã§ãã¾ã™ã€‚",
    "å¥‘ç´„å¾Œã€ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ ã¯10åˆ†ã”ã¨ã«æ®‹é«˜ã‚’ç¢ºèªã—ã¾ã™ã€‚ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã§ã¯å¤œé–“ï¼ˆ22:00ï½žç¿Œ08:00ï¼‰ã¯å®Ÿè¡Œã•ã‚Œã¾ã›ã‚“ï¼ˆæœ‰åŠ¹åŒ–å¾Œã«èª¿æ•´å¯èƒ½ï¼‰ã€‚",
    "è‡ªå‹•ãƒãƒ£ãƒ¼ã‚¸ã®10åˆ†å‰ã«ã€ã‚·ã‚¹ãƒ†ãƒ ã‹ã‚‰SMSé€šçŸ¥ãŒé€ä¿¡ã•ã‚Œã¾ã™ã€‚",
  ],
  thresholdLabel: "é–¾å€¤è¨­å®š",
  rechargeAmountLabel: "ãƒãƒ£ãƒ¼ã‚¸é‡‘é¡",
  otherAmountShort: "ãã®ä»–ã®é‡‘é¡",
  thresholdHint: "æ®‹é«˜ãŒé–¾å€¤ã‚’ä¸‹å›žã‚‹ã¨è‡ªå‹•ãƒãƒ£ãƒ¼ã‚¸ãŒå®Ÿè¡Œã•ã‚Œã¾ã™ã€‚ç¯„å›² Â¥ 5 ~ Â¥ 1000",
  amountHint: "é–¾å€¤ã‚ˆã‚Šå¤§ããã€ä¸Šé™ Â¥ 2000ã€‚æ—¥æ¬¡ç´¯è¨ˆ Â¥ 6,000ã€æœˆæ¬¡ç´¯è¨ˆ Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `æ®‹é«˜ < Â¥ ${threshold} ã®ã¨ãã€è‡ªå‹•ãƒãƒ£ãƒ¼ã‚¸ Â¥ ${amount}`,
  signNow: "ä»Šã™ãå¥‘ç´„",
});

const fr = fromEn({
  pageTitle: "Recharger",
  recordHeaders: ["ID", "Date", "Canal", "Statut", "Montant", "Actions"],
  balanceLabel: "Solde",
  overdraftSuffix: (n) => `(Quota de dÃ©couvert restant Â¥ ${n})`,
  couponLabel: "Bons",
  couponSuffix: "disponibles",
  packageLabel: "Packs de ressources",
  packageSuffix: "actifs",
  online: "Recharge en ligne",
  auto: "Recharge automatique",
  autoOff: "Non activÃ©e",
  corporate: "Virement bancaire",
  warningOn: "Alerte solde activÃ©e (ParamÃ¨tres)",
  warningOffChip: "Alerte solde dÃ©sactivÃ©e (ParamÃ¨tres)",
  warningModalTitle: "ParamÃ¨tres d'alerte solde",
  warningRule1: "Les alertes solde proposent Auto, PersonnalisÃ© et DÃ©sactivÃ© :",
  warningRule1a:
    "En mode Auto, une alerte est envoyÃ©e lorsque le quota disponible restant (solde plus dÃ©couvert) tombe sous la consommation quotidienne moyenne du solde de recharge sur les 7 derniers jours d'appels API",
  warningRule1b:
    "En mode PersonnalisÃ©, une alerte est envoyÃ©e lorsque le quota disponible restant (solde plus dÃ©couvert) tombe sous votre seuil",
  warningRule2:
    "Les alertes solde sont envoyÃ©es chaque jour Ã  10 h (heure de PÃ©kin) par SMS et e-mail",
  warningRule3Before: "AprÃ¨s votre premiÃ¨re recharge en ligne, les alertes solde sont activÃ©es en ",
  warningRule3Bold: "mode Auto",
  warningRule3After: "",
  warningThresholdLabel: "Seuil d'alerte :",
  warningAuto: "Auto",
  warningCustom: "PersonnalisÃ©",
  warningOff: "DÃ©sactiver les alertes",
  warningYuan: "CNY",
  warningCancel: "Annuler",
  warningOk: "Confirmer",
  payAmount: "Montant du paiement",
  payMethod: "Mode de paiement",
  otherAmount: "Autre montant",
  alipay: "Alipay",
  otherPay: "Autres modes de paiement",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Cliquer pour vÃ©rifier",
  captchaSuccess: "VÃ©rifiÃ©",
  confirmPay: "Confirmer le paiement",
  paying: "Redirection vers le paiementâ€¦",
  payDisabled:
    "La recharge en ligne n'est pas encore disponible. Demandez Ã  un administrateur de confirmer la conformitÃ© des paiements dans Backend et de configurer Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Ã‰chec du dÃ©marrage du paiement. RÃ©essayez plus tard.",
  agreePrefix:
    "Je comprends que les fonds rechargÃ©s ne peuvent pas Ãªtre facturÃ©s directement. En confirmant le paiement, j'accepte les ",
  agreeLink: "Conditions d'utilisation",
  recordsTitle: "Historique recharge et remboursement",
  statusPending: "Paiement en attente",
  statusSuccess: "TerminÃ©",
  statusOther: "FermÃ©",
  empty: "Aucune donnÃ©e",
  segmentAll: "Tout",
  segmentAvailable: "Disponible",
  redeemCenter: "Centre d'Ã©change",
  redeemInputLabel: "Code d'Ã©change",
  redeemPlaceholder: "Saisissez le code Ã©mis par un administrateur",
  redeemSubmit: "Ã‰changer",
  redeemSubmitting: "Ã‰change en coursâ€¦",
  redeemCancel: "Annuler",
  redeemSuccess: (n) => `Ã‰change rÃ©ussi. Quota +${n}`,
  redeemFailed: "Ã‰change Ã©chouÃ©. VÃ©rifiez que le code est valide.",
  quotaLabel: "Quota",
  autoTitle: "Activer la recharge auto Alipay",
  autoAlerts: [
    "Fourni par Alipay. AprÃ¨s signature, vous autorisez la plateforme Ã  recharger automatiquement lorsque votre solde descend sous le seuil. Annulable Ã  tout moment.",
    "AprÃ¨s signature, la plateforme vÃ©rifie le solde toutes les 10 minutes. Par dÃ©faut, pas de recharge la nuit (22:00â€“08:00). Ajustable aprÃ¨s activation.",
    "Dix minutes avant une recharge auto, le systÃ¨me vous envoie un SMS.",
  ],
  thresholdLabel: "Seuil",
  rechargeAmountLabel: "Montant de recharge",
  otherAmountShort: "Autre montant",
  thresholdHint:
    "La recharge auto se dÃ©clenche lorsque le solde descend sous le seuil. Plage Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Doit dÃ©passer le seuil, max Â¥ 2000 ; plafond quotidien Â¥ 6 000, mensuel Â¥ 100 000",
  autoPreview: (threshold, amount) =>
    `Quand solde < Â¥ ${threshold}, recharge auto Â¥ ${amount}`,
  signNow: "Signer maintenant",
});

const ru = fromEn({
  pageTitle: "ÐŸÐ¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ",
  recordHeaders: ["ID", "Ð’Ñ€ÐµÐ¼Ñ", "ÐšÐ°Ð½Ð°Ð»", "Ð¡Ñ‚Ð°Ñ‚ÑƒÑ", "Ð¡ÑƒÐ¼Ð¼Ð°", "Ð”ÐµÐ¹ÑÑ‚Ð²Ð¸Ñ"],
  balanceLabel: "Ð‘Ð°Ð»Ð°Ð½Ñ",
  overdraftSuffix: (n) => `(ÐžÑÑ‚Ð°Ð²ÑˆÐ°ÑÑÑ ÐºÐ²Ð¾Ñ‚Ð° Ð¾Ð²ÐµÑ€Ð´Ñ€Ð°Ñ„Ñ‚Ð° Â¥ ${n})`,
  couponLabel: "ÐšÑƒÐ¿Ð¾Ð½Ñ‹",
  couponSuffix: "Ð´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¾",
  packageLabel: "ÐŸÐ°ÐºÐµÑ‚Ñ‹ Ñ€ÐµÑÑƒÑ€ÑÐ¾Ð²",
  packageSuffix: "Ð°ÐºÑ‚Ð¸Ð²Ð½Ð¾",
  online: "ÐžÐ½Ð»Ð°Ð¹Ð½-Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ",
  auto: "ÐÐ²Ñ‚Ð¾Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ",
  autoOff: "ÐÐµ Ð²ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¾",
  corporate: "Ð‘Ð°Ð½ÐºÐ¾Ð²ÑÐºÐ¸Ð¹ Ð¿ÐµÑ€ÐµÐ²Ð¾Ð´",
  warningOn: "ÐžÐ¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ðµ Ð¾ Ð±Ð°Ð»Ð°Ð½ÑÐµ Ð²ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¾ (ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸)",
  warningOffChip: "ÐžÐ¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ðµ Ð¾ Ð±Ð°Ð»Ð°Ð½ÑÐµ Ð²Ñ‹ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¾ (ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸)",
  warningModalTitle: "ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸ Ð¾Ð¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ Ð¾ Ð±Ð°Ð»Ð°Ð½ÑÐµ",
  warningRule1: "ÐžÐ¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ Ð¾ Ð±Ð°Ð»Ð°Ð½ÑÐµ: ÐÐ²Ñ‚Ð¾, ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒÑÐºÐ¸Ð¹ Ð¸ Ð’Ñ‹ÐºÐ».:",
  warningRule1a:
    "Ð’ Ñ€ÐµÐ¶Ð¸Ð¼Ðµ ÐÐ²Ñ‚Ð¾ Ð¾Ð¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ðµ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð»ÑÐµÑ‚ÑÑ, ÐºÐ¾Ð³Ð´Ð° Ð¾ÑÑ‚Ð°Ð²ÑˆÐ°ÑÑÑ Ð´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð°Ñ ÐºÐ²Ð¾Ñ‚Ð° (Ð±Ð°Ð»Ð°Ð½Ñ Ð¿Ð»ÑŽÑ Ð¾Ð²ÐµÑ€Ð´Ñ€Ð°Ñ„Ñ‚) Ð½Ð¸Ð¶Ðµ ÑÑ€ÐµÐ´Ð½ÐµÐ³Ð¾ Ð´Ð½ÐµÐ²Ð½Ð¾Ð³Ð¾ Ñ€Ð°ÑÑ…Ð¾Ð´Ð° Ð±Ð°Ð»Ð°Ð½ÑÐ° Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ Ð·Ð° Ð¿Ð¾ÑÐ»ÐµÐ´Ð½Ð¸Ðµ 7 Ð´Ð½ÐµÐ¹ Ð²Ñ‹Ð·Ð¾Ð²Ð¾Ð² API",
  warningRule1b:
    "Ð’ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒÑÐºÐ¾Ð¼ Ñ€ÐµÐ¶Ð¸Ð¼Ðµ Ð¾Ð¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ðµ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð»ÑÐµÑ‚ÑÑ, ÐºÐ¾Ð³Ð´Ð° Ð¾ÑÑ‚Ð°Ð²ÑˆÐ°ÑÑÑ Ð´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð°Ñ ÐºÐ²Ð¾Ñ‚Ð° (Ð±Ð°Ð»Ð°Ð½Ñ Ð¿Ð»ÑŽÑ Ð¾Ð²ÐµÑ€Ð´Ñ€Ð°Ñ„Ñ‚) Ð½Ð¸Ð¶Ðµ Ð²Ð°ÑˆÐµÐ³Ð¾ Ð¿Ð¾Ñ€Ð¾Ð³Ð°",
  warningRule2:
    "ÐžÐ¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ Ð¾ Ð±Ð°Ð»Ð°Ð½ÑÐµ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð»ÑÑŽÑ‚ÑÑ ÐµÐ¶ÐµÐ´Ð½ÐµÐ²Ð½Ð¾ Ð² 10:00 Ð¿Ð¾ Ð¿ÐµÐºÐ¸Ð½ÑÐºÐ¾Ð¼Ñƒ Ð²Ñ€ÐµÐ¼ÐµÐ½Ð¸ Ð¿Ð¾ SMS Ð¸ e-mail",
  warningRule3Before: "ÐŸÐ¾ÑÐ»Ðµ Ð¿ÐµÑ€Ð²Ð¾Ð³Ð¾ Ð¾Ð½Ð»Ð°Ð¹Ð½-Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ Ð¾Ð¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ Ð¾ Ð±Ð°Ð»Ð°Ð½ÑÐµ Ð²ÐºÐ»ÑŽÑ‡Ð°ÑŽÑ‚ÑÑ Ð² ",
  warningRule3Bold: "Ñ€ÐµÐ¶Ð¸Ð¼Ðµ ÐÐ²Ñ‚Ð¾",
  warningRule3After: "",
  warningThresholdLabel: "ÐŸÐ¾Ñ€Ð¾Ð³ Ð¾Ð¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ:",
  warningAuto: "ÐÐ²Ñ‚Ð¾",
  warningCustom: "ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒÑÐºÐ¸Ð¹",
  warningOff: "ÐžÑ‚ÐºÐ»ÑŽÑ‡Ð¸Ñ‚ÑŒ Ð¾Ð¿Ð¾Ð²ÐµÑ‰ÐµÐ½Ð¸Ñ",
  warningYuan: "CNY",
  warningCancel: "ÐžÑ‚Ð¼ÐµÐ½Ð°",
  warningOk: "ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ",
  payAmount: "Ð¡ÑƒÐ¼Ð¼Ð° Ð¿Ð»Ð°Ñ‚ÐµÐ¶Ð°",
  payMethod: "Ð¡Ð¿Ð¾ÑÐ¾Ð± Ð¾Ð¿Ð»Ð°Ñ‚Ñ‹",
  otherAmount: "Ð”Ñ€ÑƒÐ³Ð°Ñ ÑÑƒÐ¼Ð¼Ð°",
  alipay: "Alipay",
  otherPay: "Ð”Ñ€ÑƒÐ³Ð¸Ðµ ÑÐ¿Ð¾ÑÐ¾Ð±Ñ‹ Ð¾Ð¿Ð»Ð°Ñ‚Ñ‹",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ Ð´Ð»Ñ Ð¿Ñ€Ð¾Ð²ÐµÑ€ÐºÐ¸",
  captchaSuccess: "ÐŸÑ€Ð¾Ð²ÐµÑ€ÐµÐ½Ð¾",
  confirmPay: "ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ Ð¾Ð¿Ð»Ð°Ñ‚Ñƒ",
  paying: "ÐŸÐµÑ€ÐµÑ…Ð¾Ð´ Ðº Ð¾Ð¿Ð»Ð°Ñ‚Ðµâ€¦",
  payDisabled:
    "ÐžÐ½Ð»Ð°Ð¹Ð½-Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ Ð¿Ð¾ÐºÐ° Ð½ÐµÐ´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¾. ÐŸÐ¾Ð¿Ñ€Ð¾ÑÐ¸Ñ‚Ðµ Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€Ð° Ð¿Ð¾Ð´Ñ‚Ð²ÐµÑ€Ð´Ð¸Ñ‚ÑŒ ÑÐ¾Ð¾Ñ‚Ð²ÐµÑ‚ÑÑ‚Ð²Ð¸Ðµ Ð¿Ð»Ð°Ñ‚ÐµÐ¶ÐµÐ¹ Ð² Backend Ð¸ Ð½Ð°ÑÑ‚Ñ€Ð¾Ð¸Ñ‚ÑŒ Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "ÐÐµ ÑƒÐ´Ð°Ð»Ð¾ÑÑŒ Ð½Ð°Ñ‡Ð°Ñ‚ÑŒ Ð¾Ð¿Ð»Ð°Ñ‚Ñƒ. ÐŸÐ¾Ð¿Ñ€Ð¾Ð±ÑƒÐ¹Ñ‚Ðµ Ð¿Ð¾Ð·Ð¶Ðµ.",
  agreePrefix:
    "Ð¯ Ð¿Ð¾Ð½Ð¸Ð¼Ð°ÑŽ, Ñ‡Ñ‚Ð¾ Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð½Ñ‹Ðµ ÑÑ€ÐµÐ´ÑÑ‚Ð²Ð° Ð½ÐµÐ»ÑŒÐ·Ñ Ð½Ð°Ð¿Ñ€ÑÐ¼ÑƒÑŽ Ð²Ñ‹ÑÑ‚Ð°Ð²Ð¸Ñ‚ÑŒ Ð² ÑÑ‡Ñ‘Ñ‚. ÐŸÐ¾Ð´Ñ‚Ð²ÐµÑ€Ð¶Ð´Ð°Ñ Ð¾Ð¿Ð»Ð°Ñ‚Ñƒ, Ñ Ð¿Ñ€Ð¸Ð½Ð¸Ð¼Ð°ÑŽ ",
  agreeLink: "ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒÑÐºÐ¾Ðµ ÑÐ¾Ð³Ð»Ð°ÑˆÐµÐ½Ð¸Ðµ",
  recordsTitle: "Ð˜ÑÑ‚Ð¾Ñ€Ð¸Ñ Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ð¹ Ð¸ Ð²Ð¾Ð·Ð²Ñ€Ð°Ñ‚Ð¾Ð²",
  statusPending: "ÐžÐ¶Ð¸Ð´Ð°ÐµÑ‚ Ð¾Ð¿Ð»Ð°Ñ‚Ñ‹",
  statusSuccess: "Ð—Ð°Ð²ÐµÑ€ÑˆÐµÐ½Ð¾",
  statusOther: "Ð—Ð°ÐºÑ€Ñ‹Ñ‚Ð¾",
  empty: "ÐÐµÑ‚ Ð´Ð°Ð½Ð½Ñ‹Ñ…",
  segmentAll: "Ð’ÑÐµ",
  segmentAvailable: "Ð”Ð¾ÑÑ‚ÑƒÐ¿Ð½Ñ‹Ðµ",
  redeemCenter: "Ð¦ÐµÐ½Ñ‚Ñ€ Ð°ÐºÑ‚Ð¸Ð²Ð°Ñ†Ð¸Ð¸",
  redeemInputLabel: "ÐšÐ¾Ð´ Ð°ÐºÑ‚Ð¸Ð²Ð°Ñ†Ð¸Ð¸",
  redeemPlaceholder: "Ð’Ð²ÐµÐ´Ð¸Ñ‚Ðµ ÐºÐ¾Ð´, Ð²Ñ‹Ð´Ð°Ð½Ð½Ñ‹Ð¹ Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€Ð¾Ð¼",
  redeemSubmit: "ÐÐºÑ‚Ð¸Ð²Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ",
  redeemSubmitting: "ÐÐºÑ‚Ð¸Ð²Ð°Ñ†Ð¸Ñâ€¦",
  redeemCancel: "ÐžÑ‚Ð¼ÐµÐ½Ð°",
  redeemSuccess: (n) => `ÐÐºÑ‚Ð¸Ð²Ð°Ñ†Ð¸Ñ ÑƒÑÐ¿ÐµÑˆÐ½Ð°. ÐšÐ²Ð¾Ñ‚Ð° +${n}`,
  redeemFailed: "ÐÐºÑ‚Ð¸Ð²Ð°Ñ†Ð¸Ñ Ð½Ðµ ÑƒÐ´Ð°Ð»Ð°ÑÑŒ. ÐŸÑ€Ð¾Ð²ÐµÑ€ÑŒÑ‚Ðµ ÐºÐ¾Ð´.",
  quotaLabel: "ÐšÐ²Ð¾Ñ‚Ð°",
  autoTitle: "Ð’ÐºÐ»ÑŽÑ‡Ð¸Ñ‚ÑŒ Ð°Ð²Ñ‚Ð¾Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ Alipay",
  autoAlerts: [
    "ÐŸÑ€ÐµÐ´Ð¾ÑÑ‚Ð°Ð²Ð»ÑÐµÑ‚ÑÑ Alipay. ÐŸÐ¾ÑÐ»Ðµ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐ°Ð½Ð¸Ñ Ð²Ñ‹ Ñ€Ð°Ð·Ñ€ÐµÑˆÐ°ÐµÑ‚Ðµ Ð¿Ð»Ð°Ñ‚Ñ„Ð¾Ñ€Ð¼Ðµ Ð°Ð²Ñ‚Ð¾Ð¼Ð°Ñ‚Ð¸Ñ‡ÐµÑÐºÐ¸ Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÑÑ‚ÑŒ Ð±Ð°Ð»Ð°Ð½Ñ Ð¿Ñ€Ð¸ Ð¿Ð°Ð´ÐµÐ½Ð¸Ð¸ Ð½Ð¸Ð¶Ðµ Ð¿Ð¾Ñ€Ð¾Ð³Ð°. ÐœÐ¾Ð¶Ð½Ð¾ Ð¾Ñ‚Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ð² Ð»ÑŽÐ±Ð¾Ðµ Ð²Ñ€ÐµÐ¼Ñ.",
    "ÐŸÐ¾ÑÐ»Ðµ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐ°Ð½Ð¸Ñ Ð¿Ð»Ð°Ñ‚Ñ„Ð¾Ñ€Ð¼Ð° Ð¿Ñ€Ð¾Ð²ÐµÑ€ÑÐµÑ‚ Ð±Ð°Ð»Ð°Ð½Ñ ÐºÐ°Ð¶Ð´Ñ‹Ðµ 10 Ð¼Ð¸Ð½ÑƒÑ‚. ÐŸÐ¾ ÑƒÐ¼Ð¾Ð»Ñ‡Ð°Ð½Ð¸ÑŽ Ð½Ð¾Ñ‡ÑŒÑŽ (22:00â€“08:00) Ð½Ðµ Ð²Ñ‹Ð¿Ð¾Ð»Ð½ÑÐµÑ‚ÑÑ. ÐœÐ¾Ð¶Ð½Ð¾ Ð½Ð°ÑÑ‚Ñ€Ð¾Ð¸Ñ‚ÑŒ Ð¿Ð¾ÑÐ»Ðµ Ð²ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¸Ñ.",
    "Ð—Ð° 10 Ð¼Ð¸Ð½ÑƒÑ‚ Ð´Ð¾ Ð°Ð²Ñ‚Ð¾Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ ÑÐ¸ÑÑ‚ÐµÐ¼Ð° Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð¸Ñ‚ SMS.",
  ],
  thresholdLabel: "ÐŸÐ¾Ñ€Ð¾Ð³",
  rechargeAmountLabel: "Ð¡ÑƒÐ¼Ð¼Ð° Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ",
  otherAmountShort: "Ð”Ñ€ÑƒÐ³Ð°Ñ ÑÑƒÐ¼Ð¼Ð°",
  thresholdHint:
    "ÐÐ²Ñ‚Ð¾Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ ÑÑ€Ð°Ð±Ð°Ñ‚Ñ‹Ð²Ð°ÐµÑ‚, ÐºÐ¾Ð³Ð´Ð° Ð±Ð°Ð»Ð°Ð½Ñ Ð½Ð¸Ð¶Ðµ Ð¿Ð¾Ñ€Ð¾Ð³Ð°. Ð”Ð¸Ð°Ð¿Ð°Ð·Ð¾Ð½ Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Ð”Ð¾Ð»Ð¶Ð½Ð¾ Ð¿Ñ€ÐµÐ²Ñ‹ÑˆÐ°Ñ‚ÑŒ Ð¿Ð¾Ñ€Ð¾Ð³, Ð¼Ð°ÐºÑ. Â¥ 2000; Ð´Ð½ÐµÐ²Ð½Ð¾Ð¹ Ð»Ð¸Ð¼Ð¸Ñ‚ Â¥ 6 000, Ð¼ÐµÑÑÑ‡Ð½Ñ‹Ð¹ Â¥ 100 000",
  autoPreview: (threshold, amount) =>
    `ÐšÐ¾Ð³Ð´Ð° Ð±Ð°Ð»Ð°Ð½Ñ < Â¥ ${threshold}, Ð°Ð²Ñ‚Ð¾Ð¿Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ Â¥ ${amount}`,
  signNow: "ÐŸÐ¾Ð´Ð¿Ð¸ÑÐ°Ñ‚ÑŒ ÑÐµÐ¹Ñ‡Ð°Ñ",
});

const vi = fromEn({
  pageTitle: "Náº¡p tiá»n",
  recordHeaders: ["ID", "Thá»i gian", "KÃªnh", "Tráº¡ng thÃ¡i", "Sá»‘ tiá»n", "Thao tÃ¡c"],
  balanceLabel: "Sá»‘ dÆ°",
  overdraftSuffix: (n) => `(Háº¡n má»©c tháº¥u chi cÃ²n láº¡i Â¥ ${n})`,
  couponLabel: "Phiáº¿u thÆ°á»Ÿng",
  couponSuffix: "kháº£ dá»¥ng",
  packageLabel: "GÃ³i tÃ i nguyÃªn",
  packageSuffix: "Ä‘ang hoáº¡t Ä‘á»™ng",
  online: "Náº¡p trá»±c tuyáº¿n",
  auto: "Náº¡p tá»± Ä‘á»™ng",
  autoOff: "ChÆ°a báº­t",
  corporate: "Chuyá»ƒn khoáº£n ngÃ¢n hÃ ng",
  warningOn: "Cáº£nh bÃ¡o sá»‘ dÆ° Ä‘Ã£ báº­t (CÃ i Ä‘áº·t)",
  warningOffChip: "Cáº£nh bÃ¡o sá»‘ dÆ° Ä‘Ã£ táº¯t (CÃ i Ä‘áº·t)",
  warningModalTitle: "CÃ i Ä‘áº·t cáº£nh bÃ¡o sá»‘ dÆ°",
  warningRule1: "Cáº£nh bÃ¡o sá»‘ dÆ° há»— trá»£ Tá»± Ä‘á»™ng, TÃ¹y chá»‰nh vÃ  Táº¯t:",
  warningRule1a:
    "á»ž cháº¿ Ä‘á»™ Tá»± Ä‘á»™ng, cáº£nh bÃ¡o Ä‘Æ°á»£c gá»­i khi háº¡n má»©c kháº£ dá»¥ng cÃ²n láº¡i (sá»‘ dÆ° cá»™ng tháº¥u chi) tháº¥p hÆ¡n má»©c tiÃªu thá»¥ sá»‘ dÆ° náº¡p trung bÃ¬nh hÃ ng ngÃ y tá»« cuá»™c gá»i API trong 7 ngÃ y qua",
  warningRule1b:
    "á»ž cháº¿ Ä‘á»™ TÃ¹y chá»‰nh, cáº£nh bÃ¡o Ä‘Æ°á»£c gá»­i khi háº¡n má»©c kháº£ dá»¥ng cÃ²n láº¡i (sá»‘ dÆ° cá»™ng tháº¥u chi) tháº¥p hÆ¡n ngÆ°á»¡ng báº¡n Ä‘áº·t",
  warningRule2:
    "Cáº£nh bÃ¡o sá»‘ dÆ° Ä‘Æ°á»£c gá»­i hÃ ng ngÃ y lÃºc 10:00 sÃ¡ng giá» Báº¯c Kinh qua SMS vÃ  email",
  warningRule3Before: "Sau láº§n náº¡p trá»±c tuyáº¿n Ä‘áº§u tiÃªn, cáº£nh bÃ¡o sá»‘ dÆ° Ä‘Æ°á»£c báº­t á»Ÿ ",
  warningRule3Bold: "cháº¿ Ä‘á»™ Tá»± Ä‘á»™ng",
  warningRule3After: "",
  warningThresholdLabel: "NgÆ°á»¡ng cáº£nh bÃ¡o:",
  warningAuto: "Tá»± Ä‘á»™ng",
  warningCustom: "TÃ¹y chá»‰nh",
  warningOff: "Táº¯t cáº£nh bÃ¡o",
  warningYuan: "CNY",
  warningCancel: "Há»§y",
  warningOk: "XÃ¡c nháº­n",
  payAmount: "Sá»‘ tiá»n thanh toÃ¡n",
  payMethod: "PhÆ°Æ¡ng thá»©c thanh toÃ¡n",
  otherAmount: "Sá»‘ tiá»n khÃ¡c",
  alipay: "Alipay",
  otherPay: "PhÆ°Æ¡ng thá»©c thanh toÃ¡n khÃ¡c",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Nháº¥n Ä‘á»ƒ xÃ¡c minh",
  captchaSuccess: "XÃ¡c minh thÃ nh cÃ´ng",
  confirmPay: "XÃ¡c nháº­n thanh toÃ¡n",
  paying: "Äang chuyá»ƒn Ä‘áº¿n thanh toÃ¡nâ€¦",
  payDisabled:
    "Náº¡p trá»±c tuyáº¿n chÆ°a kháº£ dá»¥ng. YÃªu cáº§u quáº£n trá»‹ viÃªn xÃ¡c nháº­n tuÃ¢n thá»§ thanh toÃ¡n trong Backend vÃ  cáº¥u hÃ¬nh Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "KhÃ´ng thá»ƒ báº¯t Ä‘áº§u thanh toÃ¡n. Vui lÃ²ng thá»­ láº¡i sau.",
  agreePrefix:
    "TÃ´i hiá»ƒu ráº±ng tiá»n náº¡p khÃ´ng thá»ƒ xuáº¥t hÃ³a Ä‘Æ¡n trá»±c tiáº¿p. XÃ¡c nháº­n thanh toÃ¡n Ä‘á»“ng nghÄ©a vá»›i viá»‡c Ä‘á»“ng Ã½ ",
  agreeLink: "Thá»a thuáº­n ngÆ°á»i dÃ¹ng",
  recordsTitle: "Lá»‹ch sá»­ náº¡p vÃ  hoÃ n tiá»n",
  statusPending: "Chá» thanh toÃ¡n",
  statusSuccess: "HoÃ n táº¥t",
  statusOther: "ÄÃ£ Ä‘Ã³ng",
  empty: "KhÃ´ng cÃ³ dá»¯ liá»‡u",
  segmentAll: "Táº¥t cáº£",
  segmentAvailable: "Kháº£ dá»¥ng",
  redeemCenter: "Trung tÃ¢m Ä‘á»•i mÃ£",
  redeemInputLabel: "MÃ£ Ä‘á»•i",
  redeemPlaceholder: "Nháº­p mÃ£ do quáº£n trá»‹ viÃªn cáº¥p",
  redeemSubmit: "Äá»•i",
  redeemSubmitting: "Äang Ä‘á»•iâ€¦",
  redeemCancel: "Há»§y",
  redeemSuccess: (n) => `Äá»•i thÃ nh cÃ´ng. Háº¡n má»©c +${n}`,
  redeemFailed: "Äá»•i tháº¥t báº¡i. Kiá»ƒm tra mÃ£ cÃ³ há»£p lá»‡ khÃ´ng.",
  quotaLabel: "Háº¡n má»©c",
  autoTitle: "Báº­t náº¡p tá»± Ä‘á»™ng Alipay",
  autoAlerts: [
    "Do Alipay cung cáº¥p. Sau khi kÃ½, báº¡n á»§y quyá»n ná»n táº£ng tá»± Ä‘á»™ng náº¡p khi sá»‘ dÆ° dÆ°á»›i ngÆ°á»¡ng. CÃ³ thá»ƒ há»§y báº¥t cá»© lÃºc nÃ o.",
    "Sau khi kÃ½, ná»n táº£ng kiá»ƒm tra sá»‘ dÆ° má»—i 10 phÃºt. Máº·c Ä‘á»‹nh khÃ´ng náº¡p ban Ä‘Ãªm (22:00â€“08:00). CÃ³ thá»ƒ Ä‘iá»u chá»‰nh sau khi báº­t.",
    "10 phÃºt trÆ°á»›c khi náº¡p tá»± Ä‘á»™ng, há»‡ thá»‘ng gá»­i SMS thÃ´ng bÃ¡o.",
  ],
  thresholdLabel: "NgÆ°á»¡ng",
  rechargeAmountLabel: "Sá»‘ tiá»n náº¡p",
  otherAmountShort: "Sá»‘ tiá»n khÃ¡c",
  thresholdHint:
    "Náº¡p tá»± Ä‘á»™ng kÃ­ch hoáº¡t khi sá»‘ dÆ° dÆ°á»›i ngÆ°á»¡ng. Pháº¡m vi Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Pháº£i lá»›n hÆ¡n ngÆ°á»¡ng, tá»‘i Ä‘a Â¥ 2000; giá»›i háº¡n ngÃ y Â¥ 6.000, thÃ¡ng Â¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Khi sá»‘ dÆ° < Â¥ ${threshold}, náº¡p tá»± Ä‘á»™ng Â¥ ${amount}`,
  signNow: "KÃ½ ngay",
});

const ko = fromEn({
  pageTitle: "ì¶©ì „",
  recordHeaders: ["ID", "ì‹œê°„", "ì±„ë„", "ìƒíƒœ", "ê¸ˆì•¡", "ìž‘ì—…"],
  balanceLabel: "ìž”ì•¡",
  overdraftSuffix: (n) => `(ë‚¨ì€ ì´ˆê³¼ ì¸ì¶œ í•œë„ Â¥ ${n})`,
  couponLabel: "ì¿ í°",
  couponSuffix: "ì‚¬ìš© ê°€ëŠ¥",
  packageLabel: "ë¦¬ì†ŒìŠ¤ íŒ©",
  packageSuffix: "í™œì„±",
  online: "ì˜¨ë¼ì¸ ì¶©ì „",
  auto: "ìžë™ ì¶©ì „",
  autoOff: "ë¯¸ì„¤ì •",
  corporate: "ë²•ì¸ ê³„ì¢Œ ì´ì²´",
  warningOn: "ìž”ì•¡ ì•Œë¦¼ ì¼œì§ (ì„¤ì •)",
  warningOffChip: "ìž”ì•¡ ì•Œë¦¼ êº¼ì§ (ì„¤ì •)",
  warningModalTitle: "ìž”ì•¡ ì•Œë¦¼ ì„¤ì •",
  warningRule1: "ìž”ì•¡ ì•Œë¦¼ì€ ìžë™, ì‚¬ìš©ìž ì§€ì •, ë„ê¸° ì„¸ ê°€ì§€ ëª¨ë“œë¥¼ ì§€ì›í•©ë‹ˆë‹¤:",
  warningRule1a:
    "ìžë™ ëª¨ë“œì—ì„œëŠ” ë‚¨ì€ ì‚¬ìš© ê°€ëŠ¥ í•œë„(ì¶©ì „ ìž”ì•¡ ë° ì´ˆê³¼ ì¸ì¶œ í•œë„ í¬í•¨)ê°€ ìµœê·¼ 7ì¼ API í˜¸ì¶œë¡œ ë°œìƒí•œ ì¶©ì „ ìž”ì•¡ì˜ í‰ê·  ì¼ì¼ ì†Œë¹„ë³´ë‹¤ ë‚®ì•„ì§€ë©´ ìžë™ìœ¼ë¡œ ì•Œë¦¼",
  warningRule1b:
    "ì‚¬ìš©ìž ì§€ì • ëª¨ë“œì—ì„œëŠ” ë‚¨ì€ ì‚¬ìš© ê°€ëŠ¥ í•œë„(ì¶©ì „ ìž”ì•¡ ë° ì´ˆê³¼ ì¸ì¶œ í•œë„ í¬í•¨)ê°€ ì„¤ì •í•œ ìž„ê³„ê°’ë³´ë‹¤ ë‚®ì•„ì§€ë©´ ìžë™ìœ¼ë¡œ ì•Œë¦¼",
  warningRule2:
    "ìž”ì•¡ ì•Œë¦¼ì€ ë² ì´ì§• ì‹œê°„ ë§¤ì¼ ì˜¤ì „ 10ì‹œì— SMS ë° ì´ë©”ì¼ë¡œ ë°œì†¡ë©ë‹ˆë‹¤",
  warningRule3Before: "ì²« ì˜¨ë¼ì¸ ì¶©ì „ ì™„ë£Œ í›„ ì‹œìŠ¤í…œì´ ",
  warningRule3Bold: "ìžë™ ëª¨ë“œ",
  warningRule3After: "ë¡œ ìž”ì•¡ ì•Œë¦¼ì„ ì¼­ë‹ˆë‹¤",
  warningThresholdLabel: "ì•Œë¦¼ ìž„ê³„ê°’:",
  warningAuto: "ìžë™",
  warningCustom: "ì‚¬ìš©ìž ì§€ì •",
  warningOff: "ì•Œë¦¼ ë„ê¸°",
  warningYuan: "ìœ„ì•ˆ",
  warningCancel: "ì·¨ì†Œ",
  warningOk: "í™•ì¸",
  payAmount: "ê²°ì œ ê¸ˆì•¡",
  payMethod: "ê²°ì œ ìˆ˜ë‹¨",
  otherAmount: "ê¸°íƒ€ ê¸ˆì•¡",
  alipay: "Alipay",
  otherPay: "ê¸°íƒ€ ê²°ì œ ìˆ˜ë‹¨",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "í´ë¦­í•˜ì—¬ ì¸ì¦",
  captchaSuccess: "ì¸ì¦ ì„±ê³µ",
  confirmPay: "ê²°ì œ í™•ì¸",
  paying: "ê²°ì œ íŽ˜ì´ì§€ë¡œ ì´ë™ ì¤‘â€¦",
  payDisabled:
    "ì˜¨ë¼ì¸ ì¶©ì „ì´ ì•„ì§ ì œê³µë˜ì§€ ì•ŠìŠµë‹ˆë‹¤. ê´€ë¦¬ìžì—ê²Œ Backendì—ì„œ ê²°ì œ ê·œì • ì¤€ìˆ˜ í™•ì¸ ë° Epay(PayAddress / EpayId / EpayKey / PayMethods) êµ¬ì„±ì„ ìš”ì²­í•˜ì„¸ìš”.",
  payError: "ê²°ì œë¥¼ ì‹œìž‘í•˜ì§€ ëª»í–ˆìŠµë‹ˆë‹¤. ë‚˜ì¤‘ì— ë‹¤ì‹œ ì‹œë„í•˜ì„¸ìš”.",
  agreePrefix:
    "ì¶©ì „ ìžê¸ˆì€ ì§ì ‘ ì„¸ê¸ˆê³„ì‚°ì„œë¥¼ ë°œí–‰í•  ìˆ˜ ì—†ìŒì„ ì´í•´í•©ë‹ˆë‹¤. ê²°ì œ í™•ì¸ì€ ë³¸ í”Œëž«í¼ ",
  agreeLink: "ã€Œì´ìš©ì•½ê´€ã€",
  recordsTitle: "ì¶©ì „ ë° í™˜ë¶ˆ ê¸°ë¡",
  statusPending: "ê²°ì œ ëŒ€ê¸°",
  statusSuccess: "ì™„ë£Œ",
  statusOther: "ì¢…ë£Œ",
  empty: "ë°ì´í„° ì—†ìŒ",
  segmentAll: "ì „ì²´",
  segmentAvailable: "ì‚¬ìš© ê°€ëŠ¥",
  redeemCenter: "êµí™˜ ì„¼í„°",
  redeemInputLabel: "êµí™˜ ì½”ë“œ",
  redeemPlaceholder: "ê´€ë¦¬ìžê°€ ë°œê¸‰í•œ ì½”ë“œë¥¼ ìž…ë ¥í•˜ì„¸ìš”",
  redeemSubmit: "êµí™˜",
  redeemSubmitting: "êµí™˜ ì¤‘â€¦",
  redeemCancel: "ì·¨ì†Œ",
  redeemSuccess: (n) => `êµí™˜ ì„±ê³µ. í•œë„ +${n}`,
  redeemFailed: "êµí™˜ ì‹¤íŒ¨. ì½”ë“œê°€ ìœ íš¨í•œì§€ í™•ì¸í•˜ì„¸ìš”.",
  quotaLabel: "í•œë„",
  autoTitle: "Alipay ìžë™ ì¶©ì „ í™œì„±í™”",
  autoAlerts: [
    "Alipayì—ì„œ ì œê³µí•©ë‹ˆë‹¤. ê³„ì•½ í›„ ìž”ì•¡ì´ ì„¤ì • ìž„ê³„ê°’ ì•„ëž˜ë¡œ ë–¨ì–´ì§€ë©´ ìžë™ ì¶©ì „ì„ í—ˆìš©í•©ë‹ˆë‹¤. ì–¸ì œë“  ì·¨ì†Œí•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.",
    "ê³„ì•½ í›„ í”Œëž«í¼ì€ 10ë¶„ë§ˆë‹¤ ìž”ì•¡ì„ í™•ì¸í•©ë‹ˆë‹¤. ê¸°ë³¸ì ìœ¼ë¡œ ì•¼ê°„(22:00~08:00)ì—ëŠ” ì‹¤í–‰ë˜ì§€ ì•ŠìŠµë‹ˆë‹¤(í™œì„±í™” í›„ ì¡°ì • ê°€ëŠ¥).",
    "ìžë™ ì¶©ì „ 10ë¶„ ì „ì— ì‹œìŠ¤í…œì´ SMS ì•Œë¦¼ì„ ë³´ëƒ…ë‹ˆë‹¤.",
  ],
  thresholdLabel: "ìž„ê³„ê°’ ì„¤ì •",
  rechargeAmountLabel: "ì¶©ì „ ê¸ˆì•¡",
  otherAmountShort: "ê¸°íƒ€ ê¸ˆì•¡",
  thresholdHint: "ìž”ì•¡ì´ ìž„ê³„ê°’ ì•„ëž˜ë¡œ ë–¨ì–´ì§€ë©´ ìžë™ ì¶©ì „ë©ë‹ˆë‹¤. ë²”ìœ„ Â¥ 5 ~ Â¥ 1000",
  amountHint: "ìž„ê³„ê°’ë³´ë‹¤ ì»¤ì•¼ í•˜ë©°, ìƒí•œ Â¥ 2000; ì¼ì¼ ëˆ„ì  Â¥ 6,000, ì›”ê°„ ëˆ„ì  Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `ìž”ì•¡ < Â¥ ${threshold}ì¼ ë•Œ ìžë™ ì¶©ì „ Â¥ ${amount}`,
  signNow: "ì§€ê¸ˆ ê³„ì•½",
});

const de = fromEn({
  pageTitle: "Aufladen",
  recordHeaders: ["ID", "Zeit", "Kanal", "Status", "Betrag", "Aktionen"],
  balanceLabel: "Guthaben",
  overdraftSuffix: (n) => `(Verbleibendes Ãœberziehungskontingent Â¥ ${n})`,
  couponLabel: "Gutscheine",
  couponSuffix: "verfÃ¼gbar",
  packageLabel: "Ressourcenpakete",
  packageSuffix: "aktiv",
  online: "Online-Aufladung",
  auto: "Automatisches Aufladen",
  autoOff: "Nicht aktiviert",
  corporate: "BankÃ¼berweisung",
  warningOn: "Guthabenwarnung aktiv (Einstellungen)",
  warningOffChip: "Guthabenwarnung deaktiviert (Einstellungen)",
  warningModalTitle: "Guthabenwarnung-Einstellungen",
  warningRule1: "Guthabenwarnungen unterstÃ¼tzen Auto, Benutzerdefiniert und Aus:",
  warningRule1a:
    "Im Auto-Modus wird gewarnt, wenn das verbleibende verfÃ¼gbare Kontingent (Guthaben plus Ãœberziehung) unter dem durchschnittlichen tÃ¤glichen Aufladeguthaben-Verbrauch der letzten 7 Tage API-Aufrufe fÃ¤llt",
  warningRule1b:
    "Im benutzerdefinierten Modus wird gewarnt, wenn das verbleibende verfÃ¼gbare Kontingent (Guthaben plus Ãœberziehung) unter Ihren Schwellenwert fÃ¤llt",
  warningRule2:
    "Guthabenwarnungen werden tÃ¤glich um 10:00 Uhr Peking-Zeit per SMS und E-Mail gesendet",
  warningRule3Before: "Nach der ersten Online-Aufladung werden Guthabenwarnungen im ",
  warningRule3Bold: "Auto-Modus",
  warningRule3After: " aktiviert",
  warningThresholdLabel: "Warnschwelle:",
  warningAuto: "Auto",
  warningCustom: "Benutzerdefiniert",
  warningOff: "Warnungen ausschalten",
  warningYuan: "CNY",
  warningCancel: "Abbrechen",
  warningOk: "BestÃ¤tigen",
  payAmount: "Zahlungsbetrag",
  payMethod: "Zahlungsmethode",
  otherAmount: "Anderer Betrag",
  alipay: "Alipay",
  otherPay: "Andere Zahlungsmethoden",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Klicken zum Verifizieren",
  captchaSuccess: "Verifiziert",
  confirmPay: "Zahlung bestÃ¤tigen",
  paying: "Weiterleitung zur Zahlungâ€¦",
  payDisabled:
    "Online-Aufladung ist noch nicht verfÃ¼gbar. Bitten Sie einen Admin, die Zahlungscompliance in Backend zu bestÃ¤tigen und Epay zu konfigurieren (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Zahlung konnte nicht gestartet werden. Bitte spÃ¤ter erneut versuchen.",
  agreePrefix:
    "Ich verstehe, dass aufgeladene Mittel nicht direkt in Rechnung gestellt werden kÃ¶nnen. Mit der ZahlungsbestÃ¤tigung akzeptiere ich die ",
  agreeLink: "Nutzungsbedingungen",
  recordsTitle: "Auflade- und RÃ¼ckerstattungsverlauf",
  statusPending: "Zahlung ausstehend",
  statusSuccess: "Abgeschlossen",
  statusOther: "Geschlossen",
  empty: "Keine Daten",
  segmentAll: "Alle",
  segmentAvailable: "VerfÃ¼gbar",
  redeemCenter: "EinlÃ¶sezentrum",
  redeemInputLabel: "EinlÃ¶secode",
  redeemPlaceholder: "Vom Administrator ausgegebenen Code eingeben",
  redeemSubmit: "EinlÃ¶sen",
  redeemSubmitting: "EinlÃ¶senâ€¦",
  redeemCancel: "Abbrechen",
  redeemSuccess: (n) => `EinlÃ¶sung erfolgreich. Kontingent +${n}`,
  redeemFailed: "EinlÃ¶sung fehlgeschlagen. PrÃ¼fen Sie, ob der Code gÃ¼ltig ist.",
  quotaLabel: "Kontingent",
  autoTitle: "Alipay-Autoladung aktivieren",
  autoAlerts: [
    "Von Alipay bereitgestellt. Nach der Unterzeichnung autorisieren Sie die Plattform, automatisch aufzuladen, wenn Ihr Guthaben unter den Schwellenwert fÃ¤llt. Jederzeit kÃ¼ndbar.",
    "Nach der Unterzeichnung prÃ¼ft die Plattform alle 10 Minuten das Guthaben. StandardmÃ¤ÃŸig nachts (22:00â€“08:00) keine Aufladung. Nach Aktivierung anpassbar.",
    "Zehn Minuten vor einer Autoladung sendet das System eine SMS-Benachrichtigung.",
  ],
  thresholdLabel: "Schwellenwert",
  rechargeAmountLabel: "Aufladebetrag",
  otherAmountShort: "Anderer Betrag",
  thresholdHint:
    "Autoladung wird ausgelÃ¶st, wenn das Guthaben unter den Schwellenwert fÃ¤llt. Bereich Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Muss den Schwellenwert Ã¼berschreiten, max. Â¥ 2000; Tageslimit Â¥ 6.000, Monatslimit Â¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Wenn Guthaben < Â¥ ${threshold}, Autoladung Â¥ ${amount}`,
  signNow: "Jetzt unterzeichnen",
});

const es = fromEn({
  pageTitle: "Recargar",
  recordHeaders: ["ID", "Hora", "Canal", "Estado", "Importe", "Acciones"],
  balanceLabel: "Saldo",
  overdraftSuffix: (n) => `(Cuota de sobregiro restante Â¥ ${n})`,
  couponLabel: "Cupones",
  couponSuffix: "disponibles",
  packageLabel: "Paquetes de recursos",
  packageSuffix: "activos",
  online: "Recarga en lÃ­nea",
  auto: "Recarga automÃ¡tica",
  autoOff: "No activada",
  corporate: "Transferencia bancaria",
  warningOn: "Alerta de saldo activada (Ajustes)",
  warningOffChip: "Alerta de saldo desactivada (Ajustes)",
  warningModalTitle: "Ajustes de alerta de saldo",
  warningRule1: "Las alertas de saldo admiten Auto, Personalizado y Desactivado:",
  warningRule1a:
    "En modo Auto, se envÃ­a una alerta cuando la cuota disponible restante (saldo mÃ¡s sobregiro) cae por debajo del consumo diario promedio del saldo de recarga de las llamadas API de los Ãºltimos 7 dÃ­as",
  warningRule1b:
    "En modo Personalizado, se envÃ­a una alerta cuando la cuota disponible restante (saldo mÃ¡s sobregiro) cae por debajo de su umbral",
  warningRule2:
    "Las alertas de saldo se envÃ­an diariamente a las 10:00 (hora de PekÃ­n) por SMS y correo",
  warningRule3Before: "Tras su primera recarga en lÃ­nea, las alertas de saldo se activan en ",
  warningRule3Bold: "modo Auto",
  warningRule3After: "",
  warningThresholdLabel: "Umbral de alerta:",
  warningAuto: "Auto",
  warningCustom: "Personalizado",
  warningOff: "Desactivar alertas",
  warningYuan: "CNY",
  warningCancel: "Cancelar",
  warningOk: "Confirmar",
  payAmount: "Importe del pago",
  payMethod: "MÃ©todo de pago",
  otherAmount: "Otro importe",
  alipay: "Alipay",
  otherPay: "Otros mÃ©todos de pago",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Clic para verificar",
  captchaSuccess: "Verificado",
  confirmPay: "Confirmar pago",
  paying: "Redirigiendo al pagoâ€¦",
  payDisabled:
    "La recarga en lÃ­nea aÃºn no estÃ¡ disponible. Pida a un administrador confirmar el cumplimiento de pagos en Backend y configurar Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "No se pudo iniciar el pago. IntÃ©ntelo mÃ¡s tarde.",
  agreePrefix:
    "Entiendo que los fondos recargados no pueden facturarse directamente. Al confirmar el pago, acepto el ",
  agreeLink: "Acuerdo de usuario",
  recordsTitle: "Historial de recargas y reembolsos",
  statusPending: "Pago pendiente",
  statusSuccess: "Completado",
  statusOther: "Cerrado",
  empty: "Sin datos",
  segmentAll: "Todo",
  segmentAvailable: "Disponible",
  redeemCenter: "Centro de canje",
  redeemInputLabel: "CÃ³digo de canje",
  redeemPlaceholder: "Introduzca el cÃ³digo emitido por un administrador",
  redeemSubmit: "Canjear",
  redeemSubmitting: "Canjeandoâ€¦",
  redeemCancel: "Cancelar",
  redeemSuccess: (n) => `Canje exitoso. Cuota +${n}`,
  redeemFailed: "Canje fallido. Compruebe si el cÃ³digo es vÃ¡lido.",
  quotaLabel: "Cuota",
  autoTitle: "Activar recarga automÃ¡tica Alipay",
  autoAlerts: [
    "Proporcionado por Alipay. Tras firmar, autoriza a la plataforma a recargar automÃ¡ticamente cuando su saldo caiga por debajo del umbral. Puede cancelar en cualquier momento.",
    "Tras firmar, la plataforma comprueba el saldo cada 10 minutos. Por defecto no recarga de noche (22:00â€“08:00). Ajustable tras activar.",
    "Diez minutos antes de una recarga automÃ¡tica, el sistema le envÃ­a un SMS.",
  ],
  thresholdLabel: "Umbral",
  rechargeAmountLabel: "Importe de recarga",
  otherAmountShort: "Otro importe",
  thresholdHint:
    "La recarga automÃ¡tica se activa cuando el saldo cae por debajo del umbral. Rango Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Debe superar el umbral, mÃ¡x. Â¥ 2000; lÃ­mite diario Â¥ 6.000, mensual Â¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Cuando saldo < Â¥ ${threshold}, recarga automÃ¡tica Â¥ ${amount}`,
  signNow: "Firmar ahora",
});

const ptBR = fromEn({
  pageTitle: "Recarga",
  recordHeaders: ["ID", "Hora", "Canal", "Status", "Valor", "AÃ§Ãµes"],
  balanceLabel: "Saldo",
  overdraftSuffix: (n) => `(Cota de cheque especial restante Â¥ ${n})`,
  couponLabel: "Cupons",
  couponSuffix: "disponÃ­veis",
  packageLabel: "Pacotes de recursos",
  packageSuffix: "ativos",
  online: "Recarga online",
  auto: "Recarga automÃ¡tica",
  autoOff: "NÃ£o ativada",
  corporate: "TransferÃªncia bancÃ¡ria",
  warningOn: "Alerta de saldo ativada (ConfiguraÃ§Ãµes)",
  warningOffChip: "Alerta de saldo desativada (ConfiguraÃ§Ãµes)",
  warningModalTitle: "ConfiguraÃ§Ãµes de alerta de saldo",
  warningRule1: "Alertas de saldo suportam Auto, Personalizado e Desligado:",
  warningRule1a:
    "No modo Auto, um alerta Ã© enviado quando a cota disponÃ­vel restante (saldo mais cheque especial) fica abaixo do consumo mÃ©dio diÃ¡rio do saldo de recarga das chamadas API dos Ãºltimos 7 dias",
  warningRule1b:
    "No modo Personalizado, um alerta Ã© enviado quando a cota disponÃ­vel restante (saldo mais cheque especial) fica abaixo do seu limite",
  warningRule2:
    "Alertas de saldo sÃ£o enviados diariamente Ã s 10:00 (horÃ¡rio de Pequim) por SMS e e-mail",
  warningRule3Before: "ApÃ³s sua primeira recarga online, alertas de saldo sÃ£o ativados no ",
  warningRule3Bold: "modo Auto",
  warningRule3After: "",
  warningThresholdLabel: "Limite de alerta:",
  warningAuto: "Auto",
  warningCustom: "Personalizado",
  warningOff: "Desativar alertas",
  warningYuan: "CNY",
  warningCancel: "Cancelar",
  warningOk: "Confirmar",
  payAmount: "Valor do pagamento",
  payMethod: "Forma de pagamento",
  otherAmount: "Outro valor",
  alipay: "Alipay",
  otherPay: "Outras formas de pagamento",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Clique para verificar",
  captchaSuccess: "Verificado",
  confirmPay: "Confirmar pagamento",
  paying: "Redirecionando ao pagamentoâ€¦",
  payDisabled:
    "Recarga online ainda nÃ£o disponÃ­vel. PeÃ§a a um administrador confirmar conformidade de pagamento no Backend e configurar Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Falha ao iniciar pagamento. Tente novamente mais tarde.",
  agreePrefix:
    "Entendo que fundos recarregados nÃ£o podem ser faturados diretamente. Ao confirmar o pagamento, concordo com o ",
  agreeLink: "Acordo do usuÃ¡rio",
  recordsTitle: "HistÃ³rico de recargas e reembolsos",
  statusPending: "Pagamento pendente",
  statusSuccess: "ConcluÃ­do",
  statusOther: "Fechado",
  empty: "Sem dados",
  segmentAll: "Todos",
  segmentAvailable: "DisponÃ­vel",
  redeemCenter: "Central de resgate",
  redeemInputLabel: "CÃ³digo de resgate",
  redeemPlaceholder: "Digite o cÃ³digo emitido por um administrador",
  redeemSubmit: "Resgatar",
  redeemSubmitting: "Resgatandoâ€¦",
  redeemCancel: "Cancelar",
  redeemSuccess: (n) => `Resgate bem-sucedido. Cota +${n}`,
  redeemFailed: "Resgate falhou. Verifique se o cÃ³digo Ã© vÃ¡lido.",
  quotaLabel: "Cota",
  autoTitle: "Ativar recarga automÃ¡tica Alipay",
  autoAlerts: [
    "Fornecido pelo Alipay. ApÃ³s assinar, vocÃª autoriza a plataforma a recarregar automaticamente quando o saldo ficar abaixo do limite. Pode cancelar a qualquer momento.",
    "ApÃ³s assinar, a plataforma verifica o saldo a cada 10 minutos. Por padrÃ£o, nÃ£o recarrega Ã  noite (22:00â€“08:00). AjustÃ¡vel apÃ³s ativar.",
    "Dez minutos antes de uma recarga automÃ¡tica, o sistema envia um SMS.",
  ],
  thresholdLabel: "Limite",
  rechargeAmountLabel: "Valor da recarga",
  otherAmountShort: "Outro valor",
  thresholdHint:
    "Recarga automÃ¡tica dispara quando o saldo fica abaixo do limite. Faixa Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Deve ser maior que o limite, mÃ¡x. Â¥ 2000; teto diÃ¡rio Â¥ 6.000, mensal Â¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Quando saldo < Â¥ ${threshold}, recarga automÃ¡tica Â¥ ${amount}`,
  signNow: "Assinar agora",
});

const ar = fromEn({
  pageTitle: "Ø´Ø­Ù†",
  recordHeaders: ["Ø§Ù„Ù…Ø¹Ø±Ù‘Ù", "Ø§Ù„ÙˆÙ‚Øª", "Ø§Ù„Ù‚Ù†Ø§Ø©", "Ø§Ù„Ø­Ø§Ù„Ø©", "Ø§Ù„Ù…Ø¨Ù„Øº", "Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª"],
  balanceLabel: "Ø§Ù„Ø±ØµÙŠØ¯",
  overdraftSuffix: (n) => `(Ø­ØµØ© Ø§Ù„Ø³Ø­Ø¨ Ø¹Ù„Ù‰ Ø§Ù„Ù…ÙƒØ´ÙˆÙ Ø§Ù„Ù…ØªØ¨Ù‚ÙŠØ© Â¥ ${n})`,
  couponLabel: "Ù‚Ø³Ø§Ø¦Ù…",
  couponSuffix: "Ù…ØªØ§Ø­Ø©",
  packageLabel: "Ø­Ø²Ù… Ø§Ù„Ù…ÙˆØ§Ø±Ø¯",
  packageSuffix: "Ù†Ø´Ø·Ø©",
  online: "Ø´Ø­Ù† Ø¹Ø¨Ø± Ø§Ù„Ø¥Ù†ØªØ±Ù†Øª",
  auto: "Ø´Ø­Ù† ØªÙ„Ù‚Ø§Ø¦ÙŠ",
  autoOff: "ØºÙŠØ± Ù…ÙØ¹Ù‘Ù„",
  corporate: "ØªØ­ÙˆÙŠÙ„ Ø¨Ù†ÙƒÙŠ",
  warningOn: "ØªÙ†Ø¨ÙŠÙ‡ Ø§Ù„Ø±ØµÙŠØ¯ Ù…ÙØ¹Ù‘Ù„ (Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª)",
  warningOffChip: "ØªÙ†Ø¨ÙŠÙ‡ Ø§Ù„Ø±ØµÙŠØ¯ Ù…Ø¹Ø·Ù‘Ù„ (Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª)",
  warningModalTitle: "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª ØªÙ†Ø¨ÙŠÙ‡ Ø§Ù„Ø±ØµÙŠØ¯",
  warningRule1: "ØªØ¯Ø¹Ù… ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø±ØµÙŠØ¯: ØªÙ„Ù‚Ø§Ø¦ÙŠØŒ Ù…Ø®ØµØµØŒ ÙˆØ¥ÙŠÙ‚Ø§Ù:",
  warningRule1a:
    "ÙÙŠ Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠØŒ ÙŠÙØ±Ø³Ù„ ØªÙ†Ø¨ÙŠÙ‡ Ø¹Ù†Ø¯Ù…Ø§ ØªÙ†Ø®ÙØ¶ Ø§Ù„Ø­ØµØ© Ø§Ù„Ù…ØªØ§Ø­Ø© Ø§Ù„Ù…ØªØ¨Ù‚ÙŠØ© (Ø§Ù„Ø±ØµÙŠØ¯ Ø¨Ø§Ù„Ø¥Ø¶Ø§ÙØ© Ø¥Ù„Ù‰ Ø§Ù„Ø³Ø­Ø¨ Ø¹Ù„Ù‰ Ø§Ù„Ù…ÙƒØ´ÙˆÙ) Ø¹Ù† Ù…ØªÙˆØ³Ø· Ø§Ù„Ø§Ø³ØªÙ‡Ù„Ø§Ùƒ Ø§Ù„ÙŠÙˆÙ…ÙŠ Ù„Ø±ØµÙŠØ¯ Ø§Ù„Ø´Ø­Ù† Ù…Ù† Ø§Ø³ØªØ¯Ø¹Ø§Ø¡Ø§Øª API Ø®Ù„Ø§Ù„ Ø¢Ø®Ø± 7 Ø£ÙŠØ§Ù…",
  warningRule1b:
    "ÙÙŠ Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„Ù…Ø®ØµØµØŒ ÙŠÙØ±Ø³Ù„ ØªÙ†Ø¨ÙŠÙ‡ Ø¹Ù†Ø¯Ù…Ø§ ØªÙ†Ø®ÙØ¶ Ø§Ù„Ø­ØµØ© Ø§Ù„Ù…ØªØ§Ø­Ø© Ø§Ù„Ù…ØªØ¨Ù‚ÙŠØ© (Ø§Ù„Ø±ØµÙŠØ¯ Ø¨Ø§Ù„Ø¥Ø¶Ø§ÙØ© Ø¥Ù„Ù‰ Ø§Ù„Ø³Ø­Ø¨ Ø¹Ù„Ù‰ Ø§Ù„Ù…ÙƒØ´ÙˆÙ) Ø¹Ù† Ø¹ØªØ¨ØªÙƒ",
  warningRule2:
    "ØªÙØ±Ø³Ù„ ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø±ØµÙŠØ¯ ÙŠÙˆÙ…ÙŠÙ‹Ø§ Ø§Ù„Ø³Ø§Ø¹Ø© 10:00 ØµØ¨Ø§Ø­Ù‹Ø§ Ø¨ØªÙˆÙ‚ÙŠØª Ø¨ÙƒÙŠÙ† Ø¹Ø¨Ø± SMS ÙˆØ§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ",
  warningRule3Before: "Ø¨Ø¹Ø¯ Ø£ÙˆÙ„ Ø´Ø­Ù† Ø¹Ø¨Ø± Ø§Ù„Ø¥Ù†ØªØ±Ù†ØªØŒ ØªÙÙØ¹Ù‘Ù„ ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø±ØµÙŠØ¯ ÙÙŠ ",
  warningRule3Bold: "Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠ",
  warningRule3After: "",
  warningThresholdLabel: "Ø¹ØªØ¨Ø© Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡:",
  warningAuto: "ØªÙ„Ù‚Ø§Ø¦ÙŠ",
  warningCustom: "Ù…Ø®ØµØµ",
  warningOff: "Ø¥ÙŠÙ‚Ø§Ù Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡Ø§Øª",
  warningYuan: "CNY",
  warningCancel: "Ø¥Ù„ØºØ§Ø¡",
  warningOk: "ØªØ£ÙƒÙŠØ¯",
  payAmount: "Ù…Ø¨Ù„Øº Ø§Ù„Ø¯ÙØ¹",
  payMethod: "Ø·Ø±ÙŠÙ‚Ø© Ø§Ù„Ø¯ÙØ¹",
  otherAmount: "Ù…Ø¨Ù„Øº Ø¢Ø®Ø±",
  alipay: "Alipay",
  otherPay: "Ø·Ø±Ù‚ Ø¯ÙØ¹ Ø£Ø®Ø±Ù‰",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Ø§Ù†Ù‚Ø± Ù„Ù„ØªØ­Ù‚Ù‚",
  captchaSuccess: "ØªÙ… Ø§Ù„ØªØ­Ù‚Ù‚",
  confirmPay: "ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø¯ÙØ¹",
  paying: "Ø¬Ø§Ø±Ù Ø§Ù„ØªÙˆØ¬ÙŠÙ‡ Ø¥Ù„Ù‰ Ø§Ù„Ø¯ÙØ¹â€¦",
  payDisabled:
    "Ø§Ù„Ø´Ø­Ù† Ø¹Ø¨Ø± Ø§Ù„Ø¥Ù†ØªØ±Ù†Øª ØºÙŠØ± Ù…ØªØ§Ø­ Ø¨Ø¹Ø¯. Ø§Ø·Ù„Ø¨ Ù…Ù† Ø§Ù„Ù…Ø³Ø¤ÙˆÙ„ ØªØ£ÙƒÙŠØ¯ Ø§Ù…ØªØ«Ø§Ù„ Ø§Ù„Ø¯ÙØ¹ ÙÙŠ Backend ÙˆØªÙƒÙˆÙŠÙ† Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "ØªØ¹Ø°Ù‘Ø± Ø¨Ø¯Ø¡ Ø§Ù„Ø¯ÙØ¹. ÙŠØ±Ø¬Ù‰ Ø§Ù„Ù…Ø­Ø§ÙˆÙ„Ø© Ù„Ø§Ø­Ù‚Ù‹Ø§.",
  agreePrefix:
    "Ø£ÙÙ‡Ù… Ø£Ù† Ø£Ù…ÙˆØ§Ù„ Ø§Ù„Ø´Ø­Ù† Ù„Ø§ ÙŠÙ…ÙƒÙ† Ø¥ØµØ¯Ø§Ø± ÙØ§ØªÙˆØ±Ø© Ù„Ù‡Ø§ Ù…Ø¨Ø§Ø´Ø±Ø©. Ø¨ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø¯ÙØ¹ØŒ Ø£ÙˆØ§ÙÙ‚ Ø¹Ù„Ù‰ ",
  agreeLink: "Ø§ØªÙØ§Ù‚ÙŠØ© Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…",
  recordsTitle: "Ø³Ø¬Ù„ Ø§Ù„Ø´Ø­Ù† ÙˆØ§Ù„Ø§Ø³ØªØ±Ø¯Ø§Ø¯",
  statusPending: "ÙÙŠ Ø§Ù†ØªØ¸Ø§Ø± Ø§Ù„Ø¯ÙØ¹",
  statusSuccess: "Ù…ÙƒØªÙ…Ù„",
  statusOther: "Ù…ØºÙ„Ù‚",
  empty: "Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¨ÙŠØ§Ù†Ø§Øª",
  segmentAll: "Ø§Ù„ÙƒÙ„",
  segmentAvailable: "Ù…ØªØ§Ø­",
  redeemCenter: "Ù…Ø±ÙƒØ² Ø§Ù„Ø§Ø³ØªØ±Ø¯Ø§Ø¯",
  redeemInputLabel: "Ø±Ù…Ø² Ø§Ù„Ø§Ø³ØªØ±Ø¯Ø§Ø¯",
  redeemPlaceholder: "Ø£Ø¯Ø®Ù„ Ø§Ù„Ø±Ù…Ø² Ø§Ù„ØµØ§Ø¯Ø± Ù…Ù† Ø§Ù„Ù…Ø³Ø¤ÙˆÙ„",
  redeemSubmit: "Ø§Ø³ØªØ±Ø¯Ø§Ø¯",
  redeemSubmitting: "Ø¬Ø§Ø±Ù Ø§Ù„Ø§Ø³ØªØ±Ø¯Ø§Ø¯â€¦",
  redeemCancel: "Ø¥Ù„ØºØ§Ø¡",
  redeemSuccess: (n) => `ØªÙ… Ø§Ù„Ø§Ø³ØªØ±Ø¯Ø§Ø¯ Ø¨Ù†Ø¬Ø§Ø­. Ø§Ù„Ø­ØµØ© +${n}`,
  redeemFailed: "ÙØ´Ù„ Ø§Ù„Ø§Ø³ØªØ±Ø¯Ø§Ø¯. ØªØ­Ù‚Ù‚ Ù…Ù† ØµØ­Ø© Ø§Ù„Ø±Ù…Ø².",
  quotaLabel: "Ø§Ù„Ø­ØµØ©",
  autoTitle: "ØªÙØ¹ÙŠÙ„ Ø§Ù„Ø´Ø­Ù† Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠ Ø¹Ø¨Ø± Alipay",
  autoAlerts: [
    "Ù…Ù‚Ø¯Ù‘Ù… Ù…Ù† Alipay. Ø¨Ø¹Ø¯ Ø§Ù„ØªÙˆÙ‚ÙŠØ¹ØŒ ØªÙÙˆÙ‘Ø¶ Ø§Ù„Ù…Ù†ØµØ© Ø¨Ø§Ù„Ø´Ø­Ù† ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‹Ø§ Ø¹Ù†Ø¯Ù…Ø§ ÙŠÙ†Ø®ÙØ¶ Ø±ØµÙŠØ¯Ùƒ Ø¹Ù† Ø§Ù„Ø¹ØªØ¨Ø©. ÙŠÙ…ÙƒÙ† Ø§Ù„Ø¥Ù„ØºØ§Ø¡ ÙÙŠ Ø£ÙŠ ÙˆÙ‚Øª.",
    "Ø¨Ø¹Ø¯ Ø§Ù„ØªÙˆÙ‚ÙŠØ¹ØŒ ØªØªØ­Ù‚Ù‚ Ø§Ù„Ù…Ù†ØµØ© Ù…Ù† Ø§Ù„Ø±ØµÙŠØ¯ ÙƒÙ„ 10 Ø¯Ù‚Ø§Ø¦Ù‚. Ø§ÙØªØ±Ø§Ø¶ÙŠÙ‹Ø§ Ù„Ø§ ÙŠÙÙ†ÙÙ‘Ø° Ù„ÙŠÙ„Ù‹Ø§ (22:00â€“08:00). Ù‚Ø§Ø¨Ù„ Ù„Ù„ØªØ¹Ø¯ÙŠÙ„ Ø¨Ø¹Ø¯ Ø§Ù„ØªÙØ¹ÙŠÙ„.",
    "Ù‚Ø¨Ù„ 10 Ø¯Ù‚Ø§Ø¦Ù‚ Ù…Ù† Ø§Ù„Ø´Ø­Ù† Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠØŒ ÙŠØ±Ø³Ù„ Ø§Ù„Ù†Ø¸Ø§Ù… Ø¥Ø´Ø¹Ø§Ø± SMS.",
  ],
  thresholdLabel: "Ø§Ù„Ø¹ØªØ¨Ø©",
  rechargeAmountLabel: "Ù…Ø¨Ù„Øº Ø§Ù„Ø´Ø­Ù†",
  otherAmountShort: "Ù…Ø¨Ù„Øº Ø¢Ø®Ø±",
  thresholdHint:
    "ÙŠÙÙØ¹Ù‘Ù„ Ø§Ù„Ø´Ø­Ù† Ø§Ù„ØªÙ„Ù‚Ø§Ø¦ÙŠ Ø¹Ù†Ø¯Ù…Ø§ ÙŠÙ†Ø®ÙØ¶ Ø§Ù„Ø±ØµÙŠØ¯ Ø¹Ù† Ø§Ù„Ø¹ØªØ¨Ø©. Ø§Ù„Ù†Ø·Ø§Ù‚ Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "ÙŠØ¬Ø¨ Ø£Ù† ÙŠØªØ¬Ø§ÙˆØ² Ø§Ù„Ø¹ØªØ¨Ø©ØŒ Ø¨Ø­Ø¯ Ø£Ù‚ØµÙ‰ Â¥ 2000Ø› Ø­Ø¯ ÙŠÙˆÙ…ÙŠ Â¥ 6,000ØŒ Ø´Ù‡Ø±ÙŠ Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `Ø¹Ù†Ø¯Ù…Ø§ Ø§Ù„Ø±ØµÙŠØ¯ < Â¥ ${threshold}ØŒ Ø´Ø­Ù† ØªÙ„Ù‚Ø§Ø¦ÙŠ Â¥ ${amount}`,
  signNow: "ÙˆÙ‚Ù‘Ø¹ Ø§Ù„Ø¢Ù†",
});

const hi = fromEn({
  pageTitle: "à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ",
  recordHeaders: ["ID", "à¤¸à¤®à¤¯", "à¤šà¥ˆà¤¨à¤²", "à¤¸à¥à¤¥à¤¿à¤¤à¤¿", "à¤°à¤¾à¤¶à¤¿", "à¤•à¤¾à¤°à¥à¤°à¤µà¤¾à¤ˆ"],
  balanceLabel: "à¤¶à¥‡à¤·",
  overdraftSuffix: (n) => `(à¤¶à¥‡à¤· à¤“à¤µà¤°à¤¡à¥à¤°à¤¾à¤«à¥à¤Ÿ à¤•à¥‹à¤Ÿà¤¾ Â¥ ${n})`,
  couponLabel: "à¤µà¤¾à¤‰à¤šà¤°",
  couponSuffix: "à¤‰à¤ªà¤²à¤¬à¥à¤§",
  packageLabel: "à¤¸à¤‚à¤¸à¤¾à¤§à¤¨ à¤ªà¥ˆà¤•",
  packageSuffix: "à¤¸à¤•à¥à¤°à¤¿à¤¯",
  online: "à¤‘à¤¨à¤²à¤¾à¤‡à¤¨ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ",
  auto: "à¤‘à¤Ÿà¥‹ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ",
  autoOff: "à¤¸à¤•à¥à¤·à¤® à¤¨à¤¹à¥€à¤‚",
  corporate: "à¤¬à¥ˆà¤‚à¤• à¤Ÿà¥à¤°à¤¾à¤‚à¤¸à¤«à¤°",
  warningOn: "à¤¬à¥ˆà¤²à¥‡à¤‚à¤¸ à¤…à¤²à¤°à¥à¤Ÿ à¤šà¤¾à¤²à¥‚ (à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸)",
  warningOffChip: "à¤¬à¥ˆà¤²à¥‡à¤‚à¤¸ à¤…à¤²à¤°à¥à¤Ÿ à¤¬à¤‚à¤¦ (à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸)",
  warningModalTitle: "à¤¬à¥ˆà¤²à¥‡à¤‚à¤¸ à¤…à¤²à¤°à¥à¤Ÿ à¤¸à¥‡à¤Ÿà¤¿à¤‚à¤—à¥à¤¸",
  warningRule1: "à¤¬à¥ˆà¤²à¥‡à¤‚à¤¸ à¤…à¤²à¤°à¥à¤Ÿ à¤®à¥‡à¤‚ à¤‘à¤Ÿà¥‹, à¤•à¤¸à¥à¤Ÿà¤® à¤”à¤° à¤¬à¤‚à¤¦ à¤¤à¥€à¤¨ à¤®à¥‹à¤¡ à¤¹à¥ˆà¤‚:",
  warningRule1a:
    "à¤‘à¤Ÿà¥‹ à¤®à¥‹à¤¡ à¤®à¥‡à¤‚, à¤œà¤¬ à¤¶à¥‡à¤· à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤•à¥‹à¤Ÿà¤¾ (à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤¶à¥‡à¤· à¤”à¤° à¤“à¤µà¤°à¤¡à¥à¤°à¤¾à¤«à¥à¤Ÿ à¤¸à¤¹à¤¿à¤¤) à¤ªà¤¿à¤›à¤²à¥‡ 7 à¤¦à¤¿à¤¨à¥‹à¤‚ à¤•à¥‡ API à¤•à¥‰à¤² à¤¸à¥‡ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤¶à¥‡à¤· à¤•à¥€ à¤”à¤¸à¤¤ à¤¦à¥ˆà¤¨à¤¿à¤• à¤–à¤ªà¤¤ à¤¸à¥‡ à¤¨à¥€à¤šà¥‡ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ à¤¤à¥‹ à¤…à¤²à¤°à¥à¤Ÿ à¤­à¥‡à¤œà¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ",
  warningRule1b:
    "à¤•à¤¸à¥à¤Ÿà¤® à¤®à¥‹à¤¡ à¤®à¥‡à¤‚, à¤œà¤¬ à¤¶à¥‡à¤· à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤•à¥‹à¤Ÿà¤¾ (à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤¶à¥‡à¤· à¤”à¤° à¤“à¤µà¤°à¤¡à¥à¤°à¤¾à¤«à¥à¤Ÿ à¤¸à¤¹à¤¿à¤¤) à¤†à¤ªà¤•à¥€ à¤¸à¥€à¤®à¤¾ à¤¸à¥‡ à¤¨à¥€à¤šà¥‡ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ à¤¤à¥‹ à¤…à¤²à¤°à¥à¤Ÿ à¤­à¥‡à¤œà¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ",
  warningRule2:
    "à¤¬à¥ˆà¤²à¥‡à¤‚à¤¸ à¤…à¤²à¤°à¥à¤Ÿ à¤¬à¥€à¤œà¤¿à¤‚à¤— à¤¸à¤®à¤¯ à¤ªà¥à¤°à¤¤à¤¿à¤¦à¤¿à¤¨ à¤¸à¥à¤¬à¤¹ 10 à¤¬à¤œà¥‡ SMS à¤”à¤° à¤ˆà¤®à¥‡à¤² à¤¸à¥‡ à¤­à¥‡à¤œà¥‡ à¤œà¤¾à¤¤à¥‡ à¤¹à¥ˆà¤‚",
  warningRule3Before: "à¤ªà¤¹à¤²à¥‡ à¤‘à¤¨à¤²à¤¾à¤‡à¤¨ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤•à¥‡ à¤¬à¤¾à¤¦, à¤¬à¥ˆà¤²à¥‡à¤‚à¤¸ à¤…à¤²à¤°à¥à¤Ÿ ",
  warningRule3Bold: "à¤‘à¤Ÿà¥‹ à¤®à¥‹à¤¡",
  warningRule3After: " à¤®à¥‡à¤‚ à¤¸à¤•à¥à¤·à¤® à¤¹à¥‹à¤¤à¤¾ à¤¹à¥ˆ",
  warningThresholdLabel: "à¤…à¤²à¤°à¥à¤Ÿ à¤¸à¥€à¤®à¤¾:",
  warningAuto: "à¤‘à¤Ÿà¥‹",
  warningCustom: "à¤•à¤¸à¥à¤Ÿà¤®",
  warningOff: "à¤…à¤²à¤°à¥à¤Ÿ à¤¬à¤‚à¤¦ à¤•à¤°à¥‡à¤‚",
  warningYuan: "CNY",
  warningCancel: "à¤°à¤¦à¥à¤¦ à¤•à¤°à¥‡à¤‚",
  warningOk: "à¤ªà¥à¤·à¥à¤Ÿà¤¿ à¤•à¤°à¥‡à¤‚",
  payAmount: "à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤°à¤¾à¤¶à¤¿",
  payMethod: "à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤µà¤¿à¤§à¤¿",
  otherAmount: "à¤…à¤¨à¥à¤¯ à¤°à¤¾à¤¶à¤¿",
  alipay: "Alipay",
  otherPay: "à¤…à¤¨à¥à¤¯ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤µà¤¿à¤§à¤¿à¤¯à¤¾à¤",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¨ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¥à¤²à¤¿à¤• à¤•à¤°à¥‡à¤‚",
  captchaSuccess: "à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤",
  confirmPay: "à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤•à¥€ à¤ªà¥à¤·à¥à¤Ÿà¤¿ à¤•à¤°à¥‡à¤‚",
  paying: "à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤ªà¤° à¤°à¥€à¤¡à¤¾à¤¯à¤°à¥‡à¤•à¥à¤Ÿ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆâ€¦",
  payDisabled:
    "à¤‘à¤¨à¤²à¤¾à¤‡à¤¨ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤…à¤­à¥€ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆà¥¤ Backend à¤®à¥‡à¤‚ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤…à¤¨à¥à¤ªà¤¾à¤²à¤¨ à¤•à¥€ à¤ªà¥à¤·à¥à¤Ÿà¤¿ à¤”à¤° Epay (PayAddress / EpayId / EpayKey / PayMethods) à¤•à¥‰à¤¨à¥à¤«à¤¼à¤¿à¤—à¤° à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤µà¥à¤¯à¤µà¤¸à¥à¤¥à¤¾à¤ªà¤• à¤¸à¥‡ à¤•à¤¹à¥‡à¤‚à¥¤",
  payError: "à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤¶à¥à¤°à¥‚ à¤¨à¤¹à¥€à¤‚ à¤¹à¥‹ à¤¸à¤•à¤¾à¥¤ à¤¬à¤¾à¤¦ à¤®à¥‡à¤‚ à¤ªà¥à¤¨à¤ƒ à¤ªà¥à¤°à¤¯à¤¾à¤¸ à¤•à¤°à¥‡à¤‚à¥¤",
  agreePrefix:
    "à¤®à¥ˆà¤‚ à¤¸à¤®à¤à¤¤à¤¾/à¤¸à¤®à¤à¤¤à¥€ à¤¹à¥‚à¤ à¤•à¤¿ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤§à¤¨ à¤¸à¥€à¤§à¥‡ à¤šà¤¾à¤²à¤¾à¤¨ à¤¨à¤¹à¥€à¤‚ à¤•à¤¿à¤¯à¤¾ à¤œà¤¾ à¤¸à¤•à¤¤à¤¾à¥¤ à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤•à¥€ à¤ªà¥à¤·à¥à¤Ÿà¤¿ à¤•à¤°à¤•à¥‡, à¤®à¥ˆà¤‚ à¤ªà¥à¤²à¥‡à¤Ÿà¤«à¤¼à¥‰à¤°à¥à¤® à¤•à¥€ ",
  agreeLink: "à¤‰à¤ªà¤¯à¥‹à¤—à¤•à¤°à¥à¤¤à¤¾ à¤¸à¤®à¤à¥Œà¤¤à¥‡",
  recordsTitle: "à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤”à¤° à¤°à¤¿à¤«à¤‚à¤¡ à¤°à¤¿à¤•à¥‰à¤°à¥à¤¡",
  statusPending: "à¤­à¥à¤—à¤¤à¤¾à¤¨ à¤²à¤‚à¤¬à¤¿à¤¤",
  statusSuccess: "à¤ªà¥‚à¤°à¥à¤£",
  statusOther: "à¤¬à¤‚à¤¦",
  empty: "à¤•à¥‹à¤ˆ à¤¡à¥‡à¤Ÿà¤¾ à¤¨à¤¹à¥€à¤‚",
  segmentAll: "à¤¸à¤­à¥€",
  segmentAvailable: "à¤‰à¤ªà¤²à¤¬à¥à¤§",
  redeemCenter: "à¤°à¤¿à¤¡à¥‡à¤®à¥à¤ªà¤¶à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°",
  redeemInputLabel: "à¤°à¤¿à¤¡à¥‡à¤®à¥à¤ªà¤¶à¤¨ à¤•à¥‹à¤¡",
  redeemPlaceholder: "à¤µà¥à¤¯à¤µà¤¸à¥à¤¥à¤¾à¤ªà¤• à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤œà¤¾à¤°à¥€ à¤•à¥‹à¤¡ à¤¦à¤°à¥à¤œ à¤•à¤°à¥‡à¤‚",
  redeemSubmit: "à¤°à¤¿à¤¡à¥€à¤® à¤•à¤°à¥‡à¤‚",
  redeemSubmitting: "à¤°à¤¿à¤¡à¥€à¤® à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆâ€¦",
  redeemCancel: "à¤°à¤¦à¥à¤¦ à¤•à¤°à¥‡à¤‚",
  redeemSuccess: (n) => `à¤°à¤¿à¤¡à¥€à¤® à¤¸à¤«à¤²à¥¤ à¤•à¥‹à¤Ÿà¤¾ +${n}`,
  redeemFailed: "à¤°à¤¿à¤¡à¥€à¤® à¤µà¤¿à¤«à¤²à¥¤ à¤•à¥‹à¤¡ à¤µà¥ˆà¤§ à¤¹à¥ˆ à¤¯à¤¾ à¤¨à¤¹à¥€à¤‚ à¤œà¤¾à¤à¤šà¥‡à¤‚à¥¤",
  quotaLabel: "à¤•à¥‹à¤Ÿà¤¾",
  autoTitle: "Alipay à¤‘à¤Ÿà¥‹ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤¸à¤•à¥à¤·à¤® à¤•à¤°à¥‡à¤‚",
  autoAlerts: [
    "Alipay à¤¦à¥à¤µà¤¾à¤°à¤¾ à¤ªà¥à¤°à¤¦à¤¾à¤¨à¥¤ à¤¹à¤¸à¥à¤¤à¤¾à¤•à¥à¤·à¤° à¤•à¥‡ à¤¬à¤¾à¤¦, à¤œà¤¬ à¤†à¤ªà¤•à¤¾ à¤¶à¥‡à¤· à¤¸à¥€à¤®à¤¾ à¤¸à¥‡ à¤¨à¥€à¤šà¥‡ à¤œà¤¾à¤ à¤¤à¥‹ à¤ªà¥à¤²à¥‡à¤Ÿà¤«à¤¼à¥‰à¤°à¥à¤® à¤•à¥‹ à¤¸à¥à¤µà¤šà¤¾à¤²à¤¿à¤¤ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤•à¥€ à¤…à¤¨à¥à¤®à¤¤à¤¿ à¤¦à¥‡à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤ à¤•à¤­à¥€ à¤­à¥€ à¤°à¤¦à¥à¤¦ à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤",
    "à¤¹à¤¸à¥à¤¤à¤¾à¤•à¥à¤·à¤° à¤•à¥‡ à¤¬à¤¾à¤¦, à¤ªà¥à¤²à¥‡à¤Ÿà¤«à¤¼à¥‰à¤°à¥à¤® à¤¹à¤° 10 à¤®à¤¿à¤¨à¤Ÿ à¤®à¥‡à¤‚ à¤¶à¥‡à¤· à¤œà¤¾à¤à¤šà¤¤à¤¾ à¤¹à¥ˆà¥¤ à¤¡à¤¿à¤«à¤¼à¥‰à¤²à¥à¤Ÿ à¤°à¥‚à¤ª à¤¸à¥‡ à¤°à¤¾à¤¤ (22:00â€“08:00) à¤®à¥‡à¤‚ à¤¨à¤¹à¥€à¤‚ à¤šà¤²à¤¤à¤¾à¥¤ à¤¸à¤•à¥à¤·à¤® à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤¬à¤¾à¤¦ à¤¸à¤®à¤¾à¤¯à¥‹à¤œà¤¿à¤¤ à¤•à¤° à¤¸à¤•à¤¤à¥‡ à¤¹à¥ˆà¤‚à¥¤",
    "à¤‘à¤Ÿà¥‹ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤¸à¥‡ 10 à¤®à¤¿à¤¨à¤Ÿ à¤ªà¤¹à¤²à¥‡, à¤¸à¤¿à¤¸à¥à¤Ÿà¤® SMS à¤¸à¥‚à¤šà¤¨à¤¾ à¤­à¥‡à¤œà¤¤à¤¾ à¤¹à¥ˆà¥¤",
  ],
  thresholdLabel: "à¤¸à¥€à¤®à¤¾",
  rechargeAmountLabel: "à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤°à¤¾à¤¶à¤¿",
  otherAmountShort: "à¤…à¤¨à¥à¤¯ à¤°à¤¾à¤¶à¤¿",
  thresholdHint:
    "à¤œà¤¬ à¤¶à¥‡à¤· à¤¸à¥€à¤®à¤¾ à¤¸à¥‡ à¤¨à¥€à¤šà¥‡ à¤œà¤¾à¤ à¤¤à¥‹ à¤‘à¤Ÿà¥‹ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ à¤Ÿà¥à¤°à¤¿à¤—à¤° à¤¹à¥‹à¤¤à¤¾ à¤¹à¥ˆà¥¤ à¤¸à¥€à¤®à¤¾ Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "à¤¸à¥€à¤®à¤¾ à¤¸à¥‡ à¤…à¤§à¤¿à¤• à¤¹à¥‹à¤¨à¤¾ à¤šà¤¾à¤¹à¤¿à¤, à¤…à¤§à¤¿à¤•à¤¤à¤® Â¥ 2000; à¤¦à¥ˆà¤¨à¤¿à¤• à¤¸à¥€à¤®à¤¾ Â¥ 6,000, à¤®à¤¾à¤¸à¤¿à¤• Â¥ 100,000",
  autoPreview: (threshold, amount) =>
    `à¤œà¤¬ à¤¶à¥‡à¤· < Â¥ ${threshold}, à¤‘à¤Ÿà¥‹ à¤°à¤¿à¤šà¤¾à¤°à¥à¤œ Â¥ ${amount}`,
  signNow: "à¤…à¤­à¥€ à¤¹à¤¸à¥à¤¤à¤¾à¤•à¥à¤·à¤° à¤•à¤°à¥‡à¤‚",
});

const id = fromEn({
  pageTitle: "Isi ulang",
  recordHeaders: ["ID", "Waktu", "Saluran", "Status", "Jumlah", "Tindakan"],
  balanceLabel: "Saldo",
  overdraftSuffix: (n) => `(Kuota overdraft tersisa Â¥ ${n})`,
  couponLabel: "Voucher",
  couponSuffix: "tersedia",
  packageLabel: "Paket sumber daya",
  packageSuffix: "aktif",
  online: "Isi ulang online",
  auto: "Isi ulang otomatis",
  autoOff: "Belum diaktifkan",
  corporate: "Transfer bank",
  warningOn: "Peringatan saldo aktif (Pengaturan)",
  warningOffChip: "Peringatan saldo nonaktif (Pengaturan)",
  warningModalTitle: "Pengaturan peringatan saldo",
  warningRule1: "Peringatan saldo mendukung Otomatis, Kustom, dan Mati:",
  warningRule1a:
    "Dalam mode Otomatis, peringatan dikirim ketika kuota tersedia tersisa (saldo plus overdraft) turun di bawah konsumsi harian rata-rata saldo isi ulang dari panggilan API 7 hari terakhir",
  warningRule1b:
    "Dalam mode Kustom, peringatan dikirim ketika kuota tersedia tersisa (saldo plus overdraft) turun di bawah ambang batas Anda",
  warningRule2:
    "Peringatan saldo dikirim setiap hari pukul 10:00 waktu Beijing via SMS dan email",
  warningRule3Before: "Setelah isi ulang online pertama, peringatan saldo diaktifkan dalam ",
  warningRule3Bold: "mode Otomatis",
  warningRule3After: "",
  warningThresholdLabel: "Ambang peringatan:",
  warningAuto: "Otomatis",
  warningCustom: "Kustom",
  warningOff: "Matikan peringatan",
  warningYuan: "CNY",
  warningCancel: "Batal",
  warningOk: "Konfirmasi",
  payAmount: "Jumlah pembayaran",
  payMethod: "Metode pembayaran",
  otherAmount: "Jumlah lain",
  alipay: "Alipay",
  otherPay: "Metode pembayaran lain",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Klik untuk verifikasi",
  captchaSuccess: "Terverifikasi",
  confirmPay: "Konfirmasi pembayaran",
  paying: "Mengalihkan ke pembayaranâ€¦",
  payDisabled:
    "Isi ulang online belum tersedia. Minta admin mengonfirmasi kepatuhan pembayaran di Backend dan mengonfigurasi Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Gagal memulai pembayaran. Coba lagi nanti.",
  agreePrefix:
    "Saya memahami dana isi ulang tidak dapat difakturkan langsung. Dengan mengonfirmasi pembayaran, saya setuju dengan ",
  agreeLink: "Perjanjian Pengguna",
  recordsTitle: "Riwayat isi ulang dan refund",
  statusPending: "Menunggu pembayaran",
  statusSuccess: "Selesai",
  statusOther: "Ditutup",
  empty: "Tidak ada data",
  segmentAll: "Semua",
  segmentAvailable: "Tersedia",
  redeemCenter: "Pusat penukaran",
  redeemInputLabel: "Kode penukaran",
  redeemPlaceholder: "Masukkan kode yang diterbitkan administrator",
  redeemSubmit: "Tukar",
  redeemSubmitting: "Menukarâ€¦",
  redeemCancel: "Batal",
  redeemSuccess: (n) => `Penukaran berhasil. Kuota +${n}`,
  redeemFailed: "Penukaran gagal. Periksa apakah kode valid.",
  quotaLabel: "Kuota",
  autoTitle: "Aktifkan isi ulang otomatis Alipay",
  autoAlerts: [
    "Disediakan oleh Alipay. Setelah menandatangani, Anda mengizinkan platform mengisi ulang otomatis saat saldo di bawah ambang batas. Dapat dibatalkan kapan saja.",
    "Setelah menandatangani, platform memeriksa saldo setiap 10 menit. Secara default tidak dijalankan malam hari (22:00â€“08:00). Dapat disesuaikan setelah diaktifkan.",
    "Sepuluh menit sebelum isi ulang otomatis, sistem mengirim notifikasi SMS.",
  ],
  thresholdLabel: "Ambang batas",
  rechargeAmountLabel: "Jumlah isi ulang",
  otherAmountShort: "Jumlah lain",
  thresholdHint:
    "Isi ulang otomatis dipicu saat saldo di bawah ambang batas. Rentang Â¥ 5 ~ Â¥ 1000",
  amountHint:
    "Harus melebihi ambang batas, maks Â¥ 2000; batas harian Â¥ 6.000, bulanan Â¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Saat saldo < Â¥ ${threshold}, isi ulang otomatis Â¥ ${amount}`,
  signNow: "Tanda tangani sekarang",
});

export const WALLET_UI_COPY: Record<TargetLocale, WalletUiCopy> = {
  "zh-CN": zhCN,
  en,
  "zh-TW": zhTW,
  ja,
  fr,
  ru,
  vi,
  ko,
  de,
  es,
  "pt-BR": ptBR,
  ar,
  hi,
  id,
};

export function getWalletUiCopy(locale: string): WalletUiCopy {
  return pickTargetCatalog(locale, WALLET_UI_COPY);
}
