import { APP_ROUTES } from "@/lib/routes";
import type { TargetLocale } from "@/lib/locale";
import { pickTargetCatalog } from "@/lib/pick-catalog";

/** Wallet UI copy — online pay + redeem + top-up records only (no SiliconFlow voucher/auto shells). */
export type WalletUiCopy = {
  pageTitle: string;
  recordHeaders: [string, string, string, string, string];
  sectionStats: string;
  statQuota: string;
  statUsedQuota: string;
  statRequests: string;
  balanceLabel: string;
  payAmount: string;
  payMethod: string;
  otherAmount: string;
  alipay: string;
  wechatPay: string;
  wechatShort: string;
  confirmPay: string;
  paying: string;
  payDisabled: string;
  payError: string;
  quotingAmount: string;
  payableAmount: (formatted: string) => string;
  agreePrefix: string;
  agreeLink: string;
  agreeHref: string;
  recordsTitle: string;
  recordsLoadFailed: string;
  recordsKeywordPlaceholder: string;
  recordsSearch: string;
  recordsPrev: string;
  recordsNext: string;
  recordsPage: (page: number, totalPages: number) => string;
  recordsTotal: (total: number) => string;
  statusPending: string;
  statusSuccess: string;
  statusOther: string;
  empty: string;
  redeemCenter: string;
  redeemInputLabel: string;
  redeemPlaceholder: string;
  redeemSubmit: string;
  redeemSubmitting: string;
  redeemSuccess: (formattedDelta: string) => string;
  redeemFailed: string;
};

const zhCN: WalletUiCopy = {
  pageTitle: "钱包",
  recordHeaders: ["编号", "时间", "充值渠道", "状态", "金额"],
  sectionStats: "账户统计",
  statQuota: "当前余额",
  statUsedQuota: "历史消耗",
  statRequests: "请求次数",
  balanceLabel: "余额",
  payAmount: "支付金额",
  payMethod: "支付方式",
  otherAmount: "其它金额",
  alipay: "支付宝",
  wechatPay: "微信支付",
  wechatShort: "微信",
  confirmPay: "确认支付",
  paying: "跳转支付中…",
  payDisabled: "当前没有可用的在线充值通道。请管理员在 Backend 确认支付合规并启用对应支付网关。",
  payError: "拉起支付失败，请稍后重试",
  quotingAmount: "正在计算应付金额…",
  payableAmount: (formatted) => `应付金额：${formatted}`,
  agreePrefix: "我已知悉充值资金不支持直接开具发票，确认支付即代表同意本平台",
  agreeLink: "「用户协议」",
  recordsTitle: "充值退款记录",
  recordsKeywordPlaceholder: "搜索订单号",
  recordsSearch: "搜索",
  recordsPrev: "上一页",
  recordsNext: "下一页",
  recordsPage: (page, totalPages) => `${page} / ${totalPages}`,
  recordsTotal: (total) => `共 ${total} 条`,
  statusPending: "待支付",
  statusSuccess: "已完成",
  statusOther: "已关闭",
  empty: "暂无数据",
  redeemCenter: "兑换中心",
  redeemInputLabel: "兑换码",
  redeemPlaceholder: "请输入管理员发放的兑换码",
  redeemSubmit: "兑换",
  redeemSubmitting: "兑换中…",
  redeemFailed: "兑换失败，请检查兑换码是否有效",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "加载充值记录失败",
  redeemSuccess: (formattedDelta) => `兑换成功，额度 +${formattedDelta}`,
};

const en: WalletUiCopy = {
  pageTitle: "Wallet",
  recordHeaders: ["ID", "Time", "Channel", "Status", "Amount"],
  sectionStats: "Account stats",
  statQuota: "Balance",
  statUsedQuota: "Used quota",
  statRequests: "Requests",
  balanceLabel: "Balance",
  payAmount: "Payment amount",
  payMethod: "Payment method",
  otherAmount: "Other amount",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Confirm payment",
  paying: "Redirecting to payment…",
  payDisabled: "No online recharge gateways are available. Ask an admin to confirm payment compliance in Backend and enable the relevant payment gateways.",
  payError: "Failed to start payment. Please try again later.",
  quotingAmount: "Calculating amount due…",
  payableAmount: (formatted) => `Amount due: ${formatted}`,
  agreePrefix: "I understand that recharged funds cannot be invoiced directly. By confirming payment, I agree to the platform's ",
  agreeLink: "User Agreement",
  recordsTitle: "Recharge & refund records",
  recordsKeywordPlaceholder: "Search trade no.",
  recordsSearch: "Search",
  recordsPrev: "Prev",
  recordsNext: "Next",
  recordsPage: (page, totalPages) => `${page} / ${totalPages}`,
  recordsTotal: (total) => `${total} total`,
  statusPending: "Pending payment",
  statusSuccess: "Completed",
  statusOther: "Closed",
  empty: "No data",
  redeemCenter: "Redemption center",
  redeemInputLabel: "Redemption code",
  redeemPlaceholder: "Enter the code issued by an administrator",
  redeemSubmit: "Redeem",
  redeemSubmitting: "Redeeming…",
  redeemFailed: "Redemption failed. Check whether the code is valid.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Failed to load recharge records",
  redeemSuccess: (formattedDelta) => `Redeemed successfully. Quota +${formattedDelta}`,
};

const zhTW: WalletUiCopy = {
  pageTitle: "錢包",
  recordHeaders: ["編號", "時間", "儲值渠道", "狀態", "金額"],
  sectionStats: "帳戶統計",
  statQuota: "目前餘額",
  statUsedQuota: "歷史消耗",
  statRequests: "請求次數",
  balanceLabel: "餘額",
  payAmount: "支付金額",
  payMethod: "支付方式",
  otherAmount: "其它金額",
  alipay: "支付寶",
  wechatPay: "微信支付",
  wechatShort: "微信",
  confirmPay: "確認支付",
  paying: "跳轉支付中…",
  payDisabled: "目前沒有可用的線上儲值通道。請管理員在 Backend 確認支付合規並啟用對應支付閘道。",
  payError: "拉起支付失敗，請稍後重試",
  quotingAmount: "正在計算應付金額…",
  payableAmount: (formatted) => `應付金額：${formatted}`,
  agreePrefix: "我已知悉儲值資金不支持直接開具發票，確認支付即代表同意本平台",
  agreeLink: "「用戶協議」",
  recordsTitle: "儲值退款記錄",
  recordsKeywordPlaceholder: "搜尋訂單號",
  recordsSearch: "搜尋",
  recordsPrev: "上一頁",
  recordsNext: "下一頁",
  recordsPage: (page, totalPages) => `${page} / ${totalPages}`,
  recordsTotal: (total) => `共 ${total} 筆`,
  statusPending: "待支付",
  statusSuccess: "已完成",
  statusOther: "已關閉",
  empty: "暫無資料",
  redeemCenter: "兌換中心",
  redeemInputLabel: "兌換碼",
  redeemPlaceholder: "請輸入管理員發放的兌換碼",
  redeemSubmit: "兌換",
  redeemSubmitting: "兌換中…",
  redeemFailed: "兌換失敗，請檢查兌換碼是否有效",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "載入儲值記錄失敗",
  redeemSuccess: (formattedDelta) => `兌換成功，額度 +${formattedDelta}`,
};

function fromEn(partial: Partial<WalletUiCopy>): WalletUiCopy {
  return {
    ...en,
    ...partial,
    recordHeaders: partial.recordHeaders ?? en.recordHeaders,
    redeemSuccess: partial.redeemSuccess ?? en.redeemSuccess,
    payableAmount: partial.payableAmount ?? en.payableAmount,
    recordsPage: partial.recordsPage ?? en.recordsPage,
    recordsTotal: partial.recordsTotal ?? en.recordsTotal,
  };
}

const ja = fromEn({
  pageTitle: "ウォレット",
  recordHeaders: ["ID", "日時", "チャネル", "状態", "金額"],
  balanceLabel: "残高",
  payAmount: "支払い金額",
  payMethod: "支払い方法",
  otherAmount: "その他の金額",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "支払いを確認",
  paying: "支払いページへ移動中…",
  payDisabled: "オンラインチャージはまだ利用できません。管理者にBackendで決済コンプライアンスの確認と易支付（PayAddress / EpayId / EpayKey / PayMethods）の設定を依頼してください。",
  payError: "支払いの開始に失敗しました。後でもう一度お試しください。",
  agreePrefix: "チャージ資金は直接請求書を発行できないことを理解しました。支払いを確認することで、本プラットフォームの",
  agreeLink: "「利用規約」",
  recordsTitle: "チャージ・返金記録",
  statusPending: "支払い待ち",
  statusSuccess: "完了",
  statusOther: "クローズ",
  empty: "データなし",
  redeemCenter: "引き換えセンター",
  redeemInputLabel: "引き換えコード",
  redeemPlaceholder: "管理者から発行されたコードを入力",
  redeemSubmit: "引き換え",
  redeemSubmitting: "引き換え中…",
  redeemFailed: "引き換えに失敗しました。コードが有効か確認してください。",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "チャージ記録の読み込みに失敗しました",
  redeemSuccess: (formattedDelta) => `引き換え成功。利用枠 +${formattedDelta}`,
});

const fr = fromEn({
  pageTitle: "Recharger",
  recordHeaders: ["ID", "Date", "Canal", "Statut", "Montant"],
  balanceLabel: "Solde",
  payAmount: "Montant du paiement",
  payMethod: "Mode de paiement",
  otherAmount: "Autre montant",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Confirmer le paiement",
  paying: "Redirection vers le paiement…",
  payDisabled: "La recharge en ligne n'est pas encore disponible. Demandez à un administrateur de confirmer la conformité des paiements dans Backend et de configurer Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Échec du démarrage du paiement. Réessayez plus tard.",
  agreePrefix: "Je comprends que les fonds rechargés ne peuvent pas être facturés directement. En confirmant le paiement, j'accepte les ",
  agreeLink: "Conditions d'utilisation",
  recordsTitle: "Historique recharge et remboursement",
  statusPending: "Paiement en attente",
  statusSuccess: "Terminé",
  statusOther: "Fermé",
  empty: "Aucune donnée",
  redeemCenter: "Centre d'échange",
  redeemInputLabel: "Code d'échange",
  redeemPlaceholder: "Saisissez le code émis par un administrateur",
  redeemSubmit: "Échanger",
  redeemSubmitting: "Échange en cours…",
  redeemFailed: "Échange échoué. Vérifiez que le code est valide.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Échec du chargement de l'historique",
  redeemSuccess: (formattedDelta) => `Échange réussi. Quota +${formattedDelta}`,
});

const ru = fromEn({
  pageTitle: "Пополнение",
  recordHeaders: ["ID", "Время", "Канал", "Статус", "Сумма"],
  balanceLabel: "Баланс",
  payAmount: "Сумма платежа",
  payMethod: "Способ оплаты",
  otherAmount: "Другая сумма",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Подтвердить оплату",
  paying: "Переход к оплате…",
  payDisabled: "Онлайн-пополнение пока недоступно. Попросите администратора подтвердить соответствие платежей в Backend и настроить Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Не удалось начать оплату. Попробуйте позже.",
  agreePrefix: "Я понимаю, что пополненные средства нельзя напрямую выставить в счёт. Подтверждая оплату, я принимаю ",
  agreeLink: "Пользовательское соглашение",
  recordsTitle: "История пополнений и возвратов",
  statusPending: "Ожидает оплаты",
  statusSuccess: "Завершено",
  statusOther: "Закрыто",
  empty: "Нет данных",
  redeemCenter: "Центр активации",
  redeemInputLabel: "Код активации",
  redeemPlaceholder: "Введите код, выданный администратором",
  redeemSubmit: "Активировать",
  redeemSubmitting: "Активация…",
  redeemFailed: "Активация не удалась. Проверьте код.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Не удалось загрузить историю пополнений",
  redeemSuccess: (formattedDelta) => `Активация успешна. Квота +${formattedDelta}`,
});

const vi = fromEn({
  pageTitle: "Nạp tiền",
  recordHeaders: ["ID", "Thời gian", "Kênh", "Trạng thái", "Số tiền"],
  balanceLabel: "Số dư",
  payAmount: "Số tiền thanh toán",
  payMethod: "Phương thức thanh toán",
  otherAmount: "Số tiền khác",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Xác nhận thanh toán",
  paying: "Đang chuyển đến thanh toán…",
  payDisabled: "Nạp trực tuyến chưa khả dụng. Yêu cầu quản trị viên xác nhận tuân thủ thanh toán trong Backend và cấu hình Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Không thể bắt đầu thanh toán. Vui lòng thử lại sau.",
  agreePrefix: "Tôi hiểu rằng tiền nạp không thể xuất hóa đơn trực tiếp. Xác nhận thanh toán đồng nghĩa với việc đồng ý ",
  agreeLink: "Thỏa thuận người dùng",
  recordsTitle: "Lịch sử nạp và hoàn tiền",
  statusPending: "Chờ thanh toán",
  statusSuccess: "Hoàn tất",
  statusOther: "Đã đóng",
  empty: "Không có dữ liệu",
  redeemCenter: "Trung tâm đổi mã",
  redeemInputLabel: "Mã đổi",
  redeemPlaceholder: "Nhập mã do quản trị viên cấp",
  redeemSubmit: "Đổi",
  redeemSubmitting: "Đang đổi…",
  redeemFailed: "Đổi thất bại. Kiểm tra mã có hợp lệ không.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Không tải được lịch sử nạp",
  redeemSuccess: (formattedDelta) => `Đổi thành công. Hạn mức +${formattedDelta}`,
});

const ko = fromEn({
  pageTitle: "충전",
  recordHeaders: ["ID", "시간", "채널", "상태", "금액"],
  balanceLabel: "잔액",
  payAmount: "결제 금액",
  payMethod: "결제 수단",
  otherAmount: "기타 금액",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "결제 확인",
  paying: "결제 페이지로 이동 중…",
  payDisabled: "온라인 충전이 아직 제공되지 않습니다. 관리자에게 Backend에서 결제 규정 준수 확인 및 Epay(PayAddress / EpayId / EpayKey / PayMethods) 구성을 요청하세요.",
  payError: "결제를 시작하지 못했습니다. 나중에 다시 시도하세요.",
  agreePrefix: "충전 자금은 직접 세금계산서를 발행할 수 없음을 이해합니다. 결제 확인은 본 플랫폼 ",
  agreeLink: "「이용약관」",
  recordsTitle: "충전 및 환불 기록",
  statusPending: "결제 대기",
  statusSuccess: "완료",
  statusOther: "종료",
  empty: "데이터 없음",
  redeemCenter: "교환 센터",
  redeemInputLabel: "교환 코드",
  redeemPlaceholder: "관리자가 발급한 코드를 입력하세요",
  redeemSubmit: "교환",
  redeemSubmitting: "교환 중…",
  redeemFailed: "교환 실패. 코드가 유효한지 확인하세요.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "충전 기록을 불러오지 못했습니다",
  redeemSuccess: (formattedDelta) => `교환 성공. 한도 +${formattedDelta}`,
});

const de = fromEn({
  pageTitle: "Aufladen",
  recordHeaders: ["ID", "Zeit", "Kanal", "Status", "Betrag"],
  balanceLabel: "Guthaben",
  payAmount: "Zahlungsbetrag",
  payMethod: "Zahlungsmethode",
  otherAmount: "Anderer Betrag",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Zahlung bestätigen",
  paying: "Weiterleitung zur Zahlung…",
  payDisabled: "Online-Aufladung ist noch nicht verfügbar. Bitten Sie einen Admin, die Zahlungscompliance in Backend zu bestätigen und Epay zu konfigurieren (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Zahlung konnte nicht gestartet werden. Bitte später erneut versuchen.",
  agreePrefix: "Ich verstehe, dass aufgeladene Mittel nicht direkt in Rechnung gestellt werden können. Mit der Zahlungsbestätigung akzeptiere ich die ",
  agreeLink: "Nutzungsbedingungen",
  recordsTitle: "Auflade- und Rückerstattungsverlauf",
  statusPending: "Zahlung ausstehend",
  statusSuccess: "Abgeschlossen",
  statusOther: "Geschlossen",
  empty: "Keine Daten",
  redeemCenter: "Einlösezentrum",
  redeemInputLabel: "Einlösecode",
  redeemPlaceholder: "Vom Administrator ausgegebenen Code eingeben",
  redeemSubmit: "Einlösen",
  redeemSubmitting: "Einlösen…",
  redeemFailed: "Einlösung fehlgeschlagen. Prüfen Sie, ob der Code gültig ist.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Aufladeverlauf konnte nicht geladen werden",
  redeemSuccess: (formattedDelta) => `Einlösung erfolgreich. Kontingent +${formattedDelta}`,
});

const es = fromEn({
  pageTitle: "Recargar",
  recordHeaders: ["ID", "Hora", "Canal", "Estado", "Importe"],
  balanceLabel: "Saldo",
  payAmount: "Importe del pago",
  payMethod: "Método de pago",
  otherAmount: "Otro importe",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Confirmar pago",
  paying: "Redirigiendo al pago…",
  payDisabled: "La recarga en línea aún no está disponible. Pida a un administrador confirmar el cumplimiento de pagos en Backend y configurar Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "No se pudo iniciar el pago. Inténtelo más tarde.",
  agreePrefix: "Entiendo que los fondos recargados no pueden facturarse directamente. Al confirmar el pago, acepto el ",
  agreeLink: "Acuerdo de usuario",
  recordsTitle: "Historial de recargas y reembolsos",
  statusPending: "Pago pendiente",
  statusSuccess: "Completado",
  statusOther: "Cerrado",
  empty: "Sin datos",
  redeemCenter: "Centro de canje",
  redeemInputLabel: "Código de canje",
  redeemPlaceholder: "Introduzca el código emitido por un administrador",
  redeemSubmit: "Canjear",
  redeemSubmitting: "Canjeando…",
  redeemFailed: "Canje fallido. Compruebe si el código es válido.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "No se pudo cargar el historial de recargas",
  redeemSuccess: (formattedDelta) => `Canje exitoso. Cuota +${formattedDelta}`,
});

const ptBR = fromEn({
  pageTitle: "Recarga",
  recordHeaders: ["ID", "Hora", "Canal", "Status", "Valor"],
  balanceLabel: "Saldo",
  payAmount: "Valor do pagamento",
  payMethod: "Forma de pagamento",
  otherAmount: "Outro valor",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Confirmar pagamento",
  paying: "Redirecionando ao pagamento…",
  payDisabled: "Recarga online ainda não disponível. Peça a um administrador confirmar conformidade de pagamento no Backend e configurar Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Falha ao iniciar pagamento. Tente novamente mais tarde.",
  agreePrefix: "Entendo que fundos recarregados não podem ser faturados diretamente. Ao confirmar o pagamento, concordo com o ",
  agreeLink: "Acordo do usuário",
  recordsTitle: "Histórico de recargas e reembolsos",
  statusPending: "Pagamento pendente",
  statusSuccess: "Concluído",
  statusOther: "Fechado",
  empty: "Sem dados",
  redeemCenter: "Central de resgate",
  redeemInputLabel: "Código de resgate",
  redeemPlaceholder: "Digite o código emitido por um administrador",
  redeemSubmit: "Resgatar",
  redeemSubmitting: "Resgatando…",
  redeemFailed: "Resgate falhou. Verifique se o código é válido.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Falha ao carregar histórico de recargas",
  redeemSuccess: (formattedDelta) => `Resgate bem-sucedido. Cota +${formattedDelta}`,
});

const ar = fromEn({
  pageTitle: "شحن",
  recordHeaders: ["المعرّف", "الوقت", "القناة", "الحالة", "المبلغ"],
  balanceLabel: "الرصيد",
  payAmount: "مبلغ الدفع",
  payMethod: "طريقة الدفع",
  otherAmount: "مبلغ آخر",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "تأكيد الدفع",
  paying: "جارٍ التوجيه إلى الدفع…",
  payDisabled: "الشحن عبر الإنترنت غير متاح بعد. اطلب من المسؤول تأكيد امتثال الدفع في Backend وتكوين Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "تعذّر بدء الدفع. يرجى المحاولة لاحقًا.",
  agreePrefix: "أفهم أن أموال الشحن لا يمكن إصدار فاتورة لها مباشرة. بتأكيد الدفع، أوافق على ",
  agreeLink: "اتفاقية المستخدم",
  recordsTitle: "سجل الشحن والاسترداد",
  statusPending: "في انتظار الدفع",
  statusSuccess: "مكتمل",
  statusOther: "مغلق",
  empty: "لا توجد بيانات",
  redeemCenter: "مركز الاسترداد",
  redeemInputLabel: "رمز الاسترداد",
  redeemPlaceholder: "أدخل الرمز الصادر من المسؤول",
  redeemSubmit: "استرداد",
  redeemSubmitting: "جارٍ الاسترداد…",
  redeemFailed: "فشل الاسترداد. تحقق من صحة الرمز.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "فشل تحميل سجل الشحن",
  redeemSuccess: (formattedDelta) => `تم الاسترداد بنجاح. الحصة +${formattedDelta}`,
});

const hi = fromEn({
  pageTitle: "रिचार्ज",
  recordHeaders: ["ID", "समय", "चैनल", "स्थिति", "राशि"],
  balanceLabel: "शेष",
  payAmount: "भुगतान राशि",
  payMethod: "भुगतान विधि",
  otherAmount: "अन्य राशि",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "भुगतान की पुष्टि करें",
  paying: "भुगतान पर रीडायरेक्ट हो रहा है…",
  payDisabled: "ऑनलाइन रिचार्ज अभी उपलब्ध नहीं है। Backend में भुगतान अनुपालन की पुष्टि और Epay (PayAddress / EpayId / EpayKey / PayMethods) कॉन्फ़िगर करने के लिए व्यवस्थापक से कहें।",
  payError: "भुगतान शुरू नहीं हो सका। बाद में पुनः प्रयास करें।",
  agreePrefix: "मैं समझता/समझती हूँ कि रिचार्ज धन सीधे चालान नहीं किया जा सकता। भुगतान की पुष्टि करके, मैं प्लेटफ़ॉर्म की ",
  agreeLink: "उपयोगकर्ता समझौते",
  recordsTitle: "रिचार्ज और रिफंड रिकॉर्ड",
  statusPending: "भुगतान लंबित",
  statusSuccess: "पूर्ण",
  statusOther: "बंद",
  empty: "कोई डेटा नहीं",
  redeemCenter: "रिडेम्पशन केंद्र",
  redeemInputLabel: "रिडेम्पशन कोड",
  redeemPlaceholder: "व्यवस्थापक द्वारा जारी कोड दर्ज करें",
  redeemSubmit: "रिडीम करें",
  redeemSubmitting: "रिडीम हो रहा है…",
  redeemFailed: "रिडीम विफल। कोड वैध है या नहीं जाँचें।",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "रिचार्ज रिकॉर्ड लोड करने में विफल",
  redeemSuccess: (formattedDelta) => `रिडीम सफल। कोटा +${formattedDelta}`,
});

const id = fromEn({
  pageTitle: "Isi ulang",
  recordHeaders: ["ID", "Waktu", "Saluran", "Status", "Jumlah"],
  balanceLabel: "Saldo",
  payAmount: "Jumlah pembayaran",
  payMethod: "Metode pembayaran",
  otherAmount: "Jumlah lain",
  alipay: "Alipay",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  confirmPay: "Konfirmasi pembayaran",
  paying: "Mengalihkan ke pembayaran…",
  payDisabled: "Isi ulang online belum tersedia. Minta admin mengonfirmasi kepatuhan pembayaran di Backend dan mengonfigurasi Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Gagal memulai pembayaran. Coba lagi nanti.",
  agreePrefix: "Saya memahami dana isi ulang tidak dapat difakturkan langsung. Dengan mengonfirmasi pembayaran, saya setuju dengan ",
  agreeLink: "Perjanjian Pengguna",
  recordsTitle: "Riwayat isi ulang dan refund",
  statusPending: "Menunggu pembayaran",
  statusSuccess: "Selesai",
  statusOther: "Ditutup",
  empty: "Tidak ada data",
  redeemCenter: "Pusat penukaran",
  redeemInputLabel: "Kode penukaran",
  redeemPlaceholder: "Masukkan kode yang diterbitkan administrator",
  redeemSubmit: "Tukar",
  redeemSubmitting: "Menukar…",
  redeemFailed: "Penukaran gagal. Periksa apakah kode valid.",
  agreeHref: APP_ROUTES.userAgreement,
  recordsLoadFailed: "Gagal memuat riwayat isi ulang",
  redeemSuccess: (formattedDelta) => `Penukaran berhasil. Kuota +${formattedDelta}`,
});

const WALLET_UI_COPY: Record<TargetLocale, WalletUiCopy> = {
  "zh-CN": zhCN,
  en,
  "zh-TW": zhTW,
  ja,
  fr,
  ru,
  vi,
  ko,
  de,
  es,
  "pt-BR": ptBR,
  ar,
  hi,
  id,
};

export function getWalletUiCopy(locale: string): WalletUiCopy {
  return pickTargetCatalog(locale, WALLET_UI_COPY);
}
