import { APP_ROUTES } from "@/lib/routes";
import type { TargetLocale } from "@/lib/locale";
import { pickTargetCatalog } from "@/lib/pick-catalog";

export type ExpenseBillUiCopy = {
  pageTitle: string;
  recordHeaders: [string, string, string, string, string, string];
  balanceLabel: string;
  overdraftSuffix: (n: number) => string;
  couponLabel: string;
  couponSuffix: string;
  packageLabel: string;
  packageSuffix: string;
  online: string;
  auto: string;
  autoOff: string;
  corporate: string;
  warningOn: string;
  warningOffChip: string;
  warningModalTitle: string;
  warningRule1: string;
  warningRule1a: string;
  warningRule1b: string;
  warningRule2: string;
  warningRule3Before: string;
  warningRule3Bold: string;
  warningRule3After: string;
  warningThresholdLabel: string;
  warningAuto: string;
  warningCustom: string;
  warningOff: string;
  warningYuan: string;
  warningCancel: string;
  warningOk: string;
  payAmount: string;
  payMethod: string;
  otherAmount: string;
  alipay: string;
  otherPay: string;
  wechatPay: string;
  wechatShort: string;
  captcha: string;
  captchaSuccess: string;
  confirmPay: string;
  paying: string;
  payDisabled: string;
  payError: string;
  agreePrefix: string;
  agreeLink: string;
  agreeHref: string;
  recordsTitle: string;
  statusPending: string;
  statusSuccess: string;
  statusOther: string;
  empty: string;
  segmentAll: string;
  segmentAvailable: string;
  redeemCenter: string;
  redeemInputLabel: string;
  redeemPlaceholder: string;
  redeemSubmit: string;
  redeemSubmitting: string;
  redeemCancel: string;
  redeemSuccess: (n: number) => string;
  redeemFailed: string;
  quotaLabel: string;
  autoTitle: string;
  autoAlerts: [string, string, string];
  thresholdLabel: string;
  rechargeAmountLabel: string;
  otherAmountShort: string;
  thresholdHint: string;
  amountHint: string;
  autoPreview: (threshold: number, amount: number) => string;
  signNow: string;
};

const zhCN: ExpenseBillUiCopy = {
  pageTitle: "钱包",
  recordHeaders: ["编号", "时间", "充值渠道", "状态", "金额", "操作"],
  balanceLabel: "余额",
  overdraftSuffix: (n) => `（剩余可透支额度 ¥ ${n}）`,
  couponLabel: "代金券",
  couponSuffix: "张可用",
  packageLabel: "资源包",
  packageSuffix: "个生效中",
  online: "在线充值",
  auto: "自动充值",
  autoOff: "未开启",
  corporate: "对公转账汇款",
  warningOn: "余额预警已开启 (去设置)",
  warningOffChip: "余额预警已关闭 (去设置)",
  warningModalTitle: "余额预警设置",
  warningRule1: "余额预警包括自动、自定义、关闭三种模式：",
  warningRule1a:
    "若设置为自动，当账户剩余可用额度（包括充值余额和透支额度）低于近 7 日 API 调用产生的充值余额平均日消费时自动预警",
  warningRule1b:
    "若设置为自定义，当账户剩余可用额度（包括充值余额和透支额度）低于设置阈值时自动预警",
  warningRule2: "余额预警将在北京时间每天上午 10 点发送预警短信及邮件通知",
  warningRule3Before: "首次完成在线充值时，系统按",
  warningRule3Bold: "自动模式",
  warningRule3After: "开启余额预警",
  warningThresholdLabel: "预警阈值：",
  warningAuto: "自动",
  warningCustom: "自定义",
  warningOff: "关闭预警",
  warningYuan: "元",
  warningCancel: "取 消",
  warningOk: "确 定",
  payAmount: "支付金额",
  payMethod: "支付方式",
  otherAmount: "其它金额",
  alipay: "支付宝",
  otherPay: "其他支付方式",
  wechatPay: "微信支付",
  wechatShort: "微信",
  captcha: "点击完成验证",
  captchaSuccess: "验证成功",
  confirmPay: "确认支付",
  paying: "跳转支付中…",
  payDisabled:
    "在线充值暂未开通。请管理员在 Backend 确认支付合规并配置易支付（PayAddress / EpayId / EpayKey / PayMethods）。",
  payError: "拉起支付失败，请稍后重试",
  agreePrefix: "我已知悉充值资金不支持直接开具发票，确认支付即代表同意本平台",
  agreeLink: "「用户协议」",
  agreeHref: APP_ROUTES.userAgreement,
  recordsTitle: "充值退款记录",
  statusPending: "待支付",
  statusSuccess: "已完成",
  statusOther: "已关闭",
  empty: "暂无数据",
  segmentAll: "全部",
  segmentAvailable: "可用",
  redeemCenter: "兑换中心",
  redeemInputLabel: "兑换码",
  redeemPlaceholder: "请输入管理员发放的兑换码",
  redeemSubmit: "兑换",
  redeemSubmitting: "兑换中…",
  redeemCancel: "取消",
  redeemSuccess: (n) => `兑换成功，额度 +${n}`,
  redeemFailed: "兑换失败，请检查兑换码是否有效",
  quotaLabel: "额度",
  autoTitle: "开通支付宝自动充值",
  autoAlerts: [
    "该功能由支付宝提供，签约后授权平台在用户余额低于设定阈值时自动充值，可随时取消",
    "签约后平台每 10 分钟检测一次余额，默认不在夜间（22:00 ~ 次日 08:00）执行（开通后可调整）",
    "自动充值执行前 10 分钟，系统将向您发送短信通知",
  ],
  thresholdLabel: "设定阈值",
  rechargeAmountLabel: "充值金额",
  otherAmountShort: "其他金额",
  thresholdHint: "当余额低于阈值时自动触发充值，范围 ¥ 5 ~ ¥ 1000",
  amountHint: "必须大于设定阈值，上限 ¥ 2000；每日累计 ¥ 6,000，每月累计 ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `余额 < ¥ ${threshold} 时，自动充值 ¥ ${amount}`,
  signNow: "立即签约",
};

const en: ExpenseBillUiCopy = {
  pageTitle: "Wallet",
  recordHeaders: ["ID", "Time", "Channel", "Status", "Amount", "Actions"],
  balanceLabel: "Balance",
  overdraftSuffix: (n) => `(Remaining overdraft quota ¥ ${n})`,
  couponLabel: "Vouchers",
  couponSuffix: "available",
  packageLabel: "Resource packs",
  packageSuffix: "active",
  online: "Online recharge",
  auto: "Auto recharge",
  autoOff: "Not enabled",
  corporate: "Bank transfer",
  warningOn: "Balance alert enabled (Settings)",
  warningOffChip: "Balance alert disabled (Settings)",
  warningModalTitle: "Balance alert settings",
  warningRule1: "Balance alerts support Auto, Custom, and Off:",
  warningRule1a:
    "In Auto mode, an alert is sent when remaining available quota (balance plus overdraft) falls below your average daily balance consumption from API calls over the last 7 days",
  warningRule1b:
    "In Custom mode, an alert is sent when remaining available quota (balance plus overdraft) falls below your threshold",
  warningRule2:
    "Balance alerts are sent daily at 10:00 AM Beijing time via SMS and email",
  warningRule3Before: "After your first online recharge, balance alerts are enabled in ",
  warningRule3Bold: "Auto mode",
  warningRule3After: "",
  warningThresholdLabel: "Alert threshold:",
  warningAuto: "Auto",
  warningCustom: "Custom",
  warningOff: "Turn off alerts",
  warningYuan: "CNY",
  warningCancel: "Cancel",
  warningOk: "Confirm",
  payAmount: "Payment amount",
  payMethod: "Payment method",
  otherAmount: "Other amount",
  alipay: "Alipay",
  otherPay: "Other payment methods",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Click to verify",
  captchaSuccess: "Verified",
  confirmPay: "Confirm payment",
  paying: "Redirecting to payment…",
  payDisabled:
    "Online recharge is not available yet. Ask an admin to confirm payment compliance in Backend and configure Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Failed to start payment. Please try again later.",
  agreePrefix:
    "I understand that recharged funds cannot be invoiced directly. By confirming payment, I agree to the platform's ",
  agreeLink: "User Agreement",
  agreeHref: APP_ROUTES.userAgreement,
  recordsTitle: "Recharge & refund records",
  statusPending: "Pending payment",
  statusSuccess: "Completed",
  statusOther: "Closed",
  empty: "No data",
  segmentAll: "All",
  segmentAvailable: "Available",
  redeemCenter: "Redemption center",
  redeemInputLabel: "Redemption code",
  redeemPlaceholder: "Enter the code issued by an administrator",
  redeemSubmit: "Redeem",
  redeemSubmitting: "Redeeming…",
  redeemCancel: "Cancel",
  redeemSuccess: (n) => `Redeemed successfully. Quota +${n}`,
  redeemFailed: "Redemption failed. Check whether the code is valid.",
  quotaLabel: "Quota",
  autoTitle: "Enable Alipay auto recharge",
  autoAlerts: [
    "Provided by Alipay. After signing, you authorize the platform to recharge automatically when your balance falls below the threshold. You can cancel anytime.",
    "After signing, the platform checks your balance every 10 minutes. By default, recharges do not run overnight (22:00–08:00). You can adjust this after enabling.",
    "Ten minutes before an auto recharge, the system sends you an SMS notification.",
  ],
  thresholdLabel: "Threshold",
  rechargeAmountLabel: "Recharge amount",
  otherAmountShort: "Other amount",
  thresholdHint:
    "Auto recharge triggers when balance falls below the threshold. Range ¥ 5 ~ ¥ 1000",
  amountHint:
    "Must exceed the threshold, up to ¥ 2000; daily cap ¥ 6,000, monthly cap ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `When balance < ¥ ${threshold}, auto recharge ¥ ${amount}`,
  signNow: "Sign now",
};

const zhTW: ExpenseBillUiCopy = {
  ...zhCN,
  pageTitle: "錢包",
  recordHeaders: ["編號", "時間", "儲值渠道", "狀態", "金額", "操作"],
  balanceLabel: "餘額",
  overdraftSuffix: (n) => `（剩餘可透支額度 ¥ ${n}）`,
  couponLabel: "代金券",
  couponSuffix: "張可用",
  packageLabel: "資源包",
  packageSuffix: "個生效中",
  online: "線上儲值",
  auto: "自動儲值",
  autoOff: "未開啟",
  corporate: "對公轉帳匯款",
  warningOn: "餘額預警已開啟 (去設定)",
  warningOffChip: "餘額預警已關閉 (去設定)",
  warningModalTitle: "餘額預警設定",
  warningRule1: "餘額預警包括自動、自訂、關閉三種模式：",
  warningRule1a:
    "若設定為自動，當帳戶剩餘可用額度（包括儲值餘額和透支額度）低於近 7 日 API 呼叫產生的儲值餘額平均日消費時自動預警",
  warningRule1b:
    "若設定為自訂，當帳戶剩餘可用額度（包括儲值餘額和透支額度）低於設定閾值時自動預警",
  warningRule2: "餘額預警將在北京時間每天上午 10 點發送預警簡訊及郵件通知",
  warningRule3Before: "首次完成線上儲值時，系統按",
  warningRule3Bold: "自動模式",
  warningRule3After: "開啟餘額預警",
  warningThresholdLabel: "預警閾值：",
  warningAuto: "自動",
  warningCustom: "自訂",
  warningOff: "關閉預警",
  warningYuan: "元",
  warningCancel: "取 消",
  warningOk: "確 定",
  payAmount: "支付金額",
  payMethod: "支付方式",
  otherAmount: "其它金額",
  alipay: "支付寶",
  otherPay: "其他支付方式",
  wechatPay: "微信支付",
  wechatShort: "微信",
  captcha: "點擊完成驗證",
  captchaSuccess: "驗證成功",
  confirmPay: "確認支付",
  paying: "跳轉支付中…",
  payDisabled:
    "線上儲值暫未開通。請管理員在 Backend 確認支付合規並配置易支付（PayAddress / EpayId / EpayKey / PayMethods）。",
  payError: "拉起支付失敗，請稍後重試",
  agreePrefix: "我已知悉儲值資金不支持直接開具發票，確認支付即代表同意本平台",
  agreeLink: "「用戶協議」",
  recordsTitle: "儲值退款記錄",
  statusPending: "待支付",
  statusSuccess: "已完成",
  statusOther: "已關閉",
  empty: "暫無資料",
  segmentAll: "全部",
  segmentAvailable: "可用",
  redeemCenter: "兌換中心",
  redeemInputLabel: "兌換碼",
  redeemPlaceholder: "請輸入管理員發放的兌換碼",
  redeemSubmit: "兌換",
  redeemSubmitting: "兌換中…",
  redeemCancel: "取消",
  redeemSuccess: (n) => `兌換成功，額度 +${n}`,
  redeemFailed: "兌換失敗，請檢查兌換碼是否有效",
  quotaLabel: "額度",
  autoTitle: "開通支付寶自動儲值",
  autoAlerts: [
    "該功能由支付寶提供，簽約後授權平台在用戶餘額低於設定閾值時自動儲值，可隨時取消",
    "簽約後平台每 10 分鐘檢測一次餘額，預設不在夜間（22:00 ~ 次日 08:00）執行（開通後可調整）",
    "自動儲值執行前 10 分鐘，系統將向您發送簡訊通知",
  ],
  thresholdLabel: "設定閾值",
  rechargeAmountLabel: "儲值金額",
  otherAmountShort: "其他金額",
  thresholdHint: "當餘額低於閾值時自動觸發儲值，範圍 ¥ 5 ~ ¥ 1000",
  amountHint: "必須大於設定閾值，上限 ¥ 2000；每日累計 ¥ 6,000，每月累計 ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `餘額 < ¥ ${threshold} 時，自動儲值 ¥ ${amount}`,
  signNow: "立即簽約",
};

function fromEn(
  partial: Partial<
    Omit<ExpenseBillUiCopy, "overdraftSuffix" | "redeemSuccess" | "autoPreview">
  > & {
    overdraftSuffix?: ExpenseBillUiCopy["overdraftSuffix"];
    redeemSuccess?: ExpenseBillUiCopy["redeemSuccess"];
    autoPreview?: ExpenseBillUiCopy["autoPreview"];
  },
): ExpenseBillUiCopy {
  return {
    ...en,
    ...partial,
    recordHeaders: partial.recordHeaders ?? en.recordHeaders,
    autoAlerts: partial.autoAlerts ?? en.autoAlerts,
    overdraftSuffix: partial.overdraftSuffix ?? en.overdraftSuffix,
    redeemSuccess: partial.redeemSuccess ?? en.redeemSuccess,
    autoPreview: partial.autoPreview ?? en.autoPreview,
  };
}

const ja = fromEn({
  pageTitle: "ウォレット",
  recordHeaders: ["ID", "日時", "チャネル", "状態", "金額", "操作"],
  balanceLabel: "残高",
  overdraftSuffix: (n) => `（残りの透支枠 ¥ ${n}）`,
  couponLabel: "クーポン",
  couponSuffix: "枚利用可能",
  packageLabel: "リソースパック",
  packageSuffix: "件有効",
  online: "オンラインチャージ",
  auto: "自動チャージ",
  autoOff: "未設定",
  corporate: "法人振込",
  warningOn: "残高アラート有効（設定へ）",
  warningOffChip: "残高アラート無効（設定へ）",
  warningModalTitle: "残高アラート設定",
  warningRule1: "残高アラートには自動・カスタム・オフの3モードがあります：",
  warningRule1a:
    "自動の場合、残り利用可能枠（チャージ残高と透支枠を含む）が過去7日間のAPI呼び出しによるチャージ残高の平均日次消費を下回ると自動でアラート",
  warningRule1b:
    "カスタムの場合、残り利用可能枠（チャージ残高と透支枠を含む）が設定した閾値を下回ると自動でアラート",
  warningRule2:
    "残高アラートは北京時間の毎日午前10時にSMSとメールで送信されます",
  warningRule3Before: "初回のオンラインチャージ完了後、システムは",
  warningRule3Bold: "自動モード",
  warningRule3After: "で残高アラートを有効にします",
  warningThresholdLabel: "アラート閾値：",
  warningAuto: "自動",
  warningCustom: "カスタム",
  warningOff: "アラートをオフ",
  warningYuan: "元",
  warningCancel: "キャンセル",
  warningOk: "確定",
  payAmount: "支払い金額",
  payMethod: "支払い方法",
  otherAmount: "その他の金額",
  alipay: "Alipay",
  otherPay: "その他の支払い方法",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "クリックして認証",
  captchaSuccess: "認証成功",
  confirmPay: "支払いを確認",
  paying: "支払いページへ移動中…",
  payDisabled:
    "オンラインチャージはまだ利用できません。管理者にBackendで決済コンプライアンスの確認と易支付（PayAddress / EpayId / EpayKey / PayMethods）の設定を依頼してください。",
  payError: "支払いの開始に失敗しました。後でもう一度お試しください。",
  agreePrefix:
    "チャージ資金は直接請求書を発行できないことを理解しました。支払いを確認することで、本プラットフォームの",
  agreeLink: "「利用規約」",
  recordsTitle: "チャージ・返金記録",
  statusPending: "支払い待ち",
  statusSuccess: "完了",
  statusOther: "クローズ",
  empty: "データなし",
  segmentAll: "すべて",
  segmentAvailable: "利用可能",
  redeemCenter: "引き換えセンター",
  redeemInputLabel: "引き換えコード",
  redeemPlaceholder: "管理者から発行されたコードを入力",
  redeemSubmit: "引き換え",
  redeemSubmitting: "引き換え中…",
  redeemCancel: "キャンセル",
  redeemSuccess: (n) => `引き換え成功。利用枠 +${n}`,
  redeemFailed: "引き換えに失敗しました。コードが有効か確認してください。",
  quotaLabel: "利用枠",
  autoTitle: "Alipay 自動チャージを有効化",
  autoAlerts: [
    "この機能はAlipayが提供します。契約後、残高が設定した閾値を下回ると自動チャージを許可します。いつでも解約できます。",
    "契約後、プラットフォームは10分ごとに残高を確認します。デフォルトでは夜間（22:00～翌08:00）は実行されません（有効化後に調整可能）。",
    "自動チャージの10分前に、システムからSMS通知が送信されます。",
  ],
  thresholdLabel: "閾値設定",
  rechargeAmountLabel: "チャージ金額",
  otherAmountShort: "その他の金額",
  thresholdHint: "残高が閾値を下回ると自動チャージが実行されます。範囲 ¥ 5 ~ ¥ 1000",
  amountHint: "閾値より大きく、上限 ¥ 2000。日次累計 ¥ 6,000、月次累計 ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `残高 < ¥ ${threshold} のとき、自動チャージ ¥ ${amount}`,
  signNow: "今すぐ契約",
});

const fr = fromEn({
  pageTitle: "Recharger",
  recordHeaders: ["ID", "Date", "Canal", "Statut", "Montant", "Actions"],
  balanceLabel: "Solde",
  overdraftSuffix: (n) => `(Quota de découvert restant ¥ ${n})`,
  couponLabel: "Bons",
  couponSuffix: "disponibles",
  packageLabel: "Packs de ressources",
  packageSuffix: "actifs",
  online: "Recharge en ligne",
  auto: "Recharge automatique",
  autoOff: "Non activée",
  corporate: "Virement bancaire",
  warningOn: "Alerte solde activée (Paramètres)",
  warningOffChip: "Alerte solde désactivée (Paramètres)",
  warningModalTitle: "Paramètres d'alerte solde",
  warningRule1: "Les alertes solde proposent Auto, Personnalisé et Désactivé :",
  warningRule1a:
    "En mode Auto, une alerte est envoyée lorsque le quota disponible restant (solde plus découvert) tombe sous la consommation quotidienne moyenne du solde de recharge sur les 7 derniers jours d'appels API",
  warningRule1b:
    "En mode Personnalisé, une alerte est envoyée lorsque le quota disponible restant (solde plus découvert) tombe sous votre seuil",
  warningRule2:
    "Les alertes solde sont envoyées chaque jour à 10 h (heure de Pékin) par SMS et e-mail",
  warningRule3Before: "Après votre première recharge en ligne, les alertes solde sont activées en ",
  warningRule3Bold: "mode Auto",
  warningRule3After: "",
  warningThresholdLabel: "Seuil d'alerte :",
  warningAuto: "Auto",
  warningCustom: "Personnalisé",
  warningOff: "Désactiver les alertes",
  warningYuan: "CNY",
  warningCancel: "Annuler",
  warningOk: "Confirmer",
  payAmount: "Montant du paiement",
  payMethod: "Mode de paiement",
  otherAmount: "Autre montant",
  alipay: "Alipay",
  otherPay: "Autres modes de paiement",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Cliquer pour vérifier",
  captchaSuccess: "Vérifié",
  confirmPay: "Confirmer le paiement",
  paying: "Redirection vers le paiement…",
  payDisabled:
    "La recharge en ligne n'est pas encore disponible. Demandez à un administrateur de confirmer la conformité des paiements dans Backend et de configurer Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Échec du démarrage du paiement. Réessayez plus tard.",
  agreePrefix:
    "Je comprends que les fonds rechargés ne peuvent pas être facturés directement. En confirmant le paiement, j'accepte les ",
  agreeLink: "Conditions d'utilisation",
  recordsTitle: "Historique recharge et remboursement",
  statusPending: "Paiement en attente",
  statusSuccess: "Terminé",
  statusOther: "Fermé",
  empty: "Aucune donnée",
  segmentAll: "Tout",
  segmentAvailable: "Disponible",
  redeemCenter: "Centre d'échange",
  redeemInputLabel: "Code d'échange",
  redeemPlaceholder: "Saisissez le code émis par un administrateur",
  redeemSubmit: "Échanger",
  redeemSubmitting: "Échange en cours…",
  redeemCancel: "Annuler",
  redeemSuccess: (n) => `Échange réussi. Quota +${n}`,
  redeemFailed: "Échange échoué. Vérifiez que le code est valide.",
  quotaLabel: "Quota",
  autoTitle: "Activer la recharge auto Alipay",
  autoAlerts: [
    "Fourni par Alipay. Après signature, vous autorisez la plateforme à recharger automatiquement lorsque votre solde descend sous le seuil. Annulable à tout moment.",
    "Après signature, la plateforme vérifie le solde toutes les 10 minutes. Par défaut, pas de recharge la nuit (22:00–08:00). Ajustable après activation.",
    "Dix minutes avant une recharge auto, le système vous envoie un SMS.",
  ],
  thresholdLabel: "Seuil",
  rechargeAmountLabel: "Montant de recharge",
  otherAmountShort: "Autre montant",
  thresholdHint:
    "La recharge auto se déclenche lorsque le solde descend sous le seuil. Plage ¥ 5 ~ ¥ 1000",
  amountHint:
    "Doit dépasser le seuil, max ¥ 2000 ; plafond quotidien ¥ 6 000, mensuel ¥ 100 000",
  autoPreview: (threshold, amount) =>
    `Quand solde < ¥ ${threshold}, recharge auto ¥ ${amount}`,
  signNow: "Signer maintenant",
});

const ru = fromEn({
  pageTitle: "Пополнение",
  recordHeaders: ["ID", "Время", "Канал", "Статус", "Сумма", "Действия"],
  balanceLabel: "Баланс",
  overdraftSuffix: (n) => `(Оставшаяся квота овердрафта ¥ ${n})`,
  couponLabel: "Купоны",
  couponSuffix: "доступно",
  packageLabel: "Пакеты ресурсов",
  packageSuffix: "активно",
  online: "Онлайн-пополнение",
  auto: "Автопополнение",
  autoOff: "Не включено",
  corporate: "Банковский перевод",
  warningOn: "Оповещение о балансе включено (Настройки)",
  warningOffChip: "Оповещение о балансе выключено (Настройки)",
  warningModalTitle: "Настройки оповещения о балансе",
  warningRule1: "Оповещения о балансе: Авто, Пользовательский и Выкл.:",
  warningRule1a:
    "В режиме Авто оповещение отправляется, когда оставшаяся доступная квота (баланс плюс овердрафт) ниже среднего дневного расхода баланса пополнения за последние 7 дней вызовов API",
  warningRule1b:
    "В пользовательском режиме оповещение отправляется, когда оставшаяся доступная квота (баланс плюс овердрафт) ниже вашего порога",
  warningRule2:
    "Оповещения о балансе отправляются ежедневно в 10:00 по пекинскому времени по SMS и e-mail",
  warningRule3Before: "После первого онлайн-пополнения оповещения о балансе включаются в ",
  warningRule3Bold: "режиме Авто",
  warningRule3After: "",
  warningThresholdLabel: "Порог оповещения:",
  warningAuto: "Авто",
  warningCustom: "Пользовательский",
  warningOff: "Отключить оповещения",
  warningYuan: "CNY",
  warningCancel: "Отмена",
  warningOk: "Подтвердить",
  payAmount: "Сумма платежа",
  payMethod: "Способ оплаты",
  otherAmount: "Другая сумма",
  alipay: "Alipay",
  otherPay: "Другие способы оплаты",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Нажмите для проверки",
  captchaSuccess: "Проверено",
  confirmPay: "Подтвердить оплату",
  paying: "Переход к оплате…",
  payDisabled:
    "Онлайн-пополнение пока недоступно. Попросите администратора подтвердить соответствие платежей в Backend и настроить Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Не удалось начать оплату. Попробуйте позже.",
  agreePrefix:
    "Я понимаю, что пополненные средства нельзя напрямую выставить в счёт. Подтверждая оплату, я принимаю ",
  agreeLink: "Пользовательское соглашение",
  recordsTitle: "История пополнений и возвратов",
  statusPending: "Ожидает оплаты",
  statusSuccess: "Завершено",
  statusOther: "Закрыто",
  empty: "Нет данных",
  segmentAll: "Все",
  segmentAvailable: "Доступные",
  redeemCenter: "Центр активации",
  redeemInputLabel: "Код активации",
  redeemPlaceholder: "Введите код, выданный администратором",
  redeemSubmit: "Активировать",
  redeemSubmitting: "Активация…",
  redeemCancel: "Отмена",
  redeemSuccess: (n) => `Активация успешна. Квота +${n}`,
  redeemFailed: "Активация не удалась. Проверьте код.",
  quotaLabel: "Квота",
  autoTitle: "Включить автопополнение Alipay",
  autoAlerts: [
    "Предоставляется Alipay. После подписания вы разрешаете платформе автоматически пополнять баланс при падении ниже порога. Можно отменить в любое время.",
    "После подписания платформа проверяет баланс каждые 10 минут. По умолчанию ночью (22:00–08:00) не выполняется. Можно настроить после включения.",
    "За 10 минут до автопополнения система отправит SMS.",
  ],
  thresholdLabel: "Порог",
  rechargeAmountLabel: "Сумма пополнения",
  otherAmountShort: "Другая сумма",
  thresholdHint:
    "Автопополнение срабатывает, когда баланс ниже порога. Диапазон ¥ 5 ~ ¥ 1000",
  amountHint:
    "Должно превышать порог, макс. ¥ 2000; дневной лимит ¥ 6 000, месячный ¥ 100 000",
  autoPreview: (threshold, amount) =>
    `Когда баланс < ¥ ${threshold}, автопополнение ¥ ${amount}`,
  signNow: "Подписать сейчас",
});

const vi = fromEn({
  pageTitle: "Nạp tiền",
  recordHeaders: ["ID", "Thời gian", "Kênh", "Trạng thái", "Số tiền", "Thao tác"],
  balanceLabel: "Số dư",
  overdraftSuffix: (n) => `(Hạn mức thấu chi còn lại ¥ ${n})`,
  couponLabel: "Phiếu thưởng",
  couponSuffix: "khả dụng",
  packageLabel: "Gói tài nguyên",
  packageSuffix: "đang hoạt động",
  online: "Nạp trực tuyến",
  auto: "Nạp tự động",
  autoOff: "Chưa bật",
  corporate: "Chuyển khoản ngân hàng",
  warningOn: "Cảnh báo số dư đã bật (Cài đặt)",
  warningOffChip: "Cảnh báo số dư đã tắt (Cài đặt)",
  warningModalTitle: "Cài đặt cảnh báo số dư",
  warningRule1: "Cảnh báo số dư hỗ trợ Tự động, Tùy chỉnh và Tắt:",
  warningRule1a:
    "Ở chế độ Tự động, cảnh báo được gửi khi hạn mức khả dụng còn lại (số dư cộng thấu chi) thấp hơn mức tiêu thụ số dư nạp trung bình hàng ngày từ cuộc gọi API trong 7 ngày qua",
  warningRule1b:
    "Ở chế độ Tùy chỉnh, cảnh báo được gửi khi hạn mức khả dụng còn lại (số dư cộng thấu chi) thấp hơn ngưỡng bạn đặt",
  warningRule2:
    "Cảnh báo số dư được gửi hàng ngày lúc 10:00 sáng giờ Bắc Kinh qua SMS và email",
  warningRule3Before: "Sau lần nạp trực tuyến đầu tiên, cảnh báo số dư được bật ở ",
  warningRule3Bold: "chế độ Tự động",
  warningRule3After: "",
  warningThresholdLabel: "Ngưỡng cảnh báo:",
  warningAuto: "Tự động",
  warningCustom: "Tùy chỉnh",
  warningOff: "Tắt cảnh báo",
  warningYuan: "CNY",
  warningCancel: "Hủy",
  warningOk: "Xác nhận",
  payAmount: "Số tiền thanh toán",
  payMethod: "Phương thức thanh toán",
  otherAmount: "Số tiền khác",
  alipay: "Alipay",
  otherPay: "Phương thức thanh toán khác",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Nhấn để xác minh",
  captchaSuccess: "Xác minh thành công",
  confirmPay: "Xác nhận thanh toán",
  paying: "Đang chuyển đến thanh toán…",
  payDisabled:
    "Nạp trực tuyến chưa khả dụng. Yêu cầu quản trị viên xác nhận tuân thủ thanh toán trong Backend và cấu hình Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Không thể bắt đầu thanh toán. Vui lòng thử lại sau.",
  agreePrefix:
    "Tôi hiểu rằng tiền nạp không thể xuất hóa đơn trực tiếp. Xác nhận thanh toán đồng nghĩa với việc đồng ý ",
  agreeLink: "Thỏa thuận người dùng",
  recordsTitle: "Lịch sử nạp và hoàn tiền",
  statusPending: "Chờ thanh toán",
  statusSuccess: "Hoàn tất",
  statusOther: "Đã đóng",
  empty: "Không có dữ liệu",
  segmentAll: "Tất cả",
  segmentAvailable: "Khả dụng",
  redeemCenter: "Trung tâm đổi mã",
  redeemInputLabel: "Mã đổi",
  redeemPlaceholder: "Nhập mã do quản trị viên cấp",
  redeemSubmit: "Đổi",
  redeemSubmitting: "Đang đổi…",
  redeemCancel: "Hủy",
  redeemSuccess: (n) => `Đổi thành công. Hạn mức +${n}`,
  redeemFailed: "Đổi thất bại. Kiểm tra mã có hợp lệ không.",
  quotaLabel: "Hạn mức",
  autoTitle: "Bật nạp tự động Alipay",
  autoAlerts: [
    "Do Alipay cung cấp. Sau khi ký, bạn ủy quyền nền tảng tự động nạp khi số dư dưới ngưỡng. Có thể hủy bất cứ lúc nào.",
    "Sau khi ký, nền tảng kiểm tra số dư mỗi 10 phút. Mặc định không nạp ban đêm (22:00–08:00). Có thể điều chỉnh sau khi bật.",
    "10 phút trước khi nạp tự động, hệ thống gửi SMS thông báo.",
  ],
  thresholdLabel: "Ngưỡng",
  rechargeAmountLabel: "Số tiền nạp",
  otherAmountShort: "Số tiền khác",
  thresholdHint:
    "Nạp tự động kích hoạt khi số dư dưới ngưỡng. Phạm vi ¥ 5 ~ ¥ 1000",
  amountHint:
    "Phải lớn hơn ngưỡng, tối đa ¥ 2000; giới hạn ngày ¥ 6.000, tháng ¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Khi số dư < ¥ ${threshold}, nạp tự động ¥ ${amount}`,
  signNow: "Ký ngay",
});

const ko = fromEn({
  pageTitle: "충전",
  recordHeaders: ["ID", "시간", "채널", "상태", "금액", "작업"],
  balanceLabel: "잔액",
  overdraftSuffix: (n) => `(남은 초과 인출 한도 ¥ ${n})`,
  couponLabel: "쿠폰",
  couponSuffix: "사용 가능",
  packageLabel: "리소스 팩",
  packageSuffix: "활성",
  online: "온라인 충전",
  auto: "자동 충전",
  autoOff: "미설정",
  corporate: "법인 계좌 이체",
  warningOn: "잔액 알림 켜짐 (설정)",
  warningOffChip: "잔액 알림 꺼짐 (설정)",
  warningModalTitle: "잔액 알림 설정",
  warningRule1: "잔액 알림은 자동, 사용자 지정, 끄기 세 가지 모드를 지원합니다:",
  warningRule1a:
    "자동 모드에서는 남은 사용 가능 한도(충전 잔액 및 초과 인출 한도 포함)가 최근 7일 API 호출로 발생한 충전 잔액의 평균 일일 소비보다 낮아지면 자동으로 알림",
  warningRule1b:
    "사용자 지정 모드에서는 남은 사용 가능 한도(충전 잔액 및 초과 인출 한도 포함)가 설정한 임계값보다 낮아지면 자동으로 알림",
  warningRule2:
    "잔액 알림은 베이징 시간 매일 오전 10시에 SMS 및 이메일로 발송됩니다",
  warningRule3Before: "첫 온라인 충전 완료 후 시스템이 ",
  warningRule3Bold: "자동 모드",
  warningRule3After: "로 잔액 알림을 켭니다",
  warningThresholdLabel: "알림 임계값:",
  warningAuto: "자동",
  warningCustom: "사용자 지정",
  warningOff: "알림 끄기",
  warningYuan: "위안",
  warningCancel: "취소",
  warningOk: "확인",
  payAmount: "결제 금액",
  payMethod: "결제 수단",
  otherAmount: "기타 금액",
  alipay: "Alipay",
  otherPay: "기타 결제 수단",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "클릭하여 인증",
  captchaSuccess: "인증 성공",
  confirmPay: "결제 확인",
  paying: "결제 페이지로 이동 중…",
  payDisabled:
    "온라인 충전이 아직 제공되지 않습니다. 관리자에게 Backend에서 결제 규정 준수 확인 및 Epay(PayAddress / EpayId / EpayKey / PayMethods) 구성을 요청하세요.",
  payError: "결제를 시작하지 못했습니다. 나중에 다시 시도하세요.",
  agreePrefix:
    "충전 자금은 직접 세금계산서를 발행할 수 없음을 이해합니다. 결제 확인은 본 플랫폼 ",
  agreeLink: "「이용약관」",
  recordsTitle: "충전 및 환불 기록",
  statusPending: "결제 대기",
  statusSuccess: "완료",
  statusOther: "종료",
  empty: "데이터 없음",
  segmentAll: "전체",
  segmentAvailable: "사용 가능",
  redeemCenter: "교환 센터",
  redeemInputLabel: "교환 코드",
  redeemPlaceholder: "관리자가 발급한 코드를 입력하세요",
  redeemSubmit: "교환",
  redeemSubmitting: "교환 중…",
  redeemCancel: "취소",
  redeemSuccess: (n) => `교환 성공. 한도 +${n}`,
  redeemFailed: "교환 실패. 코드가 유효한지 확인하세요.",
  quotaLabel: "한도",
  autoTitle: "Alipay 자동 충전 활성화",
  autoAlerts: [
    "Alipay에서 제공합니다. 계약 후 잔액이 설정 임계값 아래로 떨어지면 자동 충전을 허용합니다. 언제든 취소할 수 있습니다.",
    "계약 후 플랫폼은 10분마다 잔액을 확인합니다. 기본적으로 야간(22:00~08:00)에는 실행되지 않습니다(활성화 후 조정 가능).",
    "자동 충전 10분 전에 시스템이 SMS 알림을 보냅니다.",
  ],
  thresholdLabel: "임계값 설정",
  rechargeAmountLabel: "충전 금액",
  otherAmountShort: "기타 금액",
  thresholdHint: "잔액이 임계값 아래로 떨어지면 자동 충전됩니다. 범위 ¥ 5 ~ ¥ 1000",
  amountHint: "임계값보다 커야 하며, 상한 ¥ 2000; 일일 누적 ¥ 6,000, 월간 누적 ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `잔액 < ¥ ${threshold}일 때 자동 충전 ¥ ${amount}`,
  signNow: "지금 계약",
});

const de = fromEn({
  pageTitle: "Aufladen",
  recordHeaders: ["ID", "Zeit", "Kanal", "Status", "Betrag", "Aktionen"],
  balanceLabel: "Guthaben",
  overdraftSuffix: (n) => `(Verbleibendes Überziehungskontingent ¥ ${n})`,
  couponLabel: "Gutscheine",
  couponSuffix: "verfügbar",
  packageLabel: "Ressourcenpakete",
  packageSuffix: "aktiv",
  online: "Online-Aufladung",
  auto: "Automatisches Aufladen",
  autoOff: "Nicht aktiviert",
  corporate: "Banküberweisung",
  warningOn: "Guthabenwarnung aktiv (Einstellungen)",
  warningOffChip: "Guthabenwarnung deaktiviert (Einstellungen)",
  warningModalTitle: "Guthabenwarnung-Einstellungen",
  warningRule1: "Guthabenwarnungen unterstützen Auto, Benutzerdefiniert und Aus:",
  warningRule1a:
    "Im Auto-Modus wird gewarnt, wenn das verbleibende verfügbare Kontingent (Guthaben plus Überziehung) unter dem durchschnittlichen täglichen Aufladeguthaben-Verbrauch der letzten 7 Tage API-Aufrufe fällt",
  warningRule1b:
    "Im benutzerdefinierten Modus wird gewarnt, wenn das verbleibende verfügbare Kontingent (Guthaben plus Überziehung) unter Ihren Schwellenwert fällt",
  warningRule2:
    "Guthabenwarnungen werden täglich um 10:00 Uhr Peking-Zeit per SMS und E-Mail gesendet",
  warningRule3Before: "Nach der ersten Online-Aufladung werden Guthabenwarnungen im ",
  warningRule3Bold: "Auto-Modus",
  warningRule3After: " aktiviert",
  warningThresholdLabel: "Warnschwelle:",
  warningAuto: "Auto",
  warningCustom: "Benutzerdefiniert",
  warningOff: "Warnungen ausschalten",
  warningYuan: "CNY",
  warningCancel: "Abbrechen",
  warningOk: "Bestätigen",
  payAmount: "Zahlungsbetrag",
  payMethod: "Zahlungsmethode",
  otherAmount: "Anderer Betrag",
  alipay: "Alipay",
  otherPay: "Andere Zahlungsmethoden",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Klicken zum Verifizieren",
  captchaSuccess: "Verifiziert",
  confirmPay: "Zahlung bestätigen",
  paying: "Weiterleitung zur Zahlung…",
  payDisabled:
    "Online-Aufladung ist noch nicht verfügbar. Bitten Sie einen Admin, die Zahlungscompliance in Backend zu bestätigen und Epay zu konfigurieren (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Zahlung konnte nicht gestartet werden. Bitte später erneut versuchen.",
  agreePrefix:
    "Ich verstehe, dass aufgeladene Mittel nicht direkt in Rechnung gestellt werden können. Mit der Zahlungsbestätigung akzeptiere ich die ",
  agreeLink: "Nutzungsbedingungen",
  recordsTitle: "Auflade- und Rückerstattungsverlauf",
  statusPending: "Zahlung ausstehend",
  statusSuccess: "Abgeschlossen",
  statusOther: "Geschlossen",
  empty: "Keine Daten",
  segmentAll: "Alle",
  segmentAvailable: "Verfügbar",
  redeemCenter: "Einlösezentrum",
  redeemInputLabel: "Einlösecode",
  redeemPlaceholder: "Vom Administrator ausgegebenen Code eingeben",
  redeemSubmit: "Einlösen",
  redeemSubmitting: "Einlösen…",
  redeemCancel: "Abbrechen",
  redeemSuccess: (n) => `Einlösung erfolgreich. Kontingent +${n}`,
  redeemFailed: "Einlösung fehlgeschlagen. Prüfen Sie, ob der Code gültig ist.",
  quotaLabel: "Kontingent",
  autoTitle: "Alipay-Autoladung aktivieren",
  autoAlerts: [
    "Von Alipay bereitgestellt. Nach der Unterzeichnung autorisieren Sie die Plattform, automatisch aufzuladen, wenn Ihr Guthaben unter den Schwellenwert fällt. Jederzeit kündbar.",
    "Nach der Unterzeichnung prüft die Plattform alle 10 Minuten das Guthaben. Standardmäßig nachts (22:00–08:00) keine Aufladung. Nach Aktivierung anpassbar.",
    "Zehn Minuten vor einer Autoladung sendet das System eine SMS-Benachrichtigung.",
  ],
  thresholdLabel: "Schwellenwert",
  rechargeAmountLabel: "Aufladebetrag",
  otherAmountShort: "Anderer Betrag",
  thresholdHint:
    "Autoladung wird ausgelöst, wenn das Guthaben unter den Schwellenwert fällt. Bereich ¥ 5 ~ ¥ 1000",
  amountHint:
    "Muss den Schwellenwert überschreiten, max. ¥ 2000; Tageslimit ¥ 6.000, Monatslimit ¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Wenn Guthaben < ¥ ${threshold}, Autoladung ¥ ${amount}`,
  signNow: "Jetzt unterzeichnen",
});

const es = fromEn({
  pageTitle: "Recargar",
  recordHeaders: ["ID", "Hora", "Canal", "Estado", "Importe", "Acciones"],
  balanceLabel: "Saldo",
  overdraftSuffix: (n) => `(Cuota de sobregiro restante ¥ ${n})`,
  couponLabel: "Cupones",
  couponSuffix: "disponibles",
  packageLabel: "Paquetes de recursos",
  packageSuffix: "activos",
  online: "Recarga en línea",
  auto: "Recarga automática",
  autoOff: "No activada",
  corporate: "Transferencia bancaria",
  warningOn: "Alerta de saldo activada (Ajustes)",
  warningOffChip: "Alerta de saldo desactivada (Ajustes)",
  warningModalTitle: "Ajustes de alerta de saldo",
  warningRule1: "Las alertas de saldo admiten Auto, Personalizado y Desactivado:",
  warningRule1a:
    "En modo Auto, se envía una alerta cuando la cuota disponible restante (saldo más sobregiro) cae por debajo del consumo diario promedio del saldo de recarga de las llamadas API de los últimos 7 días",
  warningRule1b:
    "En modo Personalizado, se envía una alerta cuando la cuota disponible restante (saldo más sobregiro) cae por debajo de su umbral",
  warningRule2:
    "Las alertas de saldo se envían diariamente a las 10:00 (hora de Pekín) por SMS y correo",
  warningRule3Before: "Tras su primera recarga en línea, las alertas de saldo se activan en ",
  warningRule3Bold: "modo Auto",
  warningRule3After: "",
  warningThresholdLabel: "Umbral de alerta:",
  warningAuto: "Auto",
  warningCustom: "Personalizado",
  warningOff: "Desactivar alertas",
  warningYuan: "CNY",
  warningCancel: "Cancelar",
  warningOk: "Confirmar",
  payAmount: "Importe del pago",
  payMethod: "Método de pago",
  otherAmount: "Otro importe",
  alipay: "Alipay",
  otherPay: "Otros métodos de pago",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Clic para verificar",
  captchaSuccess: "Verificado",
  confirmPay: "Confirmar pago",
  paying: "Redirigiendo al pago…",
  payDisabled:
    "La recarga en línea aún no está disponible. Pida a un administrador confirmar el cumplimiento de pagos en Backend y configurar Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "No se pudo iniciar el pago. Inténtelo más tarde.",
  agreePrefix:
    "Entiendo que los fondos recargados no pueden facturarse directamente. Al confirmar el pago, acepto el ",
  agreeLink: "Acuerdo de usuario",
  recordsTitle: "Historial de recargas y reembolsos",
  statusPending: "Pago pendiente",
  statusSuccess: "Completado",
  statusOther: "Cerrado",
  empty: "Sin datos",
  segmentAll: "Todo",
  segmentAvailable: "Disponible",
  redeemCenter: "Centro de canje",
  redeemInputLabel: "Código de canje",
  redeemPlaceholder: "Introduzca el código emitido por un administrador",
  redeemSubmit: "Canjear",
  redeemSubmitting: "Canjeando…",
  redeemCancel: "Cancelar",
  redeemSuccess: (n) => `Canje exitoso. Cuota +${n}`,
  redeemFailed: "Canje fallido. Compruebe si el código es válido.",
  quotaLabel: "Cuota",
  autoTitle: "Activar recarga automática Alipay",
  autoAlerts: [
    "Proporcionado por Alipay. Tras firmar, autoriza a la plataforma a recargar automáticamente cuando su saldo caiga por debajo del umbral. Puede cancelar en cualquier momento.",
    "Tras firmar, la plataforma comprueba el saldo cada 10 minutos. Por defecto no recarga de noche (22:00–08:00). Ajustable tras activar.",
    "Diez minutos antes de una recarga automática, el sistema le envía un SMS.",
  ],
  thresholdLabel: "Umbral",
  rechargeAmountLabel: "Importe de recarga",
  otherAmountShort: "Otro importe",
  thresholdHint:
    "La recarga automática se activa cuando el saldo cae por debajo del umbral. Rango ¥ 5 ~ ¥ 1000",
  amountHint:
    "Debe superar el umbral, máx. ¥ 2000; límite diario ¥ 6.000, mensual ¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Cuando saldo < ¥ ${threshold}, recarga automática ¥ ${amount}`,
  signNow: "Firmar ahora",
});

const ptBR = fromEn({
  pageTitle: "Recarga",
  recordHeaders: ["ID", "Hora", "Canal", "Status", "Valor", "Ações"],
  balanceLabel: "Saldo",
  overdraftSuffix: (n) => `(Cota de cheque especial restante ¥ ${n})`,
  couponLabel: "Cupons",
  couponSuffix: "disponíveis",
  packageLabel: "Pacotes de recursos",
  packageSuffix: "ativos",
  online: "Recarga online",
  auto: "Recarga automática",
  autoOff: "Não ativada",
  corporate: "Transferência bancária",
  warningOn: "Alerta de saldo ativada (Configurações)",
  warningOffChip: "Alerta de saldo desativada (Configurações)",
  warningModalTitle: "Configurações de alerta de saldo",
  warningRule1: "Alertas de saldo suportam Auto, Personalizado e Desligado:",
  warningRule1a:
    "No modo Auto, um alerta é enviado quando a cota disponível restante (saldo mais cheque especial) fica abaixo do consumo médio diário do saldo de recarga das chamadas API dos últimos 7 dias",
  warningRule1b:
    "No modo Personalizado, um alerta é enviado quando a cota disponível restante (saldo mais cheque especial) fica abaixo do seu limite",
  warningRule2:
    "Alertas de saldo são enviados diariamente às 10:00 (horário de Pequim) por SMS e e-mail",
  warningRule3Before: "Após sua primeira recarga online, alertas de saldo são ativados no ",
  warningRule3Bold: "modo Auto",
  warningRule3After: "",
  warningThresholdLabel: "Limite de alerta:",
  warningAuto: "Auto",
  warningCustom: "Personalizado",
  warningOff: "Desativar alertas",
  warningYuan: "CNY",
  warningCancel: "Cancelar",
  warningOk: "Confirmar",
  payAmount: "Valor do pagamento",
  payMethod: "Forma de pagamento",
  otherAmount: "Outro valor",
  alipay: "Alipay",
  otherPay: "Outras formas de pagamento",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Clique para verificar",
  captchaSuccess: "Verificado",
  confirmPay: "Confirmar pagamento",
  paying: "Redirecionando ao pagamento…",
  payDisabled:
    "Recarga online ainda não disponível. Peça a um administrador confirmar conformidade de pagamento no Backend e configurar Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Falha ao iniciar pagamento. Tente novamente mais tarde.",
  agreePrefix:
    "Entendo que fundos recarregados não podem ser faturados diretamente. Ao confirmar o pagamento, concordo com o ",
  agreeLink: "Acordo do usuário",
  recordsTitle: "Histórico de recargas e reembolsos",
  statusPending: "Pagamento pendente",
  statusSuccess: "Concluído",
  statusOther: "Fechado",
  empty: "Sem dados",
  segmentAll: "Todos",
  segmentAvailable: "Disponível",
  redeemCenter: "Central de resgate",
  redeemInputLabel: "Código de resgate",
  redeemPlaceholder: "Digite o código emitido por um administrador",
  redeemSubmit: "Resgatar",
  redeemSubmitting: "Resgatando…",
  redeemCancel: "Cancelar",
  redeemSuccess: (n) => `Resgate bem-sucedido. Cota +${n}`,
  redeemFailed: "Resgate falhou. Verifique se o código é válido.",
  quotaLabel: "Cota",
  autoTitle: "Ativar recarga automática Alipay",
  autoAlerts: [
    "Fornecido pelo Alipay. Após assinar, você autoriza a plataforma a recarregar automaticamente quando o saldo ficar abaixo do limite. Pode cancelar a qualquer momento.",
    "Após assinar, a plataforma verifica o saldo a cada 10 minutos. Por padrão, não recarrega à noite (22:00–08:00). Ajustável após ativar.",
    "Dez minutos antes de uma recarga automática, o sistema envia um SMS.",
  ],
  thresholdLabel: "Limite",
  rechargeAmountLabel: "Valor da recarga",
  otherAmountShort: "Outro valor",
  thresholdHint:
    "Recarga automática dispara quando o saldo fica abaixo do limite. Faixa ¥ 5 ~ ¥ 1000",
  amountHint:
    "Deve ser maior que o limite, máx. ¥ 2000; teto diário ¥ 6.000, mensal ¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Quando saldo < ¥ ${threshold}, recarga automática ¥ ${amount}`,
  signNow: "Assinar agora",
});

const ar = fromEn({
  pageTitle: "شحن",
  recordHeaders: ["المعرّف", "الوقت", "القناة", "الحالة", "المبلغ", "إجراءات"],
  balanceLabel: "الرصيد",
  overdraftSuffix: (n) => `(حصة السحب على المكشوف المتبقية ¥ ${n})`,
  couponLabel: "قسائم",
  couponSuffix: "متاحة",
  packageLabel: "حزم الموارد",
  packageSuffix: "نشطة",
  online: "شحن عبر الإنترنت",
  auto: "شحن تلقائي",
  autoOff: "غير مفعّل",
  corporate: "تحويل بنكي",
  warningOn: "تنبيه الرصيد مفعّل (الإعدادات)",
  warningOffChip: "تنبيه الرصيد معطّل (الإعدادات)",
  warningModalTitle: "إعدادات تنبيه الرصيد",
  warningRule1: "تدعم تنبيهات الرصيد: تلقائي، مخصص، وإيقاف:",
  warningRule1a:
    "في الوضع التلقائي، يُرسل تنبيه عندما تنخفض الحصة المتاحة المتبقية (الرصيد بالإضافة إلى السحب على المكشوف) عن متوسط الاستهلاك اليومي لرصيد الشحن من استدعاءات API خلال آخر 7 أيام",
  warningRule1b:
    "في الوضع المخصص، يُرسل تنبيه عندما تنخفض الحصة المتاحة المتبقية (الرصيد بالإضافة إلى السحب على المكشوف) عن عتبتك",
  warningRule2:
    "تُرسل تنبيهات الرصيد يوميًا الساعة 10:00 صباحًا بتوقيت بكين عبر SMS والبريد الإلكتروني",
  warningRule3Before: "بعد أول شحن عبر الإنترنت، تُفعّل تنبيهات الرصيد في ",
  warningRule3Bold: "الوضع التلقائي",
  warningRule3After: "",
  warningThresholdLabel: "عتبة التنبيه:",
  warningAuto: "تلقائي",
  warningCustom: "مخصص",
  warningOff: "إيقاف التنبيهات",
  warningYuan: "CNY",
  warningCancel: "إلغاء",
  warningOk: "تأكيد",
  payAmount: "مبلغ الدفع",
  payMethod: "طريقة الدفع",
  otherAmount: "مبلغ آخر",
  alipay: "Alipay",
  otherPay: "طرق دفع أخرى",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "انقر للتحقق",
  captchaSuccess: "تم التحقق",
  confirmPay: "تأكيد الدفع",
  paying: "جارٍ التوجيه إلى الدفع…",
  payDisabled:
    "الشحن عبر الإنترنت غير متاح بعد. اطلب من المسؤول تأكيد امتثال الدفع في Backend وتكوين Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "تعذّر بدء الدفع. يرجى المحاولة لاحقًا.",
  agreePrefix:
    "أفهم أن أموال الشحن لا يمكن إصدار فاتورة لها مباشرة. بتأكيد الدفع، أوافق على ",
  agreeLink: "اتفاقية المستخدم",
  recordsTitle: "سجل الشحن والاسترداد",
  statusPending: "في انتظار الدفع",
  statusSuccess: "مكتمل",
  statusOther: "مغلق",
  empty: "لا توجد بيانات",
  segmentAll: "الكل",
  segmentAvailable: "متاح",
  redeemCenter: "مركز الاسترداد",
  redeemInputLabel: "رمز الاسترداد",
  redeemPlaceholder: "أدخل الرمز الصادر من المسؤول",
  redeemSubmit: "استرداد",
  redeemSubmitting: "جارٍ الاسترداد…",
  redeemCancel: "إلغاء",
  redeemSuccess: (n) => `تم الاسترداد بنجاح. الحصة +${n}`,
  redeemFailed: "فشل الاسترداد. تحقق من صحة الرمز.",
  quotaLabel: "الحصة",
  autoTitle: "تفعيل الشحن التلقائي عبر Alipay",
  autoAlerts: [
    "مقدّم من Alipay. بعد التوقيع، تفوّض المنصة بالشحن تلقائيًا عندما ينخفض رصيدك عن العتبة. يمكن الإلغاء في أي وقت.",
    "بعد التوقيع، تتحقق المنصة من الرصيد كل 10 دقائق. افتراضيًا لا يُنفّذ ليلًا (22:00–08:00). قابل للتعديل بعد التفعيل.",
    "قبل 10 دقائق من الشحن التلقائي، يرسل النظام إشعار SMS.",
  ],
  thresholdLabel: "العتبة",
  rechargeAmountLabel: "مبلغ الشحن",
  otherAmountShort: "مبلغ آخر",
  thresholdHint:
    "يُفعّل الشحن التلقائي عندما ينخفض الرصيد عن العتبة. النطاق ¥ 5 ~ ¥ 1000",
  amountHint:
    "يجب أن يتجاوز العتبة، بحد أقصى ¥ 2000؛ حد يومي ¥ 6,000، شهري ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `عندما الرصيد < ¥ ${threshold}، شحن تلقائي ¥ ${amount}`,
  signNow: "وقّع الآن",
});

const hi = fromEn({
  pageTitle: "रिचार्ज",
  recordHeaders: ["ID", "समय", "चैनल", "स्थिति", "राशि", "कार्रवाई"],
  balanceLabel: "शेष",
  overdraftSuffix: (n) => `(शेष ओवरड्राफ्ट कोटा ¥ ${n})`,
  couponLabel: "वाउचर",
  couponSuffix: "उपलब्ध",
  packageLabel: "संसाधन पैक",
  packageSuffix: "सक्रिय",
  online: "ऑनलाइन रिचार्ज",
  auto: "ऑटो रिचार्ज",
  autoOff: "सक्षम नहीं",
  corporate: "बैंक ट्रांसफर",
  warningOn: "बैलेंस अलर्ट चालू (सेटिंग्स)",
  warningOffChip: "बैलेंस अलर्ट बंद (सेटिंग्स)",
  warningModalTitle: "बैलेंस अलर्ट सेटिंग्स",
  warningRule1: "बैलेंस अलर्ट में ऑटो, कस्टम और बंद तीन मोड हैं:",
  warningRule1a:
    "ऑटो मोड में, जब शेष उपलब्ध कोटा (रिचार्ज शेष और ओवरड्राफ्ट सहित) पिछले 7 दिनों के API कॉल से रिचार्ज शेष की औसत दैनिक खपत से नीचे जाता है तो अलर्ट भेजा जाता है",
  warningRule1b:
    "कस्टम मोड में, जब शेष उपलब्ध कोटा (रिचार्ज शेष और ओवरड्राफ्ट सहित) आपकी सीमा से नीचे जाता है तो अलर्ट भेजा जाता है",
  warningRule2:
    "बैलेंस अलर्ट बीजिंग समय प्रतिदिन सुबह 10 बजे SMS और ईमेल से भेजे जाते हैं",
  warningRule3Before: "पहले ऑनलाइन रिचार्ज के बाद, बैलेंस अलर्ट ",
  warningRule3Bold: "ऑटो मोड",
  warningRule3After: " में सक्षम होता है",
  warningThresholdLabel: "अलर्ट सीमा:",
  warningAuto: "ऑटो",
  warningCustom: "कस्टम",
  warningOff: "अलर्ट बंद करें",
  warningYuan: "CNY",
  warningCancel: "रद्द करें",
  warningOk: "पुष्टि करें",
  payAmount: "भुगतान राशि",
  payMethod: "भुगतान विधि",
  otherAmount: "अन्य राशि",
  alipay: "Alipay",
  otherPay: "अन्य भुगतान विधियाँ",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "सत्यापन के लिए क्लिक करें",
  captchaSuccess: "सत्यापित",
  confirmPay: "भुगतान की पुष्टि करें",
  paying: "भुगतान पर रीडायरेक्ट हो रहा है…",
  payDisabled:
    "ऑनलाइन रिचार्ज अभी उपलब्ध नहीं है। Backend में भुगतान अनुपालन की पुष्टि और Epay (PayAddress / EpayId / EpayKey / PayMethods) कॉन्फ़िगर करने के लिए व्यवस्थापक से कहें।",
  payError: "भुगतान शुरू नहीं हो सका। बाद में पुनः प्रयास करें।",
  agreePrefix:
    "मैं समझता/समझती हूँ कि रिचार्ज धन सीधे चालान नहीं किया जा सकता। भुगतान की पुष्टि करके, मैं प्लेटफ़ॉर्म की ",
  agreeLink: "उपयोगकर्ता समझौते",
  recordsTitle: "रिचार्ज और रिफंड रिकॉर्ड",
  statusPending: "भुगतान लंबित",
  statusSuccess: "पूर्ण",
  statusOther: "बंद",
  empty: "कोई डेटा नहीं",
  segmentAll: "सभी",
  segmentAvailable: "उपलब्ध",
  redeemCenter: "रिडेम्पशन केंद्र",
  redeemInputLabel: "रिडेम्पशन कोड",
  redeemPlaceholder: "व्यवस्थापक द्वारा जारी कोड दर्ज करें",
  redeemSubmit: "रिडीम करें",
  redeemSubmitting: "रिडीम हो रहा है…",
  redeemCancel: "रद्द करें",
  redeemSuccess: (n) => `रिडीम सफल। कोटा +${n}`,
  redeemFailed: "रिडीम विफल। कोड वैध है या नहीं जाँचें।",
  quotaLabel: "कोटा",
  autoTitle: "Alipay ऑटो रिचार्ज सक्षम करें",
  autoAlerts: [
    "Alipay द्वारा प्रदान। हस्ताक्षर के बाद, जब आपका शेष सीमा से नीचे जाए तो प्लेटफ़ॉर्म को स्वचालित रिचार्ज की अनुमति देते हैं। कभी भी रद्द कर सकते हैं।",
    "हस्ताक्षर के बाद, प्लेटफ़ॉर्म हर 10 मिनट में शेष जाँचता है। डिफ़ॉल्ट रूप से रात (22:00–08:00) में नहीं चलता। सक्षम करने के बाद समायोजित कर सकते हैं।",
    "ऑटो रिचार्ज से 10 मिनट पहले, सिस्टम SMS सूचना भेजता है।",
  ],
  thresholdLabel: "सीमा",
  rechargeAmountLabel: "रिचार्ज राशि",
  otherAmountShort: "अन्य राशि",
  thresholdHint:
    "जब शेष सीमा से नीचे जाए तो ऑटो रिचार्ज ट्रिगर होता है। सीमा ¥ 5 ~ ¥ 1000",
  amountHint:
    "सीमा से अधिक होना चाहिए, अधिकतम ¥ 2000; दैनिक सीमा ¥ 6,000, मासिक ¥ 100,000",
  autoPreview: (threshold, amount) =>
    `जब शेष < ¥ ${threshold}, ऑटो रिचार्ज ¥ ${amount}`,
  signNow: "अभी हस्ताक्षर करें",
});

const id = fromEn({
  pageTitle: "Isi ulang",
  recordHeaders: ["ID", "Waktu", "Saluran", "Status", "Jumlah", "Tindakan"],
  balanceLabel: "Saldo",
  overdraftSuffix: (n) => `(Kuota overdraft tersisa ¥ ${n})`,
  couponLabel: "Voucher",
  couponSuffix: "tersedia",
  packageLabel: "Paket sumber daya",
  packageSuffix: "aktif",
  online: "Isi ulang online",
  auto: "Isi ulang otomatis",
  autoOff: "Belum diaktifkan",
  corporate: "Transfer bank",
  warningOn: "Peringatan saldo aktif (Pengaturan)",
  warningOffChip: "Peringatan saldo nonaktif (Pengaturan)",
  warningModalTitle: "Pengaturan peringatan saldo",
  warningRule1: "Peringatan saldo mendukung Otomatis, Kustom, dan Mati:",
  warningRule1a:
    "Dalam mode Otomatis, peringatan dikirim ketika kuota tersedia tersisa (saldo plus overdraft) turun di bawah konsumsi harian rata-rata saldo isi ulang dari panggilan API 7 hari terakhir",
  warningRule1b:
    "Dalam mode Kustom, peringatan dikirim ketika kuota tersedia tersisa (saldo plus overdraft) turun di bawah ambang batas Anda",
  warningRule2:
    "Peringatan saldo dikirim setiap hari pukul 10:00 waktu Beijing via SMS dan email",
  warningRule3Before: "Setelah isi ulang online pertama, peringatan saldo diaktifkan dalam ",
  warningRule3Bold: "mode Otomatis",
  warningRule3After: "",
  warningThresholdLabel: "Ambang peringatan:",
  warningAuto: "Otomatis",
  warningCustom: "Kustom",
  warningOff: "Matikan peringatan",
  warningYuan: "CNY",
  warningCancel: "Batal",
  warningOk: "Konfirmasi",
  payAmount: "Jumlah pembayaran",
  payMethod: "Metode pembayaran",
  otherAmount: "Jumlah lain",
  alipay: "Alipay",
  otherPay: "Metode pembayaran lain",
  wechatPay: "WeChat Pay",
  wechatShort: "WeChat",
  captcha: "Klik untuk verifikasi",
  captchaSuccess: "Terverifikasi",
  confirmPay: "Konfirmasi pembayaran",
  paying: "Mengalihkan ke pembayaran…",
  payDisabled:
    "Isi ulang online belum tersedia. Minta admin mengonfirmasi kepatuhan pembayaran di Backend dan mengonfigurasi Epay (PayAddress / EpayId / EpayKey / PayMethods).",
  payError: "Gagal memulai pembayaran. Coba lagi nanti.",
  agreePrefix:
    "Saya memahami dana isi ulang tidak dapat difakturkan langsung. Dengan mengonfirmasi pembayaran, saya setuju dengan ",
  agreeLink: "Perjanjian Pengguna",
  recordsTitle: "Riwayat isi ulang dan refund",
  statusPending: "Menunggu pembayaran",
  statusSuccess: "Selesai",
  statusOther: "Ditutup",
  empty: "Tidak ada data",
  segmentAll: "Semua",
  segmentAvailable: "Tersedia",
  redeemCenter: "Pusat penukaran",
  redeemInputLabel: "Kode penukaran",
  redeemPlaceholder: "Masukkan kode yang diterbitkan administrator",
  redeemSubmit: "Tukar",
  redeemSubmitting: "Menukar…",
  redeemCancel: "Batal",
  redeemSuccess: (n) => `Penukaran berhasil. Kuota +${n}`,
  redeemFailed: "Penukaran gagal. Periksa apakah kode valid.",
  quotaLabel: "Kuota",
  autoTitle: "Aktifkan isi ulang otomatis Alipay",
  autoAlerts: [
    "Disediakan oleh Alipay. Setelah menandatangani, Anda mengizinkan platform mengisi ulang otomatis saat saldo di bawah ambang batas. Dapat dibatalkan kapan saja.",
    "Setelah menandatangani, platform memeriksa saldo setiap 10 menit. Secara default tidak dijalankan malam hari (22:00–08:00). Dapat disesuaikan setelah diaktifkan.",
    "Sepuluh menit sebelum isi ulang otomatis, sistem mengirim notifikasi SMS.",
  ],
  thresholdLabel: "Ambang batas",
  rechargeAmountLabel: "Jumlah isi ulang",
  otherAmountShort: "Jumlah lain",
  thresholdHint:
    "Isi ulang otomatis dipicu saat saldo di bawah ambang batas. Rentang ¥ 5 ~ ¥ 1000",
  amountHint:
    "Harus melebihi ambang batas, maks ¥ 2000; batas harian ¥ 6.000, bulanan ¥ 100.000",
  autoPreview: (threshold, amount) =>
    `Saat saldo < ¥ ${threshold}, isi ulang otomatis ¥ ${amount}`,
  signNow: "Tanda tangani sekarang",
});

export const EXPENSEBILL_UI_COPY: Record<TargetLocale, ExpenseBillUiCopy> = {
  "zh-CN": zhCN,
  en,
  "zh-TW": zhTW,
  ja,
  fr,
  ru,
  vi,
  ko,
  de,
  es,
  "pt-BR": ptBR,
  ar,
  hi,
  id,
};

export function getExpenseBillUiCopy(locale: string): ExpenseBillUiCopy {
  return pickTargetCatalog(locale, EXPENSEBILL_UI_COPY);
}
