import { BRAND_THEME, LOGO_COLORS } from "@/lib/brand-colors";
import { APP_ROUTES } from "@/lib/routes";
import type { TargetLocale } from "@/lib/locale";
import { pickTargetCatalog } from "@/lib/pick-catalog";
import type { SfGradientPalette } from "@/types/siliconflow-cn-10b89bdc";

export const heroBackground: SfGradientPalette = {
  base: BRAND_THEME.cardSurface,
  orbPrimary: LOGO_COLORS.cyan,
  orbSecondary: LOGO_COLORS.blue,
  accent: LOGO_COLORS.blue,
  logoSrc: "/assets/marketing/home/images/hero-logos/auto.svg",
  logoAlt: "",
  logoOpacity: 0.9,
};

export const LINKS = {
  terms: APP_ROUTES.userAgreement,
} as const;

/** Backend User validate tags: username max=20, password min=8,max=20, email max=50 */
export const AUTH_LIMITS = {
  usernameMax: 20,
  passwordMin: 8,
  passwordMax: 20,
  emailMax: 50,
  codeLength: 6,
} as const;

export type AuthCopy = {
  title: string;
  brandName: string;
  tagline: string;
  subtitle: string;
  accountPlaceholder: string;
  usernamePlaceholder: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  passwordLoginPlaceholder: string;
  codePlaceholder: string;
  sendCode: string;
  sendingCode: string;
  resendCode: (seconds: number) => string;
  needCode: string;
  needTurnstile: string;
  needEmailForCode: string;
  needUsername: string;
  needAccount: string;
  usernameTooLong: string;
  passwordLength: string;
  emailInvalid: string;
  emailTooLong: string;
  codeSent: string;
  agreePrefix: string;
  termsLabel: string;
  login: string;
  register: string;
  submitting: string;
  registerSuccessLogin: string;
  needAgree: string;
  authFailed: string;
  keepLogin: string;
  statusLoadFailed: string;
};

const zhCN: AuthCopy = {
  title: "欢迎登录 八色鸫",
  brandName: "八色鸫",
  tagline: "做所有人的 AI。",
  subtitle: "一个 API，轻松调用 100+ 主流模型。",
  accountPlaceholder: "用户名或邮箱",
  usernamePlaceholder: "用户名",
  emailPlaceholder: "邮箱",
  passwordPlaceholder: "密码（8-20个字符）",
  passwordLoginPlaceholder: "密码",
  codePlaceholder: "邮箱验证码",
  sendCode: "获取验证码",
  sendingCode: "发送中…",
  resendCode: (seconds) => `${seconds}s 后重发`,
  needCode: "请先获取并填写邮箱验证码",
  needTurnstile: "请先完成人机验证",
  needEmailForCode: "请先填写邮箱",
  needUsername: "请填写用户名",
  needAccount: "请填写用户名或邮箱",
  usernameTooLong: "用户名不能超过 20 个字符",
  passwordLength: "密码长度须为 8-20 个字符",
  emailInvalid: "请填写有效的邮箱地址",
  emailTooLong: "邮箱不能超过 50 个字符",
  codeSent: "验证码已发送，请查收邮件",
  agreePrefix: "我已阅读并同意",
  termsLabel: "用户协议",
  login: "登录",
  register: "注册",
  submitting: "请稍候…",
  registerSuccessLogin: "注册成功，请登录",
  needAgree: "请先同意用户协议",
  authFailed: "登录失败，请检查用户名/邮箱和密码",
  keepLogin: "30天内保持登录",
  statusLoadFailed: "无法加载登录配置，请刷新重试",
};

const en: AuthCopy = {
  title: "Welcome to basedong",
  brandName: "basedong",
  tagline: "AI for everyone.",
  subtitle: "One API for 100+ leading models.",
  accountPlaceholder: "Username or email",
  usernamePlaceholder: "Username",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password (8–20 characters)",
  passwordLoginPlaceholder: "Password",
  codePlaceholder: "Email verification code",
  sendCode: "Send code",
  sendingCode: "Sending…",
  resendCode: (seconds) => `Resend in ${seconds}s`,
  needCode: "Please get and enter the email verification code",
  needTurnstile: "Please complete the human verification",
  needEmailForCode: "Please enter your email first",
  needUsername: "Please enter a username",
  needAccount: "Please enter a username or email",
  usernameTooLong: "Username cannot exceed 20 characters",
  passwordLength: "Password must be 8–20 characters",
  emailInvalid: "Please enter a valid email address",
  emailTooLong: "Email cannot exceed 50 characters",
  codeSent: "Verification code sent — check your email",
  agreePrefix: "I have read and agree to the",
  termsLabel: "User Agreement",
  login: "Log in",
  register: "Sign up",
  submitting: "Please wait…",
  registerSuccessLogin: "Registration successful — please log in",
  needAgree: "Please agree to the User Agreement first",
  authFailed: "Login failed — check your username/email and password",
  keepLogin: "Stay signed in for 30 days",
  statusLoadFailed: "Could not load login settings — refresh and try again",
};

const zhTW: AuthCopy = {
  title: "歡迎登入 八色鶇",
  brandName: "八色鶇",
  tagline: "做所有人的 AI。",
  subtitle: "一個 API，輕鬆呼叫 100+ 主流模型。",
  accountPlaceholder: "使用者名稱或電子郵件",
  usernamePlaceholder: "使用者名稱",
  emailPlaceholder: "電子郵件",
  passwordPlaceholder: "密碼（8-20 個字元）",
  passwordLoginPlaceholder: "密碼",
  codePlaceholder: "電子郵件驗證碼",
  sendCode: "取得驗證碼",
  sendingCode: "傳送中…",
  resendCode: (seconds) => `${seconds}s 後重發`,
  needCode: "請先取得並填寫電子郵件驗證碼",
  needTurnstile: "請先完成人機驗證",
  needEmailForCode: "請先填寫電子郵件",
  needUsername: "請填寫使用者名稱",
  needAccount: "請填寫使用者名稱或電子郵件",
  usernameTooLong: "使用者名稱不能超過 20 個字元",
  passwordLength: "密碼長度須為 8-20 個字元",
  emailInvalid: "請填寫有效的電子郵件地址",
  emailTooLong: "電子郵件不能超過 50 個字元",
  codeSent: "驗證碼已傳送，請查收郵件",
  agreePrefix: "我已閱讀並同意",
  termsLabel: "使用者協議",
  login: "登入",
  register: "註冊",
  submitting: "請稍候…",
  registerSuccessLogin: "註冊成功，請登入",
  needAgree: "請先同意使用者協議",
  authFailed: "登入失敗，請檢查使用者名稱／電子郵件和密碼",
  keepLogin: "30 天內保持登入",
  statusLoadFailed: "無法載入登入設定，請重新整理後再試",
};

const fr: AuthCopy = {
  title: "Bienvenue sur basedong",
  brandName: "basedong",
  tagline: "L'IA pour tous.",
  subtitle: "Une API pour plus de 100 modèles majeurs.",
  accountPlaceholder: "Nom d'utilisateur ou e-mail",
  usernamePlaceholder: "Nom d'utilisateur",
  emailPlaceholder: "E-mail",
  passwordPlaceholder: "Mot de passe (8–20 caractères)",
  passwordLoginPlaceholder: "Mot de passe",
  codePlaceholder: "Code de vérification e-mail",
  sendCode: "Envoyer le code",
  sendingCode: "Envoi…",
  resendCode: (seconds) => `Renvoyer dans ${seconds}s`,
  needCode: "Veuillez obtenir et saisir le code de vérification",
  needTurnstile: "Veuillez terminer la vérification humaine",
  needEmailForCode: "Veuillez d'abord saisir votre e-mail",
  needUsername: "Veuillez saisir un nom d'utilisateur",
  needAccount: "Veuillez saisir un nom d'utilisateur ou un e-mail",
  usernameTooLong: "Le nom d'utilisateur ne peut pas dépasser 20 caractères",
  passwordLength: "Le mot de passe doit comporter 8 à 20 caractères",
  emailInvalid: "Veuillez saisir une adresse e-mail valide",
  emailTooLong: "L'e-mail ne peut pas dépasser 50 caractères",
  codeSent: "Code envoyé — vérifiez votre boîte mail",
  agreePrefix: "J'ai lu et j'accepte",
  termsLabel: "les conditions d'utilisation",
  login: "Connexion",
  register: "Inscription",
  submitting: "Veuillez patienter…",
  registerSuccessLogin: "Inscription réussie — veuillez vous connecter",
  needAgree: "Veuillez d'abord accepter les conditions",
  authFailed:
    "Échec de la connexion — vérifiez le nom d'utilisateur/e-mail et le mot de passe",
  keepLogin: "Rester connecté 30 jours",
  statusLoadFailed:
    "Impossible de charger la configuration — actualisez et réessayez",
};

const ru: AuthCopy = {
  title: "Добро пожаловать в basedong",
  brandName: "basedong",
  tagline: "ИИ для всех.",
  subtitle: "Один API для 100+ ведущих моделей.",
  accountPlaceholder: "Имя пользователя или email",
  usernamePlaceholder: "Имя пользователя",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Пароль (8–20 символов)",
  passwordLoginPlaceholder: "Пароль",
  codePlaceholder: "Код из письма",
  sendCode: "Получить код",
  sendingCode: "Отправка…",
  resendCode: (seconds) => `Повтор через ${seconds}с`,
  needCode: "Сначала получите и введите код из письма",
  needTurnstile: "Сначала пройдите проверку",
  needEmailForCode: "Сначала укажите email",
  needUsername: "Введите имя пользователя",
  needAccount: "Введите имя пользователя или email",
  usernameTooLong: "Имя пользователя не длиннее 20 символов",
  passwordLength: "Пароль должен быть 8–20 символов",
  emailInvalid: "Введите корректный email",
  emailTooLong: "Email не длиннее 50 символов",
  codeSent: "Код отправлен — проверьте почту",
  agreePrefix: "Я прочитал(а) и принимаю",
  termsLabel: "пользовательское соглашение",
  login: "Вход",
  register: "Регистрация",
  submitting: "Подождите…",
  registerSuccessLogin: "Регистрация успешна — войдите",
  needAgree: "Сначала примите соглашение",
  authFailed: "Ошибка входа — проверьте имя/email и пароль",
  keepLogin: "Оставаться в системе 30 дней",
  statusLoadFailed: "Не удалось загрузить настройки — обновите страницу",
};

const ja: AuthCopy = {
  title: "basedong へようこそ",
  brandName: "basedong",
  tagline: "すべての人のための AI。",
  subtitle: "1 つの API で 100 以上の主要モデルを利用。",
  accountPlaceholder: "ユーザー名またはメール",
  usernamePlaceholder: "ユーザー名",
  emailPlaceholder: "メール",
  passwordPlaceholder: "パスワード（8〜20 文字）",
  passwordLoginPlaceholder: "パスワード",
  codePlaceholder: "メール認証コード",
  sendCode: "コードを送信",
  sendingCode: "送信中…",
  resendCode: (seconds) => `${seconds}秒後に再送信`,
  needCode: "先にメール認証コードを取得して入力してください",
  needTurnstile: "先に人機検証を完了してください",
  needEmailForCode: "先にメールアドレスを入力してください",
  needUsername: "ユーザー名を入力してください",
  needAccount: "ユーザー名またはメールを入力してください",
  usernameTooLong: "ユーザー名は 20 文字以内にしてください",
  passwordLength: "パスワードは 8〜20 文字にしてください",
  emailInvalid: "有効なメールアドレスを入力してください",
  emailTooLong: "メールは 50 文字以内にしてください",
  codeSent: "認証コードを送信しました。メールをご確認ください",
  agreePrefix: "以下に同意します：",
  termsLabel: "利用規約",
  login: "ログイン",
  register: "登録",
  submitting: "お待ちください…",
  registerSuccessLogin: "登録が完了しました。ログインしてください",
  needAgree: "先に利用規約に同意してください",
  authFailed: "ログインに失敗しました。ユーザー名／メールとパスワードを確認してください",
  keepLogin: "30 日間ログインを保持",
  statusLoadFailed: "ログイン設定を読み込めません。更新して再試行してください",
};

const vi: AuthCopy = {
  title: "Chào mừng đến basedong",
  brandName: "basedong",
  tagline: "AI cho mọi người.",
  subtitle: "Một API cho hơn 100 mô hình hàng đầu.",
  accountPlaceholder: "Tên người dùng hoặc email",
  usernamePlaceholder: "Tên người dùng",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Mật khẩu (8–20 ký tự)",
  passwordLoginPlaceholder: "Mật khẩu",
  codePlaceholder: "Mã xác minh email",
  sendCode: "Gửi mã",
  sendingCode: "Đang gửi…",
  resendCode: (seconds) => `Gửi lại sau ${seconds}s`,
  needCode: "Vui lòng lấy và nhập mã xác minh email",
  needTurnstile: "Vui lòng hoàn tất xác minh",
  needEmailForCode: "Vui lòng nhập email trước",
  needUsername: "Vui lòng nhập tên người dùng",
  needAccount: "Vui lòng nhập tên người dùng hoặc email",
  usernameTooLong: "Tên người dùng không quá 20 ký tự",
  passwordLength: "Mật khẩu phải từ 8–20 ký tự",
  emailInvalid: "Vui lòng nhập email hợp lệ",
  emailTooLong: "Email không quá 50 ký tự",
  codeSent: "Đã gửi mã — vui lòng kiểm tra email",
  agreePrefix: "Tôi đã đọc và đồng ý",
  termsLabel: "Thỏa thuận người dùng",
  login: "Đăng nhập",
  register: "Đăng ký",
  submitting: "Vui lòng chờ…",
  registerSuccessLogin: "Đăng ký thành công — vui lòng đăng nhập",
  needAgree: "Vui lòng đồng ý thỏa thuận trước",
  authFailed: "Đăng nhập thất bại — kiểm tra tên/email và mật khẩu",
  keepLogin: "Duy trì đăng nhập 30 ngày",
  statusLoadFailed: "Không tải được cấu hình đăng nhập — làm mới và thử lại",
};

const ko: AuthCopy = {
  title: "basedong에 오신 것을 환영합니다",
  brandName: "basedong",
  tagline: "모든 사람을 위한 AI.",
  subtitle: "하나의 API로 100개 이상의 주요 모델을 이용하세요.",
  accountPlaceholder: "사용자 이름 또는 이메일",
  usernamePlaceholder: "사용자 이름",
  emailPlaceholder: "이메일",
  passwordPlaceholder: "비밀번호 (8–20자)",
  passwordLoginPlaceholder: "비밀번호",
  codePlaceholder: "이메일 인증 코드",
  sendCode: "코드 보내기",
  sendingCode: "전송 중…",
  resendCode: (seconds) => `${seconds}초 후 재전송`,
  needCode: "이메일 인증 코드를 받아 입력해 주세요",
  needTurnstile: "먼저 사람 확인을 완료해 주세요",
  needEmailForCode: "먼저 이메일을 입력해 주세요",
  needUsername: "사용자 이름을 입력해 주세요",
  needAccount: "사용자 이름 또는 이메일을 입력해 주세요",
  usernameTooLong: "사용자 이름은 20자 이하여야 합니다",
  passwordLength: "비밀번호는 8–20자여야 합니다",
  emailInvalid: "유효한 이메일 주소를 입력해 주세요",
  emailTooLong: "이메일은 50자 이하여야 합니다",
  codeSent: "인증 코드를 보냈습니다. 이메일을 확인해 주세요",
  agreePrefix: "다음에 동의합니다:",
  termsLabel: "이용약관",
  login: "로그인",
  register: "회원가입",
  submitting: "잠시만 기다려 주세요…",
  registerSuccessLogin: "가입이 완료되었습니다. 로그인해 주세요",
  needAgree: "먼저 이용약관에 동의해 주세요",
  authFailed: "로그인에 실패했습니다. 사용자 이름/이메일과 비밀번호를 확인해 주세요",
  keepLogin: "30일 동안 로그인 유지",
  statusLoadFailed: "로그인 설정을 불러올 수 없습니다. 새로고침 후 다시 시도해 주세요",
};

const de: AuthCopy = {
  title: "Willkommen bei basedong",
  brandName: "basedong",
  tagline: "KI für alle.",
  subtitle: "Eine API für über 100 führende Modelle.",
  accountPlaceholder: "Benutzername oder E-Mail",
  usernamePlaceholder: "Benutzername",
  emailPlaceholder: "E-Mail",
  passwordPlaceholder: "Passwort (8–20 Zeichen)",
  passwordLoginPlaceholder: "Passwort",
  codePlaceholder: "E-Mail-Bestätigungscode",
  sendCode: "Code senden",
  sendingCode: "Wird gesendet…",
  resendCode: (seconds) => `Erneut in ${seconds}s`,
  needCode: "Bitte Bestätigungscode abrufen und eingeben",
  needTurnstile: "Bitte zuerst die Verifizierung abschließen",
  needEmailForCode: "Bitte zuerst E-Mail eingeben",
  needUsername: "Bitte Benutzername eingeben",
  needAccount: "Bitte Benutzername oder E-Mail eingeben",
  usernameTooLong: "Benutzername darf höchstens 20 Zeichen haben",
  passwordLength: "Passwort muss 8–20 Zeichen haben",
  emailInvalid: "Bitte gültige E-Mail-Adresse eingeben",
  emailTooLong: "E-Mail darf höchstens 50 Zeichen haben",
  codeSent: "Code gesendet — bitte E-Mail prüfen",
  agreePrefix: "Ich habe gelesen und stimme zu:",
  termsLabel: "Nutzungsbedingungen",
  login: "Anmelden",
  register: "Registrieren",
  submitting: "Bitte warten…",
  registerSuccessLogin: "Registrierung erfolgreich — bitte anmelden",
  needAgree: "Bitte zuerst den Bedingungen zustimmen",
  authFailed: "Anmeldung fehlgeschlagen — Benutzername/E-Mail und Passwort prüfen",
  keepLogin: "30 Tage angemeldet bleiben",
  statusLoadFailed: "Anmeldeeinstellungen konnten nicht geladen werden",
};

const es: AuthCopy = {
  title: "Bienvenido a basedong",
  brandName: "basedong",
  tagline: "IA para todos.",
  subtitle: "Una API para más de 100 modelos líderes.",
  accountPlaceholder: "Usuario o correo",
  usernamePlaceholder: "Nombre de usuario",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña (8–20 caracteres)",
  passwordLoginPlaceholder: "Contraseña",
  codePlaceholder: "Código de verificación",
  sendCode: "Enviar código",
  sendingCode: "Enviando…",
  resendCode: (seconds) => `Reenviar en ${seconds}s`,
  needCode: "Obtenga e ingrese el código de verificación",
  needTurnstile: "Complete primero la verificación",
  needEmailForCode: "Ingrese primero su correo",
  needUsername: "Ingrese un nombre de usuario",
  needAccount: "Ingrese usuario o correo",
  usernameTooLong: "El usuario no puede superar 20 caracteres",
  passwordLength: "La contraseña debe tener 8–20 caracteres",
  emailInvalid: "Ingrese un correo válido",
  emailTooLong: "El correo no puede superar 50 caracteres",
  codeSent: "Código enviado — revise su correo",
  agreePrefix: "He leído y acepto",
  termsLabel: "el acuerdo de usuario",
  login: "Iniciar sesión",
  register: "Registrarse",
  submitting: "Espere…",
  registerSuccessLogin: "Registro exitoso — inicie sesión",
  needAgree: "Acepte primero el acuerdo de usuario",
  authFailed: "Error de inicio de sesión — revise usuario/correo y contraseña",
  keepLogin: "Mantener sesión 30 días",
  statusLoadFailed: "No se pudo cargar la configuración — actualice e intente de nuevo",
};

const ptBR: AuthCopy = {
  title: "Bem-vindo ao basedong",
  brandName: "basedong",
  tagline: "IA para todos.",
  subtitle: "Uma API para mais de 100 modelos líderes.",
  accountPlaceholder: "Usuário ou e-mail",
  usernamePlaceholder: "Nome de usuário",
  emailPlaceholder: "E-mail",
  passwordPlaceholder: "Senha (8–20 caracteres)",
  passwordLoginPlaceholder: "Senha",
  codePlaceholder: "Código de verificação",
  sendCode: "Enviar código",
  sendingCode: "Enviando…",
  resendCode: (seconds) => `Reenviar em ${seconds}s`,
  needCode: "Obtenha e insira o código de verificação",
  needTurnstile: "Conclua primeiro a verificação",
  needEmailForCode: "Informe seu e-mail primeiro",
  needUsername: "Informe um nome de usuário",
  needAccount: "Informe usuário ou e-mail",
  usernameTooLong: "O usuário não pode exceder 20 caracteres",
  passwordLength: "A senha deve ter 8–20 caracteres",
  emailInvalid: "Informe um e-mail válido",
  emailTooLong: "O e-mail não pode exceder 50 caracteres",
  codeSent: "Código enviado — verifique seu e-mail",
  agreePrefix: "Li e concordo com",
  termsLabel: "o acordo do usuário",
  login: "Entrar",
  register: "Cadastrar",
  submitting: "Aguarde…",
  registerSuccessLogin: "Cadastro concluído — faça login",
  needAgree: "Aceite o acordo do usuário primeiro",
  authFailed: "Falha no login — verifique usuário/e-mail e senha",
  keepLogin: "Manter login por 30 dias",
  statusLoadFailed: "Não foi possível carregar as configurações — atualize e tente novamente",
};

const ar: AuthCopy = {
  title: "مرحبًا بك في basedong",
  brandName: "basedong",
  tagline: "ذكاء اصطناعي للجميع.",
  subtitle: "واجهة API واحدة لأكثر من 100 نموذج رائد.",
  accountPlaceholder: "اسم المستخدم أو البريد",
  usernamePlaceholder: "اسم المستخدم",
  emailPlaceholder: "البريد الإلكتروني",
  passwordPlaceholder: "كلمة المرور (8–20 حرفًا)",
  passwordLoginPlaceholder: "كلمة المرور",
  codePlaceholder: "رمز التحقق من البريد",
  sendCode: "إرسال الرمز",
  sendingCode: "جارٍ الإرسال…",
  resendCode: (seconds) => `إعادة الإرسال خلال ${seconds} ث`,
  needCode: "يرجى الحصول على رمز التحقق وإدخاله",
  needTurnstile: "يرجى إكمال التحقق أولًا",
  needEmailForCode: "يرجى إدخال البريد أولًا",
  needUsername: "يرجى إدخال اسم المستخدم",
  needAccount: "يرجى إدخال اسم المستخدم أو البريد",
  usernameTooLong: "اسم المستخدم لا يتجاوز 20 حرفًا",
  passwordLength: "يجب أن تكون كلمة المرور 8–20 حرفًا",
  emailInvalid: "يرجى إدخال بريد إلكتروني صالح",
  emailTooLong: "البريد لا يتجاوز 50 حرفًا",
  codeSent: "تم إرسال الرمز — تحقق من بريدك",
  agreePrefix: "قرأتُ وأوافق على",
  termsLabel: "اتفاقية المستخدم",
  login: "تسجيل الدخول",
  register: "إنشاء حساب",
  submitting: "يرجى الانتظار…",
  registerSuccessLogin: "تم التسجيل — يرجى تسجيل الدخول",
  needAgree: "يرجى الموافقة على الاتفاقية أولًا",
  authFailed: "فشل تسجيل الدخول — تحقق من الاسم/البريد وكلمة المرور",
  keepLogin: "البقاء مسجّلًا 30 يومًا",
  statusLoadFailed: "تعذّر تحميل إعدادات الدخول — حدّث الصفحة",
};

const hi: AuthCopy = {
  title: "basedong में आपका स्वागत है",
  brandName: "basedong",
  tagline: "सभी के लिए AI।",
  subtitle: "100+ प्रमुख मॉडल के लिए एक API।",
  accountPlaceholder: "उपयोगकर्ता नाम या ईमेल",
  usernamePlaceholder: "उपयोगकर्ता नाम",
  emailPlaceholder: "ईमेल",
  passwordPlaceholder: "पासवर्ड (8–20 अक्षर)",
  passwordLoginPlaceholder: "पासवर्ड",
  codePlaceholder: "ईमेल सत्यापन कोड",
  sendCode: "कोड भेजें",
  sendingCode: "भेजा जा रहा है…",
  resendCode: (seconds) => `${seconds} सेकंड में पुनः भेजें`,
  needCode: "कृपया सत्यापन कोड प्राप्त करें और दर्ज करें",
  needTurnstile: "कृपया पहले सत्यापन पूरा करें",
  needEmailForCode: "कृपया पहले ईमेल दर्ज करें",
  needUsername: "कृपया उपयोगकर्ता नाम दर्ज करें",
  needAccount: "कृपया उपयोगकर्ता नाम या ईमेल दर्ज करें",
  usernameTooLong: "उपयोगकर्ता नाम 20 अक्षर से अधिक नहीं हो सकता",
  passwordLength: "पासवर्ड 8–20 अक्षर का होना चाहिए",
  emailInvalid: "कृपया मान्य ईमेल दर्ज करें",
  emailTooLong: "ईमेल 50 अक्षर से अधिक नहीं हो सकता",
  codeSent: "कोड भेज दिया गया — अपना ईमेल देखें",
  agreePrefix: "मैंने पढ़ लिया है और सहमत हूँ",
  termsLabel: "उपयोगकर्ता समझौता",
  login: "लॉग इन",
  register: "पंजीकरण",
  submitting: "कृपया प्रतीक्षा करें…",
  registerSuccessLogin: "पंजीकरण सफल — कृपया लॉग इन करें",
  needAgree: "कृपया पहले समझौते से सहमत हों",
  authFailed: "लॉगिन विफल — उपयोगकर्ता/ईमेल और पासवर्ड जाँचें",
  keepLogin: "30 दिनों तक लॉग इन रखें",
  statusLoadFailed: "लॉगिन सेटिंग लोड नहीं हो सकी — पृष्ठ refresh करें",
};

const id: AuthCopy = {
  title: "Selamat datang di basedong",
  brandName: "basedong",
  tagline: "AI untuk semua orang.",
  subtitle: "Satu API untuk 100+ model terkemuka.",
  accountPlaceholder: "Nama pengguna atau email",
  usernamePlaceholder: "Nama pengguna",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Kata sandi (8–20 karakter)",
  passwordLoginPlaceholder: "Kata sandi",
  codePlaceholder: "Kode verifikasi email",
  sendCode: "Kirim kode",
  sendingCode: "Mengirim…",
  resendCode: (seconds) => `Kirim ulang dalam ${seconds} d`,
  needCode: "Silakan dapatkan dan masukkan kode verifikasi",
  needTurnstile: "Selesaikan verifikasi terlebih dahulu",
  needEmailForCode: "Masukkan email terlebih dahulu",
  needUsername: "Masukkan nama pengguna",
  needAccount: "Masukkan nama pengguna atau email",
  usernameTooLong: "Nama pengguna tidak boleh lebih dari 20 karakter",
  passwordLength: "Kata sandi harus 8–20 karakter",
  emailInvalid: "Masukkan alamat email yang valid",
  emailTooLong: "Email tidak boleh lebih dari 50 karakter",
  codeSent: "Kode terkirim — periksa email Anda",
  agreePrefix: "Saya telah membaca dan setuju dengan",
  termsLabel: "Perjanjian Pengguna",
  login: "Masuk",
  register: "Daftar",
  submitting: "Harap tunggu…",
  registerSuccessLogin: "Pendaftaran berhasil — silakan masuk",
  needAgree: "Setujui perjanjian pengguna terlebih dahulu",
  authFailed: "Gagal masuk — periksa nama/email dan kata sandi",
  keepLogin: "Tetap masuk selama 30 hari",
  statusLoadFailed: "Tidak dapat memuat pengaturan masuk — muat ulang halaman",
};

const AUTH_COPY: Record<TargetLocale, AuthCopy> = {
  "zh-CN": zhCN,
  en,
  "zh-TW": zhTW,
  fr,
  ru,
  ja,
  vi,
  ko,
  de,
  es,
  "pt-BR": ptBR,
  ar,
  hi,
  id,
};

export function getAuthCopy(locale: string): AuthCopy {
  return pickTargetCatalog(locale, AUTH_COPY);
}
